// Created by Crowbar 0.71

$modelname "titans/buddy/titan_buddy_MP_core.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_intBase" ""
$jointsurfaceprop "def_c_cam" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_l_hip" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_thighLow" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_hip" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_thighLow" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_c_hatchTop" ""
$jointsurfaceprop "def_c_hatchBot" ""
$jointsurfaceprop "def_c_hatchHead" ""
$jointsurfaceprop "def_c_neck1" ""
$jointsurfaceprop "def_c_eye_rotate" ""
$jointsurfaceprop "def_c_eye_detached" ""
$jointsurfaceprop "def_c_eyeball" ""
$jointsurfaceprop "def_c_eye_outer" ""
$jointsurfaceprop "def_c_eyelid" ""
$jointsurfaceprop "def_l_eyelid" ""
$jointsurfaceprop "def_r_eyelid" ""
$jointsurfaceprop "def_l_eye_side" ""
$jointsurfaceprop "def_r_eye_side" ""
$jointsurfaceprop "def_l_eye_side_cover" ""
$jointsurfaceprop "def_r_eye_side_cover" ""
$jointsurfaceprop "def_l_piston_rear_knee1" ""
$jointsurfaceprop "def_l_piston_rear_knee2" ""
$jointsurfaceprop "def_r_piston_rear_knee1" ""
$jointsurfaceprop "def_r_piston_rear_knee2" ""
$jointsurfaceprop "def_cam_shoulder" ""
$jointsurfaceprop "def_l_missile_root" ""
$jointsurfaceprop "def_l_missile_leg1" ""
$jointsurfaceprop "def_l_missile_leg2" ""
$jointsurfaceprop "def_l_missile_leg3" ""
$jointsurfaceprop "def_l_missile_leg4" ""
$jointsurfaceprop "def_l_missile_wing_out1" ""
$jointsurfaceprop "def_l_missile_wing_out2" ""
$jointsurfaceprop "def_l_missile_wing_out_hook1" ""
$jointsurfaceprop "def_l_missile_wing_out_hook2" ""
$jointsurfaceprop "def_l_missile_wing_in1" ""
$jointsurfaceprop "def_l_missile_wing_in2" ""
$jointsurfaceprop "def_l_missile_wing_in_hook1" ""
$jointsurfaceprop "def_l_missile_wing_in_hook2" ""
$jointsurfaceprop "def_l_missile_box" ""
$jointsurfaceprop "def_l_holder" ""
$jointsurfaceprop "def_l_holder_clip1" ""
$jointsurfaceprop "def_l_holder_clip2" ""
$jointsurfaceprop "def_r_missile_root" ""
$jointsurfaceprop "def_r_missile_leg1" ""
$jointsurfaceprop "def_r_missile_leg2" ""
$jointsurfaceprop "def_r_missile_leg3" ""
$jointsurfaceprop "def_r_missile_leg4" ""
$jointsurfaceprop "def_r_missile_wing_out1" ""
$jointsurfaceprop "def_r_missile_wing_out2" ""
$jointsurfaceprop "def_r_missile_wing_out_hook1" ""
$jointsurfaceprop "def_r_missile_wing_out_hook2" ""
$jointsurfaceprop "def_r_missile_wing_in1" ""
$jointsurfaceprop "def_r_missile_wing_in2" ""
$jointsurfaceprop "def_r_missile_wing_in_hook1" ""
$jointsurfaceprop "def_r_missile_wing_in_hook2" ""
$jointsurfaceprop "def_r_missile_box" ""
$jointsurfaceprop "def_r_holder" ""
$jointsurfaceprop "def_r_holder_clip1" ""
$jointsurfaceprop "def_r_holder_clip2" ""
$jointsurfaceprop "def_r_down_missile_doorA1" ""
$jointsurfaceprop "def_r_down_missile_doorB1" ""
$jointsurfaceprop "def_r_down_missile_doorC1" ""
$jointsurfaceprop "def_r_up_missile_doorA1" ""
$jointsurfaceprop "def_r_up_missile_doorB1" ""
$jointsurfaceprop "def_r_up_missile_doorC1" ""
$jointsurfaceprop "def_l_down_missile_doorC1" ""
$jointsurfaceprop "def_l_down_missile_doorB1" ""
$jointsurfaceprop "def_l_down_missile_doorA1" ""
$jointsurfaceprop "def_l_up_missile_doorC1" ""
$jointsurfaceprop "def_l_up_missile_doorB1" ""
$jointsurfaceprop "def_l_up_missile_doorA1" ""
$jointsurfaceprop "def_l_shock_waist_front_up" ""
$jointsurfaceprop "def_l_shock_waist_side_up" ""
$jointsurfaceprop "def_l_shock_waist_back_up" ""
$jointsurfaceprop "def_r_shock_waist_front_up" ""
$jointsurfaceprop "def_r_shock_waist_side_up" ""
$jointsurfaceprop "def_r_shock_waist_back_up" ""
$jointsurfaceprop "def_l_shock_waist_front_down" ""
$jointsurfaceprop "def_l_shock_waist_side_down" ""
$jointsurfaceprop "def_l_shock_waist_back_down" ""
$jointsurfaceprop "def_r_shock_waist_front_down" ""
$jointsurfaceprop "def_r_shock_waist_side_down" ""
$jointsurfaceprop "def_r_shock_waist_back_down" ""
$jointsurfaceprop "def_l_shock_knee_up" ""
$jointsurfaceprop "def_l_shock_knee_down" ""
$jointsurfaceprop "def_r_shock_knee_up" ""
$jointsurfaceprop "def_r_shock_knee_down" ""
$jointsurfaceprop "def_l_heel" ""
$jointsurfaceprop "def_l_heel_shock_start" ""
$jointsurfaceprop "def_l_heel_shock_end" ""
$jointsurfaceprop "def_r_heel" ""
$jointsurfaceprop "def_r_heel_shock_start" ""
$jointsurfaceprop "def_r_heel_shock_end" ""
$jointsurfaceprop "jx_l_ankle_hb" ""
$jointsurfaceprop "jx_r_ankle_hb" ""
$jointsurfaceprop "jx_c_hatch_1_hb" ""
$jointsurfaceprop "jx_c_hatch_2_hb" ""
$jointsurfaceprop "jx_c_hatch_3_hb" ""
$jointsurfaceprop "jx_c_hatch_4_hb" ""
$jointsurfaceprop "jx_c_hatch_5_hb" ""
$jointsurfaceprop "jx_vortex" ""
$jointsurfaceprop "def_l_battery1" ""
$jointsurfaceprop "def_l_battery2" ""
$jointsurfaceprop "def_l_battery3" ""
$jointsurfaceprop "jx_c_camera_2" ""
$jointsurfaceprop "jx_c_camera_3" ""
$jointsurfaceprop "jx_c_origin" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_intBase" "notsolid"
$jointcontents "def_c_cam" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_l_hip" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_thighLow" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_hip" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_thighLow" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_c_hatchTop" "notsolid"
$jointcontents "def_c_hatchBot" "notsolid"
$jointcontents "def_c_hatchHead" "notsolid"
$jointcontents "def_c_neck1" "notsolid"
$jointcontents "def_c_eye_rotate" "notsolid"
$jointcontents "def_c_eye_detached" "notsolid"
$jointcontents "def_c_eyeball" "notsolid"
$jointcontents "def_c_eye_outer" "notsolid"
$jointcontents "def_c_eyelid" "notsolid"
$jointcontents "def_l_eyelid" "notsolid"
$jointcontents "def_r_eyelid" "notsolid"
$jointcontents "def_l_eye_side" "notsolid"
$jointcontents "def_r_eye_side" "notsolid"
$jointcontents "def_l_eye_side_cover" "notsolid"
$jointcontents "def_r_eye_side_cover" "notsolid"
$jointcontents "def_l_piston_rear_knee1" "notsolid"
$jointcontents "def_l_piston_rear_knee2" "notsolid"
$jointcontents "def_r_piston_rear_knee1" "notsolid"
$jointcontents "def_r_piston_rear_knee2" "notsolid"
$jointcontents "def_cam_shoulder" "notsolid"
$jointcontents "def_l_missile_root" "notsolid"
$jointcontents "def_l_missile_leg1" "notsolid"
$jointcontents "def_l_missile_leg2" "notsolid"
$jointcontents "def_l_missile_leg3" "notsolid"
$jointcontents "def_l_missile_leg4" "notsolid"
$jointcontents "def_l_missile_wing_out1" "notsolid"
$jointcontents "def_l_missile_wing_out2" "notsolid"
$jointcontents "def_l_missile_wing_out_hook1" "notsolid"
$jointcontents "def_l_missile_wing_out_hook2" "notsolid"
$jointcontents "def_l_missile_wing_in1" "notsolid"
$jointcontents "def_l_missile_wing_in2" "notsolid"
$jointcontents "def_l_missile_wing_in_hook1" "notsolid"
$jointcontents "def_l_missile_wing_in_hook2" "notsolid"
$jointcontents "def_l_missile_box" "notsolid"
$jointcontents "def_l_holder" "notsolid"
$jointcontents "def_l_holder_clip1" "notsolid"
$jointcontents "def_l_holder_clip2" "notsolid"
$jointcontents "def_r_missile_root" "notsolid"
$jointcontents "def_r_missile_leg1" "notsolid"
$jointcontents "def_r_missile_leg2" "notsolid"
$jointcontents "def_r_missile_leg3" "notsolid"
$jointcontents "def_r_missile_leg4" "notsolid"
$jointcontents "def_r_missile_wing_out1" "notsolid"
$jointcontents "def_r_missile_wing_out2" "notsolid"
$jointcontents "def_r_missile_wing_out_hook1" "notsolid"
$jointcontents "def_r_missile_wing_out_hook2" "notsolid"
$jointcontents "def_r_missile_wing_in1" "notsolid"
$jointcontents "def_r_missile_wing_in2" "notsolid"
$jointcontents "def_r_missile_wing_in_hook1" "notsolid"
$jointcontents "def_r_missile_wing_in_hook2" "notsolid"
$jointcontents "def_r_missile_box" "notsolid"
$jointcontents "def_r_holder" "notsolid"
$jointcontents "def_r_holder_clip1" "notsolid"
$jointcontents "def_r_holder_clip2" "notsolid"
$jointcontents "def_r_down_missile_doorA1" "notsolid"
$jointcontents "def_r_down_missile_doorB1" "notsolid"
$jointcontents "def_r_down_missile_doorC1" "notsolid"
$jointcontents "def_r_up_missile_doorA1" "notsolid"
$jointcontents "def_r_up_missile_doorB1" "notsolid"
$jointcontents "def_r_up_missile_doorC1" "notsolid"
$jointcontents "def_l_down_missile_doorC1" "notsolid"
$jointcontents "def_l_down_missile_doorB1" "notsolid"
$jointcontents "def_l_down_missile_doorA1" "notsolid"
$jointcontents "def_l_up_missile_doorC1" "notsolid"
$jointcontents "def_l_up_missile_doorB1" "notsolid"
$jointcontents "def_l_up_missile_doorA1" "notsolid"
$jointcontents "def_l_shock_waist_front_up" "notsolid"
$jointcontents "def_l_shock_waist_side_up" "notsolid"
$jointcontents "def_l_shock_waist_back_up" "notsolid"
$jointcontents "def_r_shock_waist_front_up" "notsolid"
$jointcontents "def_r_shock_waist_side_up" "notsolid"
$jointcontents "def_r_shock_waist_back_up" "notsolid"
$jointcontents "def_l_shock_waist_front_down" "notsolid"
$jointcontents "def_l_shock_waist_side_down" "notsolid"
$jointcontents "def_l_shock_waist_back_down" "notsolid"
$jointcontents "def_r_shock_waist_front_down" "notsolid"
$jointcontents "def_r_shock_waist_side_down" "notsolid"
$jointcontents "def_r_shock_waist_back_down" "notsolid"
$jointcontents "def_l_shock_knee_up" "notsolid"
$jointcontents "def_l_shock_knee_down" "notsolid"
$jointcontents "def_r_shock_knee_up" "notsolid"
$jointcontents "def_r_shock_knee_down" "notsolid"
$jointcontents "def_l_heel" "notsolid"
$jointcontents "def_l_heel_shock_start" "notsolid"
$jointcontents "def_l_heel_shock_end" "notsolid"
$jointcontents "def_r_heel" "notsolid"
$jointcontents "def_r_heel_shock_start" "notsolid"
$jointcontents "def_r_heel_shock_end" "notsolid"
$jointcontents "jx_l_ankle_hb" "notsolid"
$jointcontents "jx_r_ankle_hb" "notsolid"
$jointcontents "jx_c_hatch_1_hb" "notsolid"
$jointcontents "jx_c_hatch_2_hb" "notsolid"
$jointcontents "jx_c_hatch_3_hb" "notsolid"
$jointcontents "jx_c_hatch_4_hb" "notsolid"
$jointcontents "jx_c_hatch_5_hb" "notsolid"
$jointcontents "jx_vortex" "notsolid"
$jointcontents "def_l_battery1" "notsolid"
$jointcontents "def_l_battery2" "notsolid"
$jointcontents "def_l_battery3" "notsolid"
$jointcontents "jx_c_camera_2" "notsolid"
$jointcontents "jx_c_camera_3" "notsolid"
$jointcontents "jx_c_origin" "notsolid"

$illumposition 0.001 14.247 165.982

$eyeposition 0 0 220

$cdmaterials ""

$attachment "HEADFOCUS" "def_c_eye_rotate" 0 0 0 rotate -90 -90 0

$cbox 0 0 0 0 0 0

$bbox -68.494 -167.616 -10.826 40 167.618 232.135

$hboxset "default"
$hbox 3 "def_c_hip" -26.056641 -28.256638 -32.149147 26.056641 16.637367 38.928268 ""
$hbox 2 "def_c_spineB" -19.684999 -2.114169 -19.684999 19.684999 8.119275 19.684999 ""
$hbox 2 "def_c_spineC" 17.113352 19.131458 -31.474346 46.786522 51.156982 15.303513 ""
$hbox 2 "def_c_spineC" -17.485792 22.0909 -53.867611 17.485792 59.975868 11.166513 ""
$hbox 2 "def_c_spineC" -23.121607 -9.501556 -29.323172 23.121607 2.900782 33.051903 ""
$hbox 2 "def_c_spineC" -27.716875 1.840941 -35.222767 27.716875 23.757038 34.452293 ""
$hbox 2 "def_c_spineC" -16.677132 22.961765 4.692904 16.677132 57.67902 42.772354 ""
$hbox 2 "def_c_spineC" -47.464867 19.720827 -32.483795 -13.937374 49.445572 10.003524 ""
$hbox 6 "def_l_ankle" -15.501938 -10.50864 -14.077925 29.804667 5.293296 14.077925 ""
$hbox 4 "def_l_elbow" -0.485038 -9.654705 -14.700365 41.759365 11.443678 10.303523 ""
$hbox 6 "def_l_knee" -0.416928 -14.385405 -11.154308 38.952679 8.759432 11.154308 ""
$hbox 4 "def_l_shoulder" -1.443304 -11.974386 -14.59249 38.138115 11.93974 14.59249 ""
$hbox 6 "def_l_thigh" -14.184224 -18.553112 -16.12792 54.436115 18.553112 16.12792 ""
$hbox 6 "def_l_thighLow" -0.082677 -11.30549 -11.317301 39.28693 18.594452 11.317301 ""
$hbox 4 "def_l_wrist" 0.570865 -5.599989 -13.025958 39.992046 7.89526 9.212187 ""
$hbox 7 "def_r_ankle" -29.804667 -5.293296 -14.077925 15.501938 10.50864 14.077925 ""
$hbox 5 "def_r_elbow" -41.759758 -11.448402 -10.305491 0.485038 9.649981 14.698396 ""
$hbox 7 "def_r_knee" -38.952679 -8.759432 -11.154308 0.416928 14.385405 11.154308 ""
$hbox 5 "def_r_shoulder" -38.138115 -11.93974 -14.59249 1.443304 11.974386 14.59249 ""
$hbox 7 "def_r_thigh" -54.436115 -18.553112 -16.12792 14.184224 18.553112 16.12792 ""
$hbox 7 "def_r_thighLow" -39.28693 -18.594452 -11.317301 0.082677 11.30549 11.317301 ""
$hbox 5 "def_r_wrist" -39.990868 -7.894866 -9.219273 -0.571652 5.599595 13.018872 ""
$hboxset "entryboxes"
$hbox 1 "jx_c_delta" -39.99992 0 0 39.99992 99.999802 139.999725 ""
$hboxset "EFFECTS_TORSO"
$hbox 3 "def_c_hip" -26.056641 -28.256638 -32.149147 26.056641 16.637367 38.928268 ""
$hbox 2 "def_c_spineB" -19.684999 -2.114169 -19.684999 19.684999 8.119275 19.684999 ""
$hbox 2 "def_c_spineC" 17.113352 19.131458 -31.474346 46.786522 51.156982 15.303513 ""
$hbox 2 "def_c_spineC" -17.485792 22.0909 -53.867611 17.485792 59.975868 11.166513 ""
$hbox 2 "def_c_spineC" -23.121607 -9.501556 -29.323172 23.121607 2.900782 33.051903 ""
$hbox 2 "def_c_spineC" -27.716875 1.840941 -35.222767 27.716875 23.757038 34.452293 ""
$hbox 2 "def_c_spineC" -16.677132 22.961765 4.692904 16.677132 57.67902 42.772354 ""
$hbox 2 "def_c_spineC" -47.464867 19.720827 -32.483795 -13.937374 49.445572 10.003524 ""
$skipboneinbbox

$screenalign def_l_thigh "sphere"
$screenalign def_l_ankle "cylinder"
$screenalign def_l_ball "cylinder"
$screenalign def_r_thigh "cylinder"
$screenalign def_r_thighLow "sphere"
$screenalign def_r_knee "sphere"
$screenalign def_r_ankle "sphere"
$screenalign def_r_ball "sphere"
$screenalign def_r_kneeB "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "sphere"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_l_finPinkyA "sphere"
$screenalign def_l_finRingA "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "sphere"
$screenalign def_l_finMidC "sphere"
$screenalign def_l_finIndexA "sphere"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finIndexC "sphere"
$screenalign def_r_piston_rear_knee1 "cylinder"
$screenalign def_r_piston_rear_knee2 "sphere"
$screenalign def_r_shock_knee_up "sphere"
$screenalign def_r_shock_knee_down "sphere"
$screenalign def_l_heel "cylinder"
$screenalign def_l_heel_shock_end "cylinder"
$screenalign def_r_heel "sphere"
$screenalign def_r_heel_shock_start "sphere"
$screenalign def_r_heel_shock_end "sphere"
$screenalign jx_r_ankle_hb "cylinder"
$screenalign jx_c_hatch_1_hb "sphere"
$screenalign jx_c_hatch_2_hb "sphere"
$screenalign jx_c_hatch_3_hb "sphere"
$screenalign jx_c_hatch_4_hb "sphere"
$screenalign jx_c_hatch_5_hb "sphere"
$screenalign def_l_battery1 "cylinder"
$screenalign def_l_battery2 "cylinder"
$screenalign def_l_battery3 "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 205.41214 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 128.382584 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 18.230331 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 18.101944 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -23.494019 32.095646 0 0 0 0 0 0 0 0 0
$definebone "def_c_intBase" "def_c_spineC" 0 22.637772 -10.026639 0 0 0 0 0 0 0 0 0
$definebone "def_c_cam" "def_c_spineC" 11.92436 58.197601 9.257601 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 27.730637 -0.770296 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 14.250473 3.081182 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 12.838257 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 21.440704 20.611954 -10.184802 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 26.678253 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 14.577797 -0.034866 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 30.95401 -0.036438 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 33.962181 -0.009247 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 22.262924 -0.009247 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulderMid" 30.95401 -0.036438 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -21.440704 20.611938 -10.184783 0 0 179.99995 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -26.678093 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -14.577923 0.035034 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -30.953876 0.036224 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -33.962532 0.009445 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -22.262947 0.009445 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulderMid" -30.953876 0.036224 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_hip" "def_c_hip" 10.269186 -7.287552 1.29411 0 0 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_l_hip" 13.153353 0 0 -5.975595 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_thighLow" "def_l_thigh" 46.445686 0 0 0 -58.138761 0 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thighLow" 27.332199 -0.000011 0 0 49.144864 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 30.113514 -0.000002 0.000004 0 23.663494 -179.99995 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 21.867176 0.000001 -0.000002 0 -58.296129 0 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thighLow" 27.332199 -0.000011 0 0 49.144864 0 0 0 0 0 0 0
$definebone "def_r_hip" "def_c_hip" -10.269192 -7.287552 1.294112 0 0 179.99995 0 0 0 0 0 0
$definebone "def_r_thigh" "def_r_hip" -13.153358 0 0 -5.975595 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_r_thighLow" "def_r_thigh" -46.445595 0.000001 0 0 -58.138761 0.000002 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thighLow" -27.332275 -0.000103 0 0.000001 49.144864 0.000003 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -30.113447 0.000004 -0.000002 0.000002 23.663493 179.999923 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -21.867199 0.000015 0 0 -58.296129 0 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thighLow" -27.332275 -0.000103 0 0.000001 49.144864 0.000003 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -18.072998 10.743011 -11.2882 0 -60.000002 0 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -9.96534 -0.000366 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -16.316849 0.000427 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -49.919006 2.60701 -12.5817 -7.986965 -4.034867 0.561547 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -17.335678 0.000046 0.000061 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -17.303375 0.000259 -0.000132 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -51.898987 1.989975 2.4909 2.664609 -3.774691 -0.175737 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -18.214111 -0.000793 -0.000067 -0.015875 0.022383 0.00104 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -18.289734 0.000381 0.000064 0 0 0 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -33.880005 1.194992 7.631501 0 0 0 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -14.29599 0 10.273399 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -17.335098 0.000366 0.000053 0.674843 0.004337 -0.044802 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -15.292389 0.000061 -0.000034 0.000002 0 0 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" -14.29599 0.000031 27.300001 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -17.335068 0.000351 0.00005 0.674843 0.004337 -0.044802 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -15.292389 0.000015 -0.000031 0.000002 0 0 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 33.880707 -1.195313 -7.631406 0 0 0 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" 10.343628 0 -27.299999 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 17.335297 0.000015 0.000011 0.674843 0.004338 -0.044802 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 15.292435 -0.000046 -0.000004 0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 14.295349 0 -10.273407 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 17.335281 -0.000015 0.000002 0.674843 0.004338 -0.044802 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 15.29245 0.000031 -0.000002 0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 51.899139 -1.990082 -2.490812 2.664609 -3.774691 -0.175737 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 18.214203 0 0 -0.015875 0.022383 0.00104 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 18.289703 -0.000061 -0.000003 0 0 0 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 49.919678 -2.607758 12.58179 -7.986965 -4.034867 0.561547 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 17.335205 -0.000031 0 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 17.303894 0.000031 0.000002 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 18.073822 -10.743774 11.288211 0 -60.000002 0 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 9.965164 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 16.316956 0 0 0 0 0 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 12.846619 -4.144196 0.731267 -0.112595 0.077172 -0.000076 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -12.846436 4.144089 -0.731257 -0.112595 0.077172 -0.000076 0 0 0 0 0 0
$definebone "def_c_hatchTop" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hatchBot" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hatchHead" "def_c_spineC" 0 58.896729 -8.825905 0 0 0 0 0 0 0 0 0
$definebone "def_c_neck1" "def_c_hatchTop" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_rotate" "def_c_neck1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_detached" "def_c_eye_rotate" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eyeball" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_outer" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eye_side" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eye_side" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eye_side_cover" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eye_side_cover" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_piston_rear_knee1" "def_l_thigh" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_piston_rear_knee2" "def_l_thighLow" 0 0 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_piston_rear_knee1" "def_r_thigh" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_piston_rear_knee2" "def_r_thighLow" 0 0 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_cam_shoulder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_root" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg1" "def_l_missile_root" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg2" "def_l_missile_leg1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg3" "def_l_missile_leg2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg4" "def_l_missile_leg3" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out1" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out2" "def_l_missile_wing_out1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out_hook1" "def_l_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out_hook2" "def_l_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in1" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in2" "def_l_missile_wing_in1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in_hook1" "def_l_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in_hook2" "def_l_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_box" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder_clip1" "def_l_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder_clip2" "def_l_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_root" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg1" "def_r_missile_root" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg2" "def_r_missile_leg1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg3" "def_r_missile_leg2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg4" "def_r_missile_leg3" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out1" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out2" "def_r_missile_wing_out1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out_hook1" "def_r_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out_hook2" "def_r_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in1" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in2" "def_r_missile_wing_in1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in_hook1" "def_r_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in_hook2" "def_r_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_box" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder_clip1" "def_r_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder_clip2" "def_r_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_down_missile_doorA1" "def_r_missile_box" -3.012396 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_down_missile_doorB1" "def_r_missile_box" 0.027008 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_down_missile_doorC1" "def_r_missile_box" 3.114403 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_up_missile_doorA1" "def_r_missile_box" -3.012396 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_r_up_missile_doorB1" "def_r_missile_box" 0.027047 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_r_up_missile_doorC1" "def_r_missile_box" 3.1146 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_down_missile_doorC1" "def_l_missile_box" -3.114389 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_down_missile_doorB1" "def_l_missile_box" -0.026994 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_down_missile_doorA1" "def_l_missile_box" 3.012392 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_up_missile_doorC1" "def_l_missile_box" -3.114573 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_up_missile_doorB1" "def_l_missile_box" -0.027032 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_up_missile_doorA1" "def_l_missile_box" 3.012391 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_front_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_side_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_back_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_front_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_side_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_back_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_front_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_side_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_back_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_front_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_side_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_back_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_knee_up" "def_l_thighLow" 0 0 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_knee_down" "def_l_knee" 0 -0.000002 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_knee_up" "def_r_thighLow" 0 0 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_knee_down" "def_r_knee" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel" "def_l_ankle" 0.000004 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel_shock_start" "def_l_knee" 0 -0.000002 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel_shock_end" "def_l_heel" 0.000004 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel" "def_r_ankle" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel_shock_start" "def_r_knee" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel_shock_end" "def_r_heel" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_l_ankle_hb" "def_l_ankle" 0.000004 -0.000001 0.000008 0 -54.429153 -90.000003 0 0 0 0 0 0
$definebone "jx_r_ankle_hb" "def_r_ankle" -0.000004 0.000002 0 0 125.570774 -90.000003 0 0 0 0 0 0
$definebone "jx_c_hatch_1_hb" "def_c_spineC" 0.000041 176.631027 -22.913513 -89.999962 0 0 0 0 0 0 0 0
$definebone "jx_c_hatch_2_hb" "jx_c_hatch_1_hb" 40 0 0 0 -20.55604 0 0 0 0 0 0 0
$definebone "jx_c_hatch_3_hb" "jx_c_hatch_2_hb" 42.720016 -0.000031 0 0 -18.103758 0 0 0 0 0 0 0
$definebone "jx_c_hatch_4_hb" "jx_c_hatch_3_hb" 64.031258 0 0 0 -35.394792 0 0 0 0 0 0 0
$definebone "jx_c_hatch_5_hb" "jx_c_hatch_4_hb" 36.400558 0 0 0 -15.945394 0 0 0 0 0 0 0
$definebone "jx_vortex" "def_r_elbow" -22.263123 0.009293 0.000049 -0.000158 -179.99995 -30.000001 0 0 0 0 0 0
$definebone "def_l_battery1" "def_c_spineC" 24.313248 -6.626495 12.072434 -20.247998 -43.921002 -11.247999 0 0 0 0 0 0
$definebone "def_l_battery2" "def_c_spineC" 26.246765 -8.354889 2.264471 -13.127999 -38.161992 -13.077999 0 0 0 0 0 0
$definebone "def_l_battery3" "def_c_spineC" 28.255947 -7.03009 -7.913634 -4.381 -30.610002 -13.026999 0 0 0 0 0 0
$definebone "jx_c_camera_2" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera_3" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_origin" "" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "def_r_knee"
$bonemerge "def_r_kneeB"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"
$bonemerge "def_r_shock_knee_down"
$bonemerge "def_r_heel_shock_start"
$bonemerge "jx_c_hatch_1_hb"
$bonemerge "jx_c_hatch_2_hb"
$bonemerge "jx_c_hatch_3_hb"
$bonemerge "jx_c_hatch_4_hb"
$bonemerge "jx_c_hatch_5_hb"
$bonemerge "jx_vortex"


$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_thighLow" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position rotation
$bonesaveframe "def_r_ankle" position
$bonesaveframe "def_r_ball" position
$bonesaveframe "def_r_kneeB" position rotation
$bonesaveframe "def_r_finIndexA" position rotation
$bonesaveframe "def_r_finIndexB" position rotation
$bonesaveframe "def_r_finIndexC" position rotation
$bonesaveframe "def_r_finMidA" position rotation
$bonesaveframe "def_r_finMidB" position rotation
$bonesaveframe "def_r_finMidC" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finMidA" position rotation
$bonesaveframe "def_l_finMidB" position rotation
$bonesaveframe "def_l_finMidC" position rotation
$bonesaveframe "def_l_finIndexA" position rotation
$bonesaveframe "def_l_finIndexB" position rotation
$bonesaveframe "def_l_finIndexC" position rotation
$bonesaveframe "ja_l_propHand" position rotation
$bonesaveframe "ja_r_propHand" position rotation
$bonesaveframe "def_l_piston_rear_knee1" position
$bonesaveframe "def_l_piston_rear_knee2" position
$bonesaveframe "def_r_piston_rear_knee1" position
$bonesaveframe "def_l_shock_knee_up" position
$bonesaveframe "def_l_shock_knee_down" position
$bonesaveframe "def_r_shock_knee_down" position rotation
$bonesaveframe "def_l_heel_shock_start" position
$bonesaveframe "def_r_heel" position
$bonesaveframe "def_r_heel_shock_start" position rotation
$bonesaveframe "def_r_heel_shock_end" position
$bonesaveframe "jx_c_hatch_1_hb" rotation
$bonesaveframe "jx_c_hatch_2_hb" rotation
$bonesaveframe "jx_c_hatch_3_hb" rotation
$bonesaveframe "jx_c_hatch_4_hb" rotation
$bonesaveframe "jx_c_hatch_5_hb" rotation
$bonesaveframe "jx_vortex" rotation
$bonesaveframe "def_l_battery1" position rotation
$bonesaveframe "def_l_battery2" position rotation
$bonesaveframe "def_l_battery3" position rotation

$weightlist "weights_mp_stand_shootGeneric_add" {
	 "jx_c_delta" 0
	 "jx_c_start" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0.1
	 "def_c_spineA" 0.4
	 "def_c_spineB" 0.6
	 "def_c_spineC" 1
	 "ja_c_propGun" 1
	 "def_c_intBase" 1
	 "def_c_cam" 1
	 "def_c_neckA" 1
	 "jx_c_neckB" 1
	 "def_c_neckB" 1
	 "def_c_head" 1
	 "def_l_clav" 1
	 "def_l_shoulder" 1
	 "def_l_shoulderMid" 1
	 "def_l_elbow" 1
	 "def_l_wrist" 1
	 "def_l_forearm" 1
	 "def_l_elbowB" 1
	 "def_l_shoulderTwist" 1
	 "def_r_clav" 1
	 "def_r_shoulder" 1
	 "def_r_shoulderMid" 1
	 "def_r_elbow" 1
	 "def_r_wrist" 1
	 "def_r_forearm" 1
	 "def_r_elbowB" 1
	 "def_r_shoulderTwist" 1
	 "def_l_hip" 0.1
	 "def_l_thigh" 0
	 "def_l_thighLow" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_hip" 0.1
	 "def_r_thigh" 0
	 "def_r_thighLow" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "def_r_finThumbA" 1
	 "def_r_finThumbB" 1
	 "def_r_finThumbC" 1
	 "def_r_finIndexA" 1
	 "def_r_finIndexB" 1
	 "def_r_finIndexC" 1
	 "def_r_finMidA" 1
	 "def_r_finMidB" 1
	 "def_r_finMidC" 1
	 "def_r_finRingCarpal" 1
	 "def_r_finRingA" 1
	 "def_r_finRingB" 1
	 "def_r_finRingC" 1
	 "def_r_finPinkyA" 1
	 "def_r_finPinkyB" 1
	 "def_r_finPinkyC" 1
	 "def_l_finRingCarpal" 1
	 "def_l_finPinkyA" 1
	 "def_l_finPinkyB" 1
	 "def_l_finPinkyC" 1
	 "def_l_finRingA" 1
	 "def_l_finRingB" 1
	 "def_l_finRingC" 1
	 "def_l_finMidA" 1
	 "def_l_finMidB" 1
	 "def_l_finMidC" 1
	 "def_l_finIndexA" 1
	 "def_l_finIndexB" 1
	 "def_l_finIndexC" 1
	 "def_l_finThumbA" 1
	 "def_l_finThumbB" 1
	 "def_l_finThumbC" 1
	 "ja_l_propHand" 1
	 "ja_r_propHand" 1
	 "def_c_hatchTop" 1
	 "def_c_hatchBot" 1
	 "def_c_hatchHead" 1
	 "def_c_neck1" 1
	 "def_c_eye_rotate" 1
	 "def_c_eye_detached" 1
	 "def_c_eyeball" 1
	 "def_c_eye_outer" 1
	 "def_c_eyelid" 1
	 "def_l_eyelid" 1
	 "def_r_eyelid" 1
	 "def_l_eye_side" 1
	 "def_r_eye_side" 1
	 "def_l_eye_side_cover" 1
	 "def_r_eye_side_cover" 1
	 "def_l_piston_rear_knee1" 0
	 "def_l_piston_rear_knee2" 0
	 "def_r_piston_rear_knee1" 0
	 "def_r_piston_rear_knee2" 0
	 "def_cam_shoulder" 1
	 "def_l_missile_root" 1
	 "def_l_missile_leg1" 1
	 "def_l_missile_leg2" 1
	 "def_l_missile_leg3" 1
	 "def_l_missile_leg4" 1
	 "def_l_missile_wing_out1" 1
	 "def_l_missile_wing_out2" 1
	 "def_l_missile_wing_out_hook1" 1
	 "def_l_missile_wing_out_hook2" 1
	 "def_l_missile_wing_in1" 1
	 "def_l_missile_wing_in2" 1
	 "def_l_missile_wing_in_hook1" 1
	 "def_l_missile_wing_in_hook2" 1
	 "def_l_missile_box" 1
	 "def_l_holder" 1
	 "def_l_holder_clip1" 1
	 "def_l_holder_clip2" 1
	 "def_r_missile_root" 1
	 "def_r_missile_leg1" 1
	 "def_r_missile_leg2" 1
	 "def_r_missile_leg3" 1
	 "def_r_missile_leg4" 1
	 "def_r_missile_wing_out1" 1
	 "def_r_missile_wing_out2" 1
	 "def_r_missile_wing_out_hook1" 1
	 "def_r_missile_wing_out_hook2" 1
	 "def_r_missile_wing_in1" 1
	 "def_r_missile_wing_in2" 1
	 "def_r_missile_wing_in_hook1" 1
	 "def_r_missile_wing_in_hook2" 1
	 "def_r_missile_box" 1
	 "def_r_holder" 1
	 "def_r_holder_clip1" 1
	 "def_r_holder_clip2" 1
	 "def_r_down_missile_doorA1" 1
	 "def_r_down_missile_doorB1" 1
	 "def_r_down_missile_doorC1" 1
	 "def_r_up_missile_doorA1" 1
	 "def_r_up_missile_doorB1" 1
	 "def_r_up_missile_doorC1" 1
	 "def_l_down_missile_doorC1" 1
	 "def_l_down_missile_doorB1" 1
	 "def_l_down_missile_doorA1" 1
	 "def_l_up_missile_doorC1" 1
	 "def_l_up_missile_doorB1" 1
	 "def_l_up_missile_doorA1" 1
	 "def_l_shock_waist_front_up" 1
	 "def_l_shock_waist_side_up" 1
	 "def_l_shock_waist_back_up" 1
	 "def_r_shock_waist_front_up" 1
	 "def_r_shock_waist_side_up" 1
	 "def_r_shock_waist_back_up" 1
	 "def_l_shock_waist_front_down" 0.1
	 "def_l_shock_waist_side_down" 0.1
	 "def_l_shock_waist_back_down" 0.1
	 "def_r_shock_waist_front_down" 0.1
	 "def_r_shock_waist_side_down" 0.1
	 "def_r_shock_waist_back_down" 0.1
	 "def_l_shock_knee_up" 0
	 "def_l_shock_knee_down" 0
	 "def_r_shock_knee_up" 0
	 "def_r_shock_knee_down" 0
	 "def_l_heel" 0
	 "def_l_heel_shock_start" 0
	 "def_l_heel_shock_end" 0
	 "def_r_heel" 0
	 "def_r_heel_shock_start" 0
	 "def_r_heel_shock_end" 0
	 "jx_l_ankle_hb" 0
	 "jx_r_ankle_hb" 0
	 "jx_c_hatch_1_hb" 1
	 "jx_c_hatch_2_hb" 1
	 "jx_c_hatch_3_hb" 1
	 "jx_c_hatch_4_hb" 1
	 "jx_c_hatch_5_hb" 1
	 "jx_vortex" 1
	 "def_l_battery1" 1
	 "def_l_battery2" 1
	 "def_l_battery3" 1
	 "jx_c_camera_2" 0
	 "jx_c_camera_3" 0
	 "jx_c_origin" 0
}

$weightlist "weights_mp_stand_gesture_reload" {
	 "jx_c_delta" 0
	 "jx_c_start" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "def_c_spineA" 1
	 "def_c_spineB" 1
	 "def_c_spineC" 1
	 "ja_c_propGun" 1
	 "def_c_intBase" 1
	 "def_c_cam" 1
	 "def_c_neckA" 1
	 "jx_c_neckB" 1
	 "def_c_neckB" 1
	 "def_c_head" 1
	 "def_l_clav" 1
	 "def_l_shoulder" 1
	 "def_l_shoulderMid" 1
	 "def_l_elbow" 1
	 "def_l_wrist" 1
	 "def_l_forearm" 1
	 "def_l_elbowB" 1
	 "def_l_shoulderTwist" 1
	 "def_r_clav" 1
	 "def_r_shoulder" 1
	 "def_r_shoulderMid" 1
	 "def_r_elbow" 1
	 "def_r_wrist" 1
	 "def_r_forearm" 1
	 "def_r_elbowB" 1
	 "def_r_shoulderTwist" 1
	 "def_l_hip" 0
	 "def_l_thigh" 0
	 "def_l_thighLow" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_hip" 0
	 "def_r_thigh" 0
	 "def_r_thighLow" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "def_r_finThumbA" 1
	 "def_r_finThumbB" 1
	 "def_r_finThumbC" 1
	 "def_r_finIndexA" 1
	 "def_r_finIndexB" 1
	 "def_r_finIndexC" 1
	 "def_r_finMidA" 1
	 "def_r_finMidB" 1
	 "def_r_finMidC" 1
	 "def_r_finRingCarpal" 1
	 "def_r_finRingA" 1
	 "def_r_finRingB" 1
	 "def_r_finRingC" 1
	 "def_r_finPinkyA" 1
	 "def_r_finPinkyB" 1
	 "def_r_finPinkyC" 1
	 "def_l_finRingCarpal" 1
	 "def_l_finPinkyA" 1
	 "def_l_finPinkyB" 1
	 "def_l_finPinkyC" 1
	 "def_l_finRingA" 1
	 "def_l_finRingB" 1
	 "def_l_finRingC" 1
	 "def_l_finMidA" 1
	 "def_l_finMidB" 1
	 "def_l_finMidC" 1
	 "def_l_finIndexA" 1
	 "def_l_finIndexB" 1
	 "def_l_finIndexC" 1
	 "def_l_finThumbA" 1
	 "def_l_finThumbB" 1
	 "def_l_finThumbC" 1
	 "ja_l_propHand" 1
	 "ja_r_propHand" 1
	 "def_c_hatchTop" 1
	 "def_c_hatchBot" 1
	 "def_c_hatchHead" 1
	 "def_c_neck1" 1
	 "def_c_eye_rotate" 1
	 "def_c_eye_detached" 1
	 "def_c_eyeball" 1
	 "def_c_eye_outer" 1
	 "def_c_eyelid" 1
	 "def_l_eyelid" 1
	 "def_r_eyelid" 1
	 "def_l_eye_side" 1
	 "def_r_eye_side" 1
	 "def_l_eye_side_cover" 1
	 "def_r_eye_side_cover" 1
	 "def_l_piston_rear_knee1" 0
	 "def_l_piston_rear_knee2" 0
	 "def_r_piston_rear_knee1" 0
	 "def_r_piston_rear_knee2" 0
	 "def_cam_shoulder" 1
	 "def_l_missile_root" 1
	 "def_l_missile_leg1" 1
	 "def_l_missile_leg2" 1
	 "def_l_missile_leg3" 1
	 "def_l_missile_leg4" 1
	 "def_l_missile_wing_out1" 1
	 "def_l_missile_wing_out2" 1
	 "def_l_missile_wing_out_hook1" 1
	 "def_l_missile_wing_out_hook2" 1
	 "def_l_missile_wing_in1" 1
	 "def_l_missile_wing_in2" 1
	 "def_l_missile_wing_in_hook1" 1
	 "def_l_missile_wing_in_hook2" 1
	 "def_l_missile_box" 1
	 "def_l_holder" 1
	 "def_l_holder_clip1" 1
	 "def_l_holder_clip2" 1
	 "def_r_missile_root" 1
	 "def_r_missile_leg1" 1
	 "def_r_missile_leg2" 1
	 "def_r_missile_leg3" 1
	 "def_r_missile_leg4" 1
	 "def_r_missile_wing_out1" 1
	 "def_r_missile_wing_out2" 1
	 "def_r_missile_wing_out_hook1" 1
	 "def_r_missile_wing_out_hook2" 1
	 "def_r_missile_wing_in1" 1
	 "def_r_missile_wing_in2" 1
	 "def_r_missile_wing_in_hook1" 1
	 "def_r_missile_wing_in_hook2" 1
	 "def_r_missile_box" 1
	 "def_r_holder" 1
	 "def_r_holder_clip1" 1
	 "def_r_holder_clip2" 1
	 "def_r_down_missile_doorA1" 1
	 "def_r_down_missile_doorB1" 1
	 "def_r_down_missile_doorC1" 1
	 "def_r_up_missile_doorA1" 1
	 "def_r_up_missile_doorB1" 1
	 "def_r_up_missile_doorC1" 1
	 "def_l_down_missile_doorC1" 1
	 "def_l_down_missile_doorB1" 1
	 "def_l_down_missile_doorA1" 1
	 "def_l_up_missile_doorC1" 1
	 "def_l_up_missile_doorB1" 1
	 "def_l_up_missile_doorA1" 1
	 "def_l_shock_waist_front_up" 1
	 "def_l_shock_waist_side_up" 1
	 "def_l_shock_waist_back_up" 1
	 "def_r_shock_waist_front_up" 1
	 "def_r_shock_waist_side_up" 1
	 "def_r_shock_waist_back_up" 1
	 "def_l_shock_waist_front_down" 0
	 "def_l_shock_waist_side_down" 0
	 "def_l_shock_waist_back_down" 0
	 "def_r_shock_waist_front_down" 0
	 "def_r_shock_waist_side_down" 0
	 "def_r_shock_waist_back_down" 0
	 "def_l_shock_knee_up" 0
	 "def_l_shock_knee_down" 0
	 "def_r_shock_knee_up" 0
	 "def_r_shock_knee_down" 0
	 "def_l_heel" 0
	 "def_l_heel_shock_start" 0
	 "def_l_heel_shock_end" 0
	 "def_r_heel" 0
	 "def_r_heel_shock_start" 0
	 "def_r_heel_shock_end" 0
	 "jx_l_ankle_hb" 0
	 "jx_r_ankle_hb" 0
	 "jx_c_hatch_1_hb" 1
	 "jx_c_hatch_2_hb" 1
	 "jx_c_hatch_3_hb" 1
	 "jx_c_hatch_4_hb" 1
	 "jx_c_hatch_5_hb" 1
	 "jx_vortex" 1
	 "def_l_battery1" 1
	 "def_l_battery2" 1
	 "def_l_battery3" 1
	 "jx_c_camera_2" 0
	 "jx_c_camera_3" 0
	 "jx_c_origin" 0
}

$weightlist "weights_mp_stand_gesture_reload_rocket" {
	 "jx_c_delta" 0
	 "jx_c_start" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "def_c_spineA" 0
	 "def_c_spineB" 0
	 "def_c_spineC" 1
	 "ja_c_propGun" 1
	 "def_c_intBase" 1
	 "def_c_cam" 1
	 "def_c_neckA" 1
	 "jx_c_neckB" 1
	 "def_c_neckB" 1
	 "def_c_head" 1
	 "def_l_clav" 1
	 "def_l_shoulder" 1
	 "def_l_shoulderMid" 1
	 "def_l_elbow" 1
	 "def_l_wrist" 1
	 "def_l_forearm" 1
	 "def_l_elbowB" 1
	 "def_l_shoulderTwist" 1
	 "def_r_clav" 1
	 "def_r_shoulder" 1
	 "def_r_shoulderMid" 1
	 "def_r_elbow" 1
	 "def_r_wrist" 1
	 "def_r_forearm" 1
	 "def_r_elbowB" 1
	 "def_r_shoulderTwist" 1
	 "def_l_hip" 0
	 "def_l_thigh" 0
	 "def_l_thighLow" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_hip" 0
	 "def_r_thigh" 0
	 "def_r_thighLow" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "def_r_finThumbA" 1
	 "def_r_finThumbB" 1
	 "def_r_finThumbC" 1
	 "def_r_finIndexA" 1
	 "def_r_finIndexB" 1
	 "def_r_finIndexC" 1
	 "def_r_finMidA" 1
	 "def_r_finMidB" 1
	 "def_r_finMidC" 1
	 "def_r_finRingCarpal" 1
	 "def_r_finRingA" 1
	 "def_r_finRingB" 1
	 "def_r_finRingC" 1
	 "def_r_finPinkyA" 1
	 "def_r_finPinkyB" 1
	 "def_r_finPinkyC" 1
	 "def_l_finRingCarpal" 1
	 "def_l_finPinkyA" 1
	 "def_l_finPinkyB" 1
	 "def_l_finPinkyC" 1
	 "def_l_finRingA" 1
	 "def_l_finRingB" 1
	 "def_l_finRingC" 1
	 "def_l_finMidA" 1
	 "def_l_finMidB" 1
	 "def_l_finMidC" 1
	 "def_l_finIndexA" 1
	 "def_l_finIndexB" 1
	 "def_l_finIndexC" 1
	 "def_l_finThumbA" 1
	 "def_l_finThumbB" 1
	 "def_l_finThumbC" 1
	 "ja_l_propHand" 1
	 "ja_r_propHand" 1
	 "def_c_hatchTop" 1
	 "def_c_hatchBot" 1
	 "def_c_hatchHead" 1
	 "def_c_neck1" 1
	 "def_c_eye_rotate" 1
	 "def_c_eye_detached" 1
	 "def_c_eyeball" 1
	 "def_c_eye_outer" 1
	 "def_c_eyelid" 1
	 "def_l_eyelid" 1
	 "def_r_eyelid" 1
	 "def_l_eye_side" 1
	 "def_r_eye_side" 1
	 "def_l_eye_side_cover" 1
	 "def_r_eye_side_cover" 1
	 "def_l_piston_rear_knee1" 0
	 "def_l_piston_rear_knee2" 0
	 "def_r_piston_rear_knee1" 0
	 "def_r_piston_rear_knee2" 0
	 "def_cam_shoulder" 1
	 "def_l_missile_root" 1
	 "def_l_missile_leg1" 1
	 "def_l_missile_leg2" 1
	 "def_l_missile_leg3" 1
	 "def_l_missile_leg4" 1
	 "def_l_missile_wing_out1" 1
	 "def_l_missile_wing_out2" 1
	 "def_l_missile_wing_out_hook1" 1
	 "def_l_missile_wing_out_hook2" 1
	 "def_l_missile_wing_in1" 1
	 "def_l_missile_wing_in2" 1
	 "def_l_missile_wing_in_hook1" 1
	 "def_l_missile_wing_in_hook2" 1
	 "def_l_missile_box" 1
	 "def_l_holder" 1
	 "def_l_holder_clip1" 1
	 "def_l_holder_clip2" 1
	 "def_r_missile_root" 1
	 "def_r_missile_leg1" 1
	 "def_r_missile_leg2" 1
	 "def_r_missile_leg3" 1
	 "def_r_missile_leg4" 1
	 "def_r_missile_wing_out1" 1
	 "def_r_missile_wing_out2" 1
	 "def_r_missile_wing_out_hook1" 1
	 "def_r_missile_wing_out_hook2" 1
	 "def_r_missile_wing_in1" 1
	 "def_r_missile_wing_in2" 1
	 "def_r_missile_wing_in_hook1" 1
	 "def_r_missile_wing_in_hook2" 1
	 "def_r_missile_box" 1
	 "def_r_holder" 1
	 "def_r_holder_clip1" 1
	 "def_r_holder_clip2" 1
	 "def_r_down_missile_doorA1" 1
	 "def_r_down_missile_doorB1" 1
	 "def_r_down_missile_doorC1" 1
	 "def_r_up_missile_doorA1" 1
	 "def_r_up_missile_doorB1" 1
	 "def_r_up_missile_doorC1" 1
	 "def_l_down_missile_doorC1" 1
	 "def_l_down_missile_doorB1" 1
	 "def_l_down_missile_doorA1" 1
	 "def_l_up_missile_doorC1" 1
	 "def_l_up_missile_doorB1" 1
	 "def_l_up_missile_doorA1" 1
	 "def_l_shock_waist_front_up" 1
	 "def_l_shock_waist_side_up" 1
	 "def_l_shock_waist_back_up" 1
	 "def_r_shock_waist_front_up" 1
	 "def_r_shock_waist_side_up" 1
	 "def_r_shock_waist_back_up" 1
	 "def_l_shock_waist_front_down" 0
	 "def_l_shock_waist_side_down" 0
	 "def_l_shock_waist_back_down" 0
	 "def_r_shock_waist_front_down" 0
	 "def_r_shock_waist_side_down" 0
	 "def_r_shock_waist_back_down" 0
	 "def_l_shock_knee_up" 0
	 "def_l_shock_knee_down" 0
	 "def_r_shock_knee_up" 0
	 "def_r_shock_knee_down" 0
	 "def_l_heel" 0
	 "def_l_heel_shock_start" 0
	 "def_l_heel_shock_end" 0
	 "def_r_heel" 0
	 "def_r_heel_shock_start" 0
	 "def_r_heel_shock_end" 0
	 "jx_l_ankle_hb" 0
	 "jx_r_ankle_hb" 0
	 "jx_c_hatch_1_hb" 1
	 "jx_c_hatch_2_hb" 1
	 "jx_c_hatch_3_hb" 1
	 "jx_c_hatch_4_hb" 1
	 "jx_c_hatch_5_hb" 1
	 "jx_vortex" 1
	 "def_l_battery1" 1
	 "def_l_battery2" 1
	 "def_l_battery3" 1
	 "jx_c_camera_2" 0
	 "jx_c_camera_3" 0
	 "jx_c_origin" 0
}

$animation "a_aim_combat_walk_neutral_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_neutral_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_down_left_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_down_left_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_down_center_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_down_center_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_down_right_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_down_right_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_mid_left_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_mid_left_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_mid_center_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_mid_center_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_mid_right_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_mid_right_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_up_left_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_up_left_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_up_center_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_up_center_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_up_right_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_up_right_MP.smd" {
	fps 30
}

$animation "a_aim_combat_walk_straightup_MP" "titan_buddy_mp_core_anims\a_aim_combat_walk_straightup_MP.smd" {
	fps 30
}

$animation "a_aim_stand_neutral_MP" "titan_buddy_mp_core_anims\a_aim_stand_neutral_MP.smd" {
	fps 30
}

$animation "a_aim_stand_down_left_MP" "titan_buddy_mp_core_anims\a_aim_stand_down_left_MP.smd" {
	fps 30
}

$animation "a_aim_stand_down_center_MP" "titan_buddy_mp_core_anims\a_aim_stand_down_center_MP.smd" {
	fps 30
}

$animation "a_aim_stand_down_right_MP" "titan_buddy_mp_core_anims\a_aim_stand_down_right_MP.smd" {
	fps 30
}

$animation "a_aim_stand_mid_left_MP" "titan_buddy_mp_core_anims\a_aim_stand_mid_left_MP.smd" {
	fps 30
}

$animation "a_aim_stand_mid_center_MP" "titan_buddy_mp_core_anims\a_aim_stand_mid_center_MP.smd" {
	fps 30
}

$animation "a_aim_stand_mid_right_MP" "titan_buddy_mp_core_anims\a_aim_stand_mid_right_MP.smd" {
	fps 30
}

$animation "a_aim_stand_up_left_MP" "titan_buddy_mp_core_anims\a_aim_stand_up_left_MP.smd" {
	fps 30
}

$animation "a_aim_stand_up_center_MP" "titan_buddy_mp_core_anims\a_aim_stand_up_center_MP.smd" {
	fps 30
}

$animation "a_aim_stand_up_right_MP" "titan_buddy_mp_core_anims\a_aim_stand_up_right_MP.smd" {
	fps 30
}

$animation "a_aim_stand_straightup_MP" "titan_buddy_mp_core_anims\a_aim_stand_straightup_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_neutral_MP" "titan_buddy_mp_core_anims\a_ADS_stand_neutral_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_down_left_MP" "titan_buddy_mp_core_anims\a_ADS_stand_down_left_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_down_center_MP" "titan_buddy_mp_core_anims\a_ADS_stand_down_center_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_down_right_MP" "titan_buddy_mp_core_anims\a_ADS_stand_down_right_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_mid_left_MP" "titan_buddy_mp_core_anims\a_ADS_stand_mid_left_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_mid_center_MP" "titan_buddy_mp_core_anims\a_ADS_stand_mid_center_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_mid_right_MP" "titan_buddy_mp_core_anims\a_ADS_stand_mid_right_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_up_left_MP" "titan_buddy_mp_core_anims\a_ADS_stand_up_left_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_up_center_MP" "titan_buddy_mp_core_anims\a_ADS_stand_up_center_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_up_right_MP" "titan_buddy_mp_core_anims\a_ADS_stand_up_right_MP.smd" {
	fps 30
}

$animation "a_ADS_stand_straightup_MP" "titan_buddy_mp_core_anims\a_ADS_stand_straightup_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_neutral_MP" "titan_buddy_mp_core_anims\a_aim_crouch_neutral_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_down_left_MP" "titan_buddy_mp_core_anims\a_aim_crouch_down_left_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_down_center_MP" "titan_buddy_mp_core_anims\a_aim_crouch_down_center_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_down_right_MP" "titan_buddy_mp_core_anims\a_aim_crouch_down_right_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_left_MP" "titan_buddy_mp_core_anims\a_aim_crouch_mid_left_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_center_MP" "titan_buddy_mp_core_anims\a_aim_crouch_mid_center_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_right_MP" "titan_buddy_mp_core_anims\a_aim_crouch_mid_right_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_up_left_MP" "titan_buddy_mp_core_anims\a_aim_crouch_up_left_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_up_center_MP" "titan_buddy_mp_core_anims\a_aim_crouch_up_center_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_up_right_MP" "titan_buddy_mp_core_anims\a_aim_crouch_up_right_MP.smd" {
	fps 30
}

$animation "a_aim_crouch_straightup_MP" "titan_buddy_mp_core_anims\a_aim_crouch_straightup_MP.smd" {
	fps 30
}

$animation "a_MP_CQB_idle" "titan_buddy_mp_core_anims\a_MP_CQB_idle.smd" {
	fps 30
	loop
}

$animation "a_MP_CQB_ADS_idle" "titan_buddy_mp_core_anims\a_MP_CQB_ADS_idle.smd" {
	fps 30
	loop
}

$animation "a_MP_crouch_IDLE" "titan_buddy_mp_core_anims\a_MP_crouch_IDLE.smd" {
	fps 30
	loop
}

$animation "a_MP_stand_shoot" "titan_buddy_mp_core_anims\a_MP_stand_shoot.smd" {
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$animation "a_MP_ADS_stand_shoot" "titan_buddy_mp_core_anims\a_MP_ADS_stand_shoot.smd" {
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$animation "a_MP_stand_shootB" "titan_buddy_mp_core_anims\a_MP_stand_shootB.smd" {
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$animation "a_MP_crouch_shoot" "titan_buddy_mp_core_anims\a_MP_crouch_shoot.smd" {
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$animation "a_MP_crouch_shootB" "titan_buddy_mp_core_anims\a_MP_crouch_shootB.smd" {
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$animation "a_ReloadGesture" "titan_buddy_mp_core_anims\a_ReloadGesture.smd" {
	fps 30
}

$animation "a_stand_gesture_reload" "titan_buddy_mp_core_anims\a_stand_gesture_reload.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$animation "a_MP_crouch_reload" "titan_buddy_mp_core_anims\a_MP_crouch_reload.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$animation "a_gesture_reload_rocket" "titan_buddy_mp_core_anims\a_gesture_reload_rocket.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$animation "a_gesture_reload_40mm" "titan_buddy_mp_core_anims\a_gesture_reload_40mm.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$animation "a_gesture_reload_xo16" "titan_buddy_mp_core_anims\a_gesture_reload_xo16.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$animation "a_gesture_reload_triple_threat" "titan_buddy_mp_core_anims\a_gesture_reload_triple_threat.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$animation "a_gesture_reload_shotgun" "titan_buddy_mp_core_anims\a_gesture_reload_shotgun.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$animation "a_WalkForward" "titan_buddy_mp_core_anims\a_WalkForward.smd" {
	fps 30
	loop
}

$animation "a_WalkForward_L" "titan_buddy_mp_core_anims\a_WalkForward_L.smd" {
	fps 30
	loop
}

$animation "a_WalkForward_R" "titan_buddy_mp_core_anims\a_WalkForward_R.smd" {
	fps 30
	loop
}

$animation "a_combat_WalkBackward" "titan_buddy_mp_core_anims\a_combat_WalkBackward.smd" {
	fps 30
	loop
}

$animation "a_combat_WalkBackward_L" "titan_buddy_mp_core_anims\a_combat_WalkBackward_L.smd" {
	fps 30
	loop
}

$animation "a_combat_WalkBackward_R" "titan_buddy_mp_core_anims\a_combat_WalkBackward_R.smd" {
	fps 30
	loop
}

$animation "a_RunForward" "titan_buddy_mp_core_anims\a_RunForward.smd" {
	fps 30
	loop
}

$animation "a_RunForward_L" "titan_buddy_mp_core_anims\a_RunForward_L.smd" {
	fps 30
	loop
}

$animation "a_RunForward_R" "titan_buddy_mp_core_anims\a_RunForward_R.smd" {
	fps 30
	loop
}

$animation "a_combat_runBackward" "titan_buddy_mp_core_anims\a_combat_runBackward.smd" {
	fps 30
	loop
}

$animation "a_combat_runBackward_L" "titan_buddy_mp_core_anims\a_combat_runBackward_L.smd" {
	fps 30
	loop
}

$animation "a_combat_runBackward_R" "titan_buddy_mp_core_anims\a_combat_runBackward_R.smd" {
	fps 30
	loop
}

$animation "a_combat_sprint_Lean_L" "titan_buddy_mp_core_anims\a_combat_sprint_Lean_L.smd" {
	fps 30
	loop
}

$animation "a_combat_sprint_Lean_R" "titan_buddy_mp_core_anims\a_combat_sprint_Lean_R.smd" {
	fps 30
}

$animation "a_combat_sprint" "titan_buddy_mp_core_anims\a_combat_sprint.smd" {
	fps 30
}

$animation "Slide_forward" "titan_buddy_mp_core_anims\Slide_forward.smd" {
	fps 30
}

$animation "Slide_forward_L" "titan_buddy_mp_core_anims\Slide_forward_L.smd" {
	fps 30
}

$animation "Slide_forward_R" "titan_buddy_mp_core_anims\Slide_forward_R.smd" {
	fps 30
	loop
}

$animation "Slide_Backward" "titan_buddy_mp_core_anims\Slide_Backward.smd" {
	fps 30
}

$animation "Slide_Backward_L" "titan_buddy_mp_core_anims\Slide_Backward_L.smd" {
	fps 30
	loop
}

$animation "Slide_Backward_R" "titan_buddy_mp_core_anims\Slide_Backward_R.smd" {
	fps 30
}

$animation "a_Crouch_WalkForward" "titan_buddy_mp_core_anims\a_Crouch_WalkForward.smd" {
	fps 30
	loop
}

$animation "a_Crouch_WalkForward_L" "titan_buddy_mp_core_anims\a_Crouch_WalkForward_L.smd" {
	fps 30
	loop
}

$animation "a_Crouch_WalkForward_R" "titan_buddy_mp_core_anims\a_Crouch_WalkForward_R.smd" {
	fps 30
	loop
}

$animation "a_Crouch_WalkBackward" "titan_buddy_mp_core_anims\a_Crouch_WalkBackward.smd" {
	fps 30
	loop
}

$animation "a_Crouch_WalkBackward_L" "titan_buddy_mp_core_anims\a_Crouch_WalkBackward_L.smd" {
	fps 30
	loop
}

$animation "a_Crouch_WalkBackward_R" "titan_buddy_mp_core_anims\a_Crouch_WalkBackward_R.smd" {
	fps 30
	loop
}

$animation "at_Dodge_Start" "titan_buddy_mp_core_anims\at_Dodge_Start.smd" {
	fps 30
}

$animation "at_Dodge_Start_L" "titan_buddy_mp_core_anims\at_Dodge_Start_L.smd" {
	fps 30
}

$animation "at_Dodge_Start_R" "titan_buddy_mp_core_anims\at_Dodge_Start_R.smd" {
	fps 30
}

$animation "at_Dodge_Float" "titan_buddy_mp_core_anims\at_Dodge_Float.smd" {
	fps 30
}

$animation "at_Dodge_Float_L" "titan_buddy_mp_core_anims\at_Dodge_Float_L.smd" {
	fps 30
}

$animation "at_Dodge_Float_R" "titan_buddy_mp_core_anims\at_Dodge_Float_R.smd" {
	fps 30
	loop
}

$animation "at_Dodge_Land" "titan_buddy_mp_core_anims\at_Dodge_Land.smd" {
	fps 30
}

$animation "at_Dodge_Land_L" "titan_buddy_mp_core_anims\at_Dodge_Land_L.smd" {
	fps 30
}

$animation "at_Dodge_Land_R" "titan_buddy_mp_core_anims\at_Dodge_Land_R.smd" {
	fps 30
}

$animation "at_DodgeBackward_Start" "titan_buddy_mp_core_anims\at_DodgeBackward_Start.smd" {
	fps 30
}

$animation "at_DodgeBackward_Start_L" "titan_buddy_mp_core_anims\at_DodgeBackward_Start_L.smd" {
	fps 30
}

$animation "at_DodgeBackward_Start_R" "titan_buddy_mp_core_anims\at_DodgeBackward_Start_R.smd" {
	fps 30
}

$animation "at_DodgeBackward_Float" "titan_buddy_mp_core_anims\at_DodgeBackward_Float.smd" {
	fps 30
}

$animation "at_DodgeBackward_Float_L" "titan_buddy_mp_core_anims\at_DodgeBackward_Float_L.smd" {
	fps 30
	loop
}

$animation "at_DodgeBackward_Float_R" "titan_buddy_mp_core_anims\at_DodgeBackward_Float_R.smd" {
	fps 30
}

$animation "at_DodgeBackward_Land" "titan_buddy_mp_core_anims\at_DodgeBackward_Land.smd" {
	fps 30
}

$animation "at_DodgeBackward_Land_L" "titan_buddy_mp_core_anims\at_DodgeBackward_Land_L.smd" {
	fps 30
}

$animation "at_DodgeBackward_Land_R" "titan_buddy_mp_core_anims\at_DodgeBackward_Land_R.smd" {
	fps 30
}

$animation "a_MP_Jump_start" "titan_buddy_mp_core_anims\a_MP_Jump_start.smd" {
	fps 30
}

$animation "a_MP_Jump_float" "titan_buddy_mp_core_anims\a_MP_Jump_float.smd" {
	fps 30
	loop
}

$animation "a_MP_Jump_end" "titan_buddy_mp_core_anims\a_MP_Jump_end.smd" {
	fps 30
}

$animation "a_MP_rodeo_walk" "titan_buddy_mp_core_anims\a_MP_rodeo_walk.smd" {
	fps 30
	loop
}

$animation "a_MP_rodeo_crouchwalk" "titan_buddy_mp_core_anims\a_MP_rodeo_crouchwalk.smd" {
	fps 30
	loop
}

$animation "a_PiggyBack" "titan_buddy_mp_core_anims\a_PiggyBack.smd" {
	fps 30
	loop
}

$animation "a_Death_stumbleback" "titan_buddy_mp_core_anims\a_Death_stumbleback.smd" {
	fps 30
}

$animation "a_Death_twist" "titan_buddy_mp_core_anims\a_Death_twist.smd" {
	fps 30
}

$animation "a_Death_twist_L" "titan_buddy_mp_core_anims\a_Death_twist_L.smd" {
	fps 30
}

$animation "a_Death_fallforward" "titan_buddy_mp_core_anims\a_Death_fallforward.smd" {
	fps 30
}

$animation "a_death_damaged" "titan_buddy_mp_core_anims\a_death_damaged.smd" {
	fps 30
}

$animation "a_death_knockback" "titan_buddy_mp_core_anims\a_death_knockback.smd" {
	fps 30
}

$animation "a_death_slowfall_back" "titan_buddy_mp_core_anims\a_death_slowfall_back.smd" {
	fps 30
}

$animation "a_death_twitch" "titan_buddy_mp_core_anims\a_death_twitch.smd" {
	fps 30
}

$animation "a_death_sprint_crash" "titan_buddy_mp_core_anims\a_death_sprint_crash.smd" {
	fps 30
}

$animation "a_death_sprint_F_stumble" "titan_buddy_mp_core_anims\a_death_sprint_F_stumble.smd" {
	fps 30
}

$animation "a_death_Sprint_F_slam" "titan_buddy_mp_core_anims\a_death_Sprint_F_slam.smd" {
	fps 30
}

$animation "sp_Flinch" "titan_buddy_mp_core_anims\sp_Flinch.smd" {
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$animation "a_MP_pain_F_twitch" "titan_buddy_mp_core_anims\a_MP_pain_F_twitch.smd" {
	fps 30
}

$animation "a_MP_pain_L_shoulder" "titan_buddy_mp_core_anims\a_MP_pain_L_shoulder.smd" {
	fps 30
}

$animation "a_MP_pain_L_shoulder_long" "titan_buddy_mp_core_anims\a_MP_pain_L_shoulder_long.smd" {
	fps 30
}

$animation "a_MP_pain_F_short" "titan_buddy_mp_core_anims\a_MP_pain_F_short.smd" {
	fps 30
}

$animation "a_MP_pain_R_twitch" "titan_buddy_mp_core_anims\a_MP_pain_R_twitch.smd" {
	fps 30
}

$animation "a_aim_doomed_neutral_MP" "titan_buddy_mp_core_anims\a_aim_doomed_neutral_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_down_left_MP" "titan_buddy_mp_core_anims\a_aim_doomed_down_left_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_down_center_MP" "titan_buddy_mp_core_anims\a_aim_doomed_down_center_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_down_right_MP" "titan_buddy_mp_core_anims\a_aim_doomed_down_right_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_mid_left_MP" "titan_buddy_mp_core_anims\a_aim_doomed_mid_left_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_mid_center_MP" "titan_buddy_mp_core_anims\a_aim_doomed_mid_center_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_mid_right_MP" "titan_buddy_mp_core_anims\a_aim_doomed_mid_right_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_up_left_MP" "titan_buddy_mp_core_anims\a_aim_doomed_up_left_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_up_center_MP" "titan_buddy_mp_core_anims\a_aim_doomed_up_center_MP.smd" {
	fps 30
}

$animation "a_aim_doomed_up_right_MP" "titan_buddy_mp_core_anims\a_aim_doomed_up_right_MP.smd" {
	fps 30
}

$sequence "ref" {
	"titan_buddy_mp_core_anims\ref.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ref_reactions" {
	"titan_buddy_mp_core_anims\ref_reactions.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Aim_combat_walk_MP" {
	"a_aim_combat_walk_up_left_MP"
	"a_aim_combat_walk_up_center_MP"
	"a_aim_combat_walk_up_right_MP"
	"a_aim_combat_walk_mid_left_MP"
	"a_aim_combat_walk_mid_center_MP"
	"a_aim_combat_walk_mid_right_MP"
	"a_aim_combat_walk_down_left_MP"
	"a_aim_combat_walk_down_center_MP"
	"a_aim_combat_walk_down_right_MP"
}

$sequence "MP_stand_Aim_all" {
	"a_aim_stand_up_left_MP"
	"a_aim_stand_up_center_MP"
	"a_aim_stand_up_right_MP"
	"a_aim_stand_mid_left_MP"
	"a_aim_stand_mid_center_MP"
	"a_aim_stand_mid_right_MP"
	"a_aim_stand_down_left_MP"
	"a_aim_stand_down_center_MP"
	"a_aim_stand_down_right_MP"
}

$sequence "MP_ADS_stand_Aim_all" {
	"a_ADS_stand_up_left_MP"
	"a_ADS_stand_up_center_MP"
	"a_ADS_stand_up_right_MP"
	"a_ADS_stand_mid_left_MP"
	"a_ADS_stand_mid_center_MP"
	"a_ADS_stand_mid_right_MP"
	"a_ADS_stand_down_left_MP"
	"a_ADS_stand_down_center_MP"
	"a_ADS_stand_down_right_MP"
}

$sequence "MP_crouch_Aim_all" {
	"a_aim_crouch_up_left_MP"
	"a_aim_crouch_up_center_MP"
	"a_aim_crouch_up_right_MP"
	"a_aim_crouch_mid_left_MP"
	"a_aim_crouch_mid_center_MP"
	"a_aim_crouch_mid_right_MP"
	"a_aim_crouch_down_left_MP"
	"a_aim_crouch_down_center_MP"
	"a_aim_crouch_down_right_MP"
}

$sequence "CQB_Idle_MP" {
	"a_MP_CQB_idle"
	activity "ACT_MP_STAND_IDLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	addlayer "MP_stand_Aim_all"
	fps 30
	loop
}

$sequence "CQB_ADS_Idle_MP" {
	"a_MP_CQB_ADS_idle"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier ads
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	addlayer "MP_ADS_stand_Aim_all"
	fps 30
	loop
}

$sequence "CQB_CrouchIdle_MP" {
	"a_MP_crouch_IDLE"
	activity "ACT_MP_CROUCH_IDLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	addlayer "MP_crouch_Aim_all"
	fps 30
	loop
}

$sequence "mp_stand_shootGeneric_add" {
	"a_MP_stand_shoot"
	activity "ACT_MP_ATTACK_STAND_PRIMARYFIRE" 3
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$sequence "mp_stand_shootGeneric_add2" {
	"a_MP_stand_shootB"
	activity "ACT_MP_ATTACK_STAND_PRIMARYFIRE" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$sequence "mp_ADS_stand_shootGeneric_add" {
	"a_MP_ADS_stand_shoot"
	activity "ACT_MP_ATTACK_STAND_PRIMARYFIRE" 1
	activitymodifier ads
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$sequence "mp_crouch_shootGeneric_add" {
	"a_MP_crouch_shoot"
	activity "ACT_MP_ATTACK_CROUCH_PRIMARYFIRE" 3
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$sequence "mp_crouch_shootGeneric_add2" {
	"a_MP_crouch_shootB"
	activity "ACT_MP_ATTACK_CROUCH_PRIMARYFIRE" 2
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_shootGeneric_add"
}

$sequence "mp_stand_gesture_reload" {
	"a_stand_gesture_reload"
	activity "ACT_MP_RELOAD_STAND" -1
	delta
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 0 "Titan_3P_Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "mp_crouch_gesture_reload" {
	"a_MP_crouch_reload"
	activity "ACT_MP_RELOAD_CROUCH" -1
	delta
	{ event AE_CL_PLAYSOUND 0 "Titan_3P_Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "mp_stand_gesture_reload_rocket" {
	"a_gesture_reload_rocket"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_rocketeer_rocketstream
	{ event AE_CL_PLAYSOUND 0 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 48 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 89 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 106 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 139 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt6" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_rocket" {
	"a_gesture_reload_rocket"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_rocketeer_rocketstream
	{ event AE_CL_PLAYSOUND 0 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 15 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 48 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 89 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 106 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 139 "Wpn_Titan_Rocket_Launcher_3P_Reload_Pt6" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_stand_gesture_40mm" {
	"a_gesture_reload_40mm"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_40mm
	{ event AE_CL_PLAYSOUND 0 "Wpn_40mm_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 8 "Wpn_40mm_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_40mm_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 49 "Wpn_40mm_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 61 "Wpn_40mm_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 67 "Wpn_40mm_3P_Reload_Pt6" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_40mm" {
	"a_gesture_reload_40mm"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_40mm
	{ event AE_CL_PLAYSOUND 0 "Wpn_40mm_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 8 "Wpn_40mm_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_40mm_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 49 "Wpn_40mm_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 61 "Wpn_40mm_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 67 "Wpn_40mm_3P_Reload_Pt6" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_stand_gesture_xo16" {
	"a_gesture_reload_xo16"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_xo16_shorty
	{ event AE_CL_PLAYSOUND 0 "Wpn_XO16_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 11 "Wpn_XO16_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_XO16_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 43 "Wpn_XO16_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 64 "Wpn_XO16_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 73 "Wpn_XO16_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 98 "Wpn_XO16_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 117 "Wpn_XO16_3P_Reload_Pt8" }
	{ event AE_CL_PLAYSOUND 124 "Wpn_XO16_3P_Reload_Pt9" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_xo16" {
	"a_gesture_reload_xo16"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_xo16_shorty
	{ event AE_CL_PLAYSOUND 0 "Wpn_XO16_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 11 "Wpn_XO16_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_XO16_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 43 "Wpn_XO16_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 64 "Wpn_XO16_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 73 "Wpn_XO16_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 98 "Wpn_XO16_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 117 "Wpn_XO16_3P_Reload_Pt8" }
	{ event AE_CL_PLAYSOUND 124 "Wpn_XO16_3P_Reload_Pt9" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_stand_gesture_xo16_vanguard" {
	"a_gesture_reload_xo16"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_xo16_vanguard
	{ event AE_CL_PLAYSOUND 0 "Wpn_XO16_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 11 "Wpn_XO16_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_XO16_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 43 "Wpn_XO16_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 64 "Wpn_XO16_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 73 "Wpn_XO16_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 98 "Wpn_XO16_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 117 "Wpn_XO16_3P_Reload_Pt8" }
	{ event AE_CL_PLAYSOUND 124 "Wpn_XO16_3P_Reload_Pt9" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_xo16_vanguard" {
	"a_gesture_reload_xo16"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_xo16_vanguard
	{ event AE_CL_PLAYSOUND 0 "Wpn_XO16_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 11 "Wpn_XO16_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 21 "Wpn_XO16_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 43 "Wpn_XO16_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 64 "Wpn_XO16_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 73 "Wpn_XO16_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 98 "Wpn_XO16_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 117 "Wpn_XO16_3P_Reload_Pt8" }
	{ event AE_CL_PLAYSOUND 124 "Wpn_XO16_3P_Reload_Pt9" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_stand_gesture_triple_threat" {
	"a_gesture_reload_triple_threat"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_triple_threat
	{ event AE_CL_PLAYSOUND 0 "Wpn_TripleThreat_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 4 "Wpn_TripleThreat_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 9 "Wpn_TripleThreat_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 20 "Wpn_TripleThreat_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 34 "Wpn_TripleThreat_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 41 "Wpn_TripleThreat_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 49 "Wpn_TripleThreat_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 70 "Wpn_TripleThreat_3P_Reload_Pt8" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_triple_threat" {
	"a_gesture_reload_triple_threat"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_triple_threat
	{ event AE_CL_PLAYSOUND 0 "Wpn_TripleThreat_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 4 "Wpn_TripleThreat_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 9 "Wpn_TripleThreat_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 20 "Wpn_TripleThreat_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 34 "Wpn_TripleThreat_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 41 "Wpn_TripleThreat_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 49 "Wpn_TripleThreat_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 70 "Wpn_TripleThreat_3P_Reload_Pt8" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_stand_gesture_shotgun" {
	"a_gesture_reload_shotgun"
	activity "ACT_MP_RELOAD_STAND" -1
	activitymodifier mp_titanweapon_sniper
	{ event AE_CL_PLAYSOUND 0 "Wpn_Titan_Sniper_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 3 "Wpn_Titan_Sniper_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 12 "Wpn_Titan_Sniper_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 19 "Wpn_Titan_Sniper_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 29 "Wpn_Titan_Sniper_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 37 "Wpn_Titan_Sniper_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 42 "Wpn_Titan_Sniper_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 58 "Wpn_Titan_Sniper_3P_Reload_Pt8" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "mp_crouch_gesture_reload_shotgun" {
	"a_gesture_reload_shotgun"
	activity "ACT_MP_RELOAD_CROUCH" -1
	activitymodifier mp_titanweapon_sniper
	{ event AE_CL_PLAYSOUND 0 "Wpn_Titan_Sniper_3P_Reload_Pt1" }
	{ event AE_CL_PLAYSOUND 3 "Wpn_Titan_Sniper_3P_Reload_Pt2" }
	{ event AE_CL_PLAYSOUND 12 "Wpn_Titan_Sniper_3P_Reload_Pt3" }
	{ event AE_CL_PLAYSOUND 19 "Wpn_Titan_Sniper_3P_Reload_Pt4" }
	{ event AE_CL_PLAYSOUND 29 "Wpn_Titan_Sniper_3P_Reload_Pt5" }
	{ event AE_CL_PLAYSOUND 37 "Wpn_Titan_Sniper_3P_Reload_Pt6" }
	{ event AE_CL_PLAYSOUND 42 "Wpn_Titan_Sniper_3P_Reload_Pt7" }
	{ event AE_CL_PLAYSOUND 58 "Wpn_Titan_Sniper_3P_Reload_Pt8" }
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload_rocket"
}

$sequence "Walk_forward_MP" {
	"a_WalkForward_R"
	"a_WalkForward"
	"a_WalkForward_L"
	activity "ACT_MP_WALK_FORWARD" 1
}

$sequence "Walk_backward_MP" {
	"a_combat_WalkBackward_L"
	"a_combat_WalkBackward"
	"a_combat_WalkBackward_R"
	activity "ACT_MP_WALK_BACKWARD" 1
}

$sequence "Run_forward_MP" {
	"a_RunForward_R"
	"a_RunForward"
	"a_RunForward_L"
	activity "ACT_MP_RUN_FORWARD" 1
}

$sequence "Run_backward_MP" {
	"a_combat_runBackward_L"
	"a_combat_runBackward"
	"a_combat_runBackward_R"
	activity "ACT_MP_RUN_BACKWARD" 1
}

$sequence "Sprint_mp_forward" {
	"a_combat_sprint_Lean_L"
	"a_combat_sprint"
	"a_combat_sprint_Lean_R"
	activity "ACT_MP_SPRINT" 1
}

$sequence "Slide_mp_forward" {
	"Slide_forward_R"
	"Slide_forward"
	"Slide_forward_L"
	activity "ACT_MP_SLIDE_FORWARD" 1
}

$sequence "Slide_mp_backward" {
	"Slide_Backward_L"
	"Slide_Backward"
	"Slide_Backward_R"
	activity "ACT_MP_SLIDE_BACKWARD" 1
}

$sequence "Walk_Crouch_forward_MP" {
	"a_Crouch_WalkForward_R"
	"a_Crouch_WalkForward"
	"a_Crouch_WalkForward_L"
	activity "ACT_MP_CROUCHWALK_FORWARD" 1
}

$sequence "Walk_Crouch_backward_MP" {
	"a_Crouch_WalkBackward_L"
	"a_Crouch_WalkBackward"
	"a_Crouch_WalkBackward_R"
	activity "ACT_MP_CROUCHWALK_BACKWARD" 1
}

$sequence "at_MP_dodge_Start" {
	"at_Dodge_Start_R"
	"at_Dodge_Start"
	"at_Dodge_Start_L"
	activity "ACT_MP_DODGE_FORWARD" 1
}

$sequence "at_MP_dodge_float" {
	"at_Dodge_Float_R"
	"at_Dodge_Float"
	"at_Dodge_Float_L"
	activity "ACT_MP_DODGE_FLOAT_FORWARD" 1
}

$sequence "at_MP_dodge_land" {
	"at_Dodge_Land_R"
	"at_Dodge_Land"
	"at_Dodge_Land_L"
	activity "ACT_MP_DODGE_LAND_FORWARD" 1
}

$sequence "at_MP_dodgeBackward_Start" {
	"at_DodgeBackward_Start_L"
	"at_DodgeBackward_Start"
	"at_DodgeBackward_Start_R"
	activity "ACT_MP_DODGE_BACKWARD" 1
}

$sequence "at_MP_dodgeBackward_float" {
	"at_DodgeBackward_Float_L"
	"at_DodgeBackward_Float"
	"at_DodgeBackward_Float_R"
	activity "ACT_MP_DODGE_FLOAT_BACKWARD" 1
}

$sequence "at_MP_dodgeBackward_land" {
	"at_DodgeBackward_Land_L"
	"at_DodgeBackward_Land"
	"at_DodgeBackward_Land_R"
	activity "ACT_MP_DODGE_LAND_BACKWARD" 1
}

$sequence "dodge_start_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_DODGE" 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "dodge_float_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_DODGE_FLOAT" 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "dodge_end_MP" {
	"a_MP_Jump_end"
	activity "ACT_MP_DODGE_LAND" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_start_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_JUMP_START" 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_float_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_JUMP_FLOAT" 1
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Jump_end_MP" {
	"a_MP_Jump_end"
	activity "ACT_MP_JUMP_LAND" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_start_F_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_JUMP_START" 1
	activitymodifier movingforward
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_float_F_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_JUMP_FLOAT" 1
	activitymodifier movingforward
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Jump_end_F_MP" {
	"titan_buddy_mp_core_anims\Jump_end_F_MP.smd"
	activity "ACT_MP_JUMP_LAND_FORWARD" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_start_B_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_JUMP_START" 1
	activitymodifier movingbackward
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_float_B_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_JUMP_FLOAT" 1
	activitymodifier movingbackward
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Jump_end_B_MP" {
	"titan_buddy_mp_core_anims\Jump_end_B_MP.smd"
	activity "ACT_MP_JUMP_LAND_BACKWARD" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_start_R_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_JUMP_START" 1
	activitymodifier movingright
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_float_R_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_JUMP_FLOAT" 1
	activitymodifier movingright
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Jump_end_R_MP" {
	"titan_buddy_mp_core_anims\Jump_end_R_MP.smd"
	activity "ACT_MP_JUMP_LAND_RIGHT" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_start_L_MP" {
	"a_MP_Jump_start"
	activity "ACT_MP_JUMP_START" 1
	activitymodifier movingleft
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 25 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Jump_float_L_MP" {
	"a_MP_Jump_float"
	activity "ACT_MP_JUMP_FLOAT" 1
	activitymodifier movingleft
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 2 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Jump_end_L_MP" {
	"titan_buddy_mp_core_anims\Jump_end_L_MP.smd"
	activity "ACT_MP_JUMP_LAND_LEFT" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "northstar_anim_sp_ai_flight_end_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "CQB_Rodeoed_Idle_MP" {
	"a_MP_CQB_idle"
	activity "ACT_RODEOED_STAND_IDLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "CQB_Rodeoed_CrouchIdle_MP" {
	"a_MP_crouch_IDLE"
	activity "ACT_RODEOED_CROUCH_IDLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "CQB_Rodeoed_Walk_MP" {
	"a_MP_rodeo_walk"
	activity "ACT_RODEOED_WALK" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "CQB_Rodeoed_CrouchWalk_MP" {
	"a_MP_rodeo_crouchwalk"
	activity "ACT_RODEOED_CROUCHWALK" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 0 "xo_atlas_jet_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "at_PiggyBack" {
	"a_PiggyBack"
	activity "ACT_BUSY_QUEUE" 1
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "at_MP_death_explosion" {
	"titan_buddy_mp_core_anims\at_MP_death_explosion.smd"
	activity "ACT_MP_DIE_INSTANT_STANDING" 1
	{ event AE_CL_VSCRIPT_CALLBACK 5 "hide_titan_eye" }
	{ event AE_FOOTSTEP_R 4 "Stand" }
	{ event AE_WPN_DROP 29 "" }
	{ event AE_RAGDOLL 33 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_Death_stumbleback_MP" {
	"a_Death_stumbleback"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 24 "" }
	{ event AE_CL_PLAYSOUND 28 "exo_stomp" }
	{ event AE_RAGDOLL 33 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_Death_twist_MP" {
	"a_Death_twist"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 14 "" }
	{ event AE_RAGDOLL 42 "" }
	{ event AE_CL_PLAYSOUND 43 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_Death_twist_L_MP" {
	"a_Death_twist_L"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 16 "" }
	{ event AE_RAGDOLL 18 "" }
	{ event AE_CL_PLAYSOUND 23 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_Death_fallforward_MP" {
	"a_Death_fallforward"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 16 "" }
	{ event AE_RAGDOLL 20 "" }
	{ event AE_CL_PLAYSOUND 25 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_damaged_MP" {
	"a_death_damaged"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 64 "" }
	{ event AE_CL_PLAYSOUND 69 "exo_stomp" }
	{ event AE_RAGDOLL 72 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_knockback_MP" {
	"a_death_knockback"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 12 "" }
	{ event AE_RAGDOLL 16 "" }
	{ event AE_CL_PLAYSOUND 15 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_slowfall_back_MP" {
	"a_death_slowfall_back"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 40 "" }
	{ event AE_RAGDOLL 44 "" }
	{ event AE_CL_PLAYSOUND 44 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_twitch_MP" {
	"a_death_twitch"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 13 "" }
	{ event AE_CL_PLAYSOUND 42 "exo_stomp" }
	{ event AE_RAGDOLL 45 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_swing_fall_L" {
	"titan_buddy_mp_core_anims\at_death_swing_fall_L.smd"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 38 "" }
	{ event AE_RAGDOLL 78 "" }
	{ event AE_CL_PLAYSOUND 89 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_robotwist_fall_L" {
	"titan_buddy_mp_core_anims\at_death_robotwist_fall_L.smd"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 41 "" }
	{ event AE_RAGDOLL 79 "" }
	{ event AE_CL_PLAYSOUND 88 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_MP_crouch_death_twitch" {
	"titan_buddy_mp_core_anims\a_MP_crouch_death_twitch.smd"
	activity "ACT_MP_DEATH_CROUCH" 1
	{ event AE_WPN_DROP 3 "" }
	{ event AE_RAGDOLL 27 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_MP_crouch_death_timber" {
	"titan_buddy_mp_core_anims\a_MP_crouch_death_timber.smd"
	activity "ACT_MP_DEATH_CROUCH" 2
	{ event AE_WPN_DROP 6 "" }
	{ event AE_RAGDOLL 86 "" }
	{ event AE_FOOTSTEP_R 9 "Crouch" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "Crouch" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 56 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_MP_crouch_death_stumbleback" {
	"titan_buddy_mp_core_anims\a_MP_crouch_death_stumbleback.smd"
	activity "ACT_MP_DEATH_CROUCH" 1
	{ event AE_WPN_DROP 37 "" }
	{ event AE_RAGDOLL 39 "" }
	{ event AE_FOOTSTEP_R 20 "Crouch" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "Crouch" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 34 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_MP_crouch_death_fallside" {
	"titan_buddy_mp_core_anims\a_MP_crouch_death_fallside.smd"
	activity "ACT_MP_DEATH_CROUCH" 2
	{ event AE_WPN_DROP 49 "" }
	{ event AE_RAGDOLL 63 "" }
	{ event AE_FOOTSTEP_L 7 "Crouch" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "Crouch" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 44 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_MP_crouch_death_fallback" {
	"titan_buddy_mp_core_anims\a_MP_crouch_death_fallback.smd"
	activity "ACT_MP_DEATH_CROUCH" 3
	{ event AE_WPN_DROP 32 "" }
	{ event AE_RAGDOLL 33 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_F" {
	"a_death_damaged"
	activity "ACT_MP_DEATH_WALK_FORWARD" 1
	{ event AE_WPN_DROP 64 "" }
	{ event AE_RAGDOLL 70 "" }
	{ event AE_CL_PLAYSOUND 69 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_F_stumble" {
	"titan_buddy_mp_core_anims\at_walking_death_F_stumble.smd"
	activity "ACT_MP_DEATH_WALK_FORWARD" 1
	{ event AE_WPN_DROP 16 "" }
	{ event AE_RAGDOLL 26 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_B" {
	"a_Death_stumbleback"
	activity "ACT_MP_DEATH_WALK_BACKWARD" 1
	{ event AE_FOOTSTEP_R 5 "Stand" }
	{ event AE_FOOTSTEP_L 18 "Stand" }
	{ event AE_WPN_DROP 30 "" }
	{ event AE_RAGDOLL 33 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_B_drop" {
	"titan_buddy_mp_core_anims\at_walking_death_B_drop.smd"
	activity "ACT_MP_DEATH_WALK_BACKWARD" 1
	{ event AE_FOOTSTEP_R 6 "Stand" }
	{ event AE_FOOTSTEP_R 40 "Stand" }
	{ event AE_WPN_DROP 54 "" }
	{ event AE_RAGDOLL 60 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_B_twitch" {
	"titan_buddy_mp_core_anims\at_walking_death_B_twitch.smd"
	activity "ACT_MP_DEATH_WALK_BACKWARD" 1
	{ event AE_FOOTSTEP_R 4 "Stand" }
	{ event AE_WPN_DROP 29 "" }
	{ event AE_RAGDOLL 33 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_drop_strafe_R" {
	"titan_buddy_mp_core_anims\at_death_drop_strafe_R.smd"
	activity "ACT_MP_DEATH_WALK_RIGHT" 1
	{ event AE_WPN_DROP 35 "" }
	{ event AE_RAGDOLL 40 "" }
	{ event AE_CL_PLAYSOUND 44 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_flail_strafe_R" {
	"titan_buddy_mp_core_anims\at_death_flail_strafe_R.smd"
	activity "ACT_MP_DEATH_WALK_RIGHT" 1
	{ event AE_FOOTSTEP_L 4 "Stand" }
	{ event AE_WPN_DROP 25 "" }
	{ event AE_RAGDOLL 30 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_robowalk_strafe_R" {
	"titan_buddy_mp_core_anims\at_death_robowalk_strafe_R.smd"
	activity "ACT_MP_DEATH_WALK_RIGHT" 1
	{ event AE_WPN_DROP 27 "" }
	{ event AE_RAGDOLL 45 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_R_stumble" {
	"titan_buddy_mp_core_anims\at_walking_death_R_stumble.smd"
	activity "ACT_MP_DEATH_WALK_RIGHT" 2
	{ event AE_FOOTSTEP_L 14 "Stand" }
	{ event AE_FOOTSTEP_R 39 "Stand" }
	{ event AE_WPN_DROP 70 "" }
	{ event AE_RAGDOLL 75 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_L_broken" {
	"titan_buddy_mp_core_anims\at_walking_death_L_broken.smd"
	activity "ACT_MP_DEATH_WALK_LEFT" 1
	{ event AE_WPN_DROP 41 "" }
	{ event AE_RAGDOLL 46 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_walking_death_L_stumble" {
	"titan_buddy_mp_core_anims\at_walking_death_L_stumble.smd"
	activity "ACT_MP_DEATH_WALK_LEFT" 2
	{ event AE_WPN_DROP 44 "" }
	{ event AE_RAGDOLL 57 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_F_crash" {
	"titan_buddy_mp_core_anims\at_death_run_F_crash.smd"
	activity "ACT_MP_DEATH_RUN_FORWARD" 1
	{ event AE_WPN_DROP 13 "" }
	{ event AE_RAGDOLL 17 "" }
	{ event AE_CL_PLAYSOUND 20 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_faceslam" {
	"titan_buddy_mp_core_anims\at_death_run_faceslam.smd"
	activity "ACT_MP_DEATH_RUN_FORWARD" 1
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_WPN_DROP 15 "" }
	{ event AE_RAGDOLL 23 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_sidefall" {
	"titan_buddy_mp_core_anims\at_death_run_sidefall.smd"
	activity "ACT_MP_DEATH_RUN_FORWARD" 1
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_WPN_DROP 17 "" }
	{ event AE_RAGDOLL 24 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_B_twitch" {
	"titan_buddy_mp_core_anims\at_death_run_B_twitch.smd"
	activity "ACT_MP_DEATH_RUN_BACKWARD" 2
	{ event AE_WPN_DROP 14 "" }
	{ event AE_RAGDOLL 23 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_B_crumble" {
	"titan_buddy_mp_core_anims\at_death_run_B_crumble.smd"
	activity "ACT_MP_DEATH_RUN_BACKWARD" 1
	{ event AE_FOOTSTEP_R 3 "Stand" }
	{ event AE_WPN_DROP 30 "" }
	{ event AE_RAGDOLL 39 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_drop_run_R" {
	"titan_buddy_mp_core_anims\at_death_drop_run_R.smd"
	activity "ACT_MP_DEATH_RUN_RIGHT" 1
	{ event AE_WPN_DROP 36 "" }
	{ event AE_RAGDOLL 40 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_R_stumble" {
	"titan_buddy_mp_core_anims\at_death_run_R_stumble.smd"
	activity "ACT_MP_DEATH_RUN_RIGHT" 3
	{ event AE_FOOTSTEP_L 3 "Stand" }
	{ event AE_WPN_DROP 5 "" }
	{ event AE_RAGDOLL 28 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_swing_run_L" {
	"titan_buddy_mp_core_anims\at_death_swing_run_L.smd"
	activity "ACT_MP_DEATH_RUN_LEFT" 1
	{ event AE_FOOTSTEP_L 8 "Stand" }
	{ event AE_WPN_DROP 35 "" }
	{ event AE_RAGDOLL 85 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_run_L_stumble" {
	"titan_buddy_mp_core_anims\at_death_run_L_stumble.smd"
	activity "ACT_MP_DEATH_RUN_LEFT" 3
	{ event AE_FOOTSTEP_R 3 "Stand" }
	{ event AE_WPN_DROP 12 "" }
	{ event AE_RAGDOLL 43 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_sprint_crash" {
	"a_death_sprint_crash"
	activity "ACT_MP_DEATH_SPRINT_FORWARD" 1
	{ event AE_FOOTSTEP_R 3 "Stand" }
	{ event AE_WPN_DROP 11 "" }
	{ event AE_RAGDOLL 17 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_sprint_F_stumble" {
	"a_death_sprint_F_stumble"
	activity "ACT_MP_DEATH_SPRINT_FORWARD" 1
	{ event AE_FOOTSTEP_R 5 "Stand" }
	{ event AE_FOOTSTEP_L 17 "Stand" }
	{ event AE_WPN_DROP 28 "" }
	{ event AE_RAGDOLL 34 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_death_Sprint_F_slam" {
	"a_death_Sprint_F_slam"
	activity "ACT_MP_DEATH_SPRINT_FORWARD" 1
	{ event AE_FOOTSTEP_L 9 "Stand" }
	{ event AE_WPN_DROP 16 "" }
	{ event AE_RAGDOLL 26 "" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_Death_crush" {
	"a_Death_fallforward"
	activity "ACT_MP_DEATH_CRUSH" 1
	{ event AE_CL_PLAYSOUND 25 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "player_Death_stumbleback" {
	"a_Death_stumbleback"
	activity "ACT_MP_DEATH_GENERIC" 1
	{ event AE_WPN_DROP 10 "" }
	{ event AE_RAGDOLL 33 "" }
	{ event AE_CL_PLAYSOUND 28 "exo_stomp" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_pain_add_F1" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_FORWARDS" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "at_MP_pain_add_B1" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_BACKWARDS" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "at_MP_pain_add_R1" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_RIGHT" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "at_MP_pain_add_L1" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_LEFT" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "Bullet_flinch_MP" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "Bullet_flinch_MP_primary" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_PRIMARY" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "Bullet_flinch_MP_melee" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_MELEE" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "Bullet_flinch_MP_chest" {
	"sp_Flinch"
	activity "ACT_MP_GESTURE_FLINCH_CHEST" 1
	delta
	fadein 0.2
	fadeout 0.2
	fps 30
	weightlist "weights_mp_stand_gesture_reload"
}

$sequence "at_MP_pain_F_twitch" {
	"a_MP_pain_F_twitch"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier stagger
	{ event AE_FOOTSTEP_L 26 "Stand" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 47 "Stand" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 59 "Stand" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 93 "Stand" }
	{ event AE_CL_PLAYSOUND 93 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_pain_L_shoulder" {
	"a_MP_pain_L_shoulder"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier stagger
	{ event AE_FOOTSTEP_R 8 "Stand" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "Stand" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "Stand" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "Stand" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_pain_L_shoulder_long" {
	"a_MP_pain_L_shoulder_long"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier stagger
	{ event AE_FOOTSTEP_R 14 "Stand" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "Stand" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 44 "Stand" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 60 "Stand" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 70 "Stand" }
	{ event AE_CL_PLAYSOUND 70 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_pain_F_short" {
	"a_MP_pain_F_short"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier stagger
	{ event AE_FOOTSTEP_L 25 "Stand" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 34 "Stand" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 54 "Stand" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_pain_R_twitch" {
	"a_MP_pain_R_twitch"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier stagger
	{ event AE_FOOTSTEP_R 12 "Stand" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 59 "Stand" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_pain_walk_stumble_A" {
	"titan_buddy_mp_core_anims\at_pain_walk_stumble_A.smd"
	activity "ACT_MP_STAGGERED_WALK_FORWARD" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "Stand" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 50 "Stand" }
	{ event AE_CL_PLAYSOUND 50 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 69 "Stand" }
	{ event AE_CL_PLAYSOUND 69 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 90 "Stand" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_pain_walk_stumble_B" {
	"titan_buddy_mp_core_anims\at_pain_walk_stumble_B.smd"
	activity "ACT_MP_STAGGERED_WALK_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 10 "Stand" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "Stand" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 40 "Stand" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 62 "Stand" }
	{ event AE_CL_PLAYSOUND 62 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_pain_walk_stumble_C" {
	"titan_buddy_mp_core_anims\at_pain_walk_stumble_C.smd"
	activity "ACT_MP_STAGGERED_WALK_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 12 "Stand" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "Stand" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_back_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_walk_back_stumble_A.smd"
	activity "ACT_MP_STAGGERED_WALK_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 9 "Stand" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "Stand" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 51 "Stand" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 78 "Stand" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_back_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_walk_back_stumble_B.smd"
	activity "ACT_MP_STAGGERED_WALK_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 21 "Stand" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "Stand" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "Stand" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 106 "Stand" }
	{ event AE_CL_PLAYSOUND 106 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_left_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_walk_left_stumble_A.smd"
	activity "ACT_MP_STAGGERED_WALK_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 6 "Stand" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "Stand" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 60 "Stand" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_left_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_walk_left_stumble_B.smd"
	activity "ACT_MP_STAGGERED_WALK_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "Stand" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 41 "Stand" }
	{ event AE_CL_PLAYSOUND 41 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 58 "Stand" }
	{ event AE_CL_PLAYSOUND 58 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_left_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_walk_left_stumble_C.smd"
	activity "ACT_MP_STAGGERED_WALK_LEFT" 3
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 1 "Stand" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "Stand" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 40 "Stand" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 58 "Stand" }
	{ event AE_CL_PLAYSOUND 58 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 83 "Stand" }
	{ event AE_CL_PLAYSOUND 83 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 112 "Stand" }
	{ event AE_CL_PLAYSOUND 112 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_right_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_walk_right_stumble_A.smd"
	activity "ACT_MP_STAGGERED_WALK_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 8 "Stand" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 23 "Stand" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "Stand" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 82 "Stand" }
	{ event AE_CL_PLAYSOUND 82 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_right_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_walk_right_stumble_B.smd"
	activity "ACT_MP_STAGGERED_WALK_RIGHT" 3
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 27 "Stand" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 60 "Stand" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 82 "Stand" }
	{ event AE_CL_PLAYSOUND 82 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_walk_right_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_walk_right_stumble_C.smd"
	activity "ACT_MP_STAGGERED_WALK_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 10 "Stand" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "Stand" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 47 "Stand" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_A.smd"
	activity "ACT_MP_STAGGERED_RUN_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 9 "Stand" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 22 "Stand" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "Stand" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 50 "Stand" }
	{ event AE_CL_PLAYSOUND 50 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 64 "Stand" }
	{ event AE_CL_PLAYSOUND 64 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_B.smd"
	activity "ACT_MP_STAGGERED_RUN_FORWARD" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 4 "Stand" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 12 "Stand" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 22 "Stand" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 35 "Stand" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 48 "Stand" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 61 "Stand" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_C.smd"
	activity "ACT_MP_STAGGERED_RUN_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 15 "Stand" }
	{ event AE_CL_PLAYSOUND 15 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 26 "Stand" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 53 "Stand" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 66 "Stand" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_back_A" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_back_A.smd"
	activity "ACT_MP_STAGGERED_RUN_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 9 "Stand" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "Stand" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 51 "Stand" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 78 "Stand" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_back_B" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_back_B.smd"
	activity "ACT_MP_STAGGERED_RUN_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 21 "Stand" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "Stand" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "Stand" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 106 "Stand" }
	{ event AE_CL_PLAYSOUND 106 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_left_A" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_left_A.smd"
	activity "ACT_MP_STAGGERED_RUN_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 6 "Stand" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "Stand" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 60 "Stand" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_left_B" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_left_B.smd"
	activity "ACT_MP_STAGGERED_RUN_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "Stand" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 41 "Stand" }
	{ event AE_CL_PLAYSOUND 41 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 58 "Stand" }
	{ event AE_CL_PLAYSOUND 58 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_left_C" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_left_C.smd"
	activity "ACT_MP_STAGGERED_RUN_LEFT" 3
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 1 "Stand" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "Stand" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 40 "Stand" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 58 "Stand" }
	{ event AE_CL_PLAYSOUND 58 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 83 "Stand" }
	{ event AE_CL_PLAYSOUND 83 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 112 "Stand" }
	{ event AE_CL_PLAYSOUND 112 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_right_A" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_right_A.smd"
	activity "ACT_MP_STAGGERED_RUN_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 8 "Stand" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 23 "Stand" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "Stand" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 82 "Stand" }
	{ event AE_CL_PLAYSOUND 82 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_right_B" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_right_B.smd"
	activity "ACT_MP_STAGGERED_RUN_RIGHT" 3
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 27 "Stand" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 60 "Stand" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 82 "Stand" }
	{ event AE_CL_PLAYSOUND 82 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_run_stumble_right_C" {
	"titan_buddy_mp_core_anims\at_MP_run_stumble_right_C.smd"
	activity "ACT_MP_STAGGERED_RUN_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 10 "Stand" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "Stand" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 47 "Stand" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_sprint_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_sprint_stumble_A.smd"
	activity "ACT_MP_STAGGERED_SPRINT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 6 "Stand" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "Stand" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 32 "Stand" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_sprint_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_sprint_stumble_B.smd"
	activity "ACT_MP_STAGGERED_SPRINT" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 7 "Stand" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "Stand" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "Stand" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 42 "Stand" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_sprint_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_sprint_stumble_C.smd"
	activity "ACT_MP_STAGGERED_SPRINT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 5 "Stand" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "Stand" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 33 "Stand" }
	{ event AE_CL_PLAYSOUND 33 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_F_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_F_stumble_A.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_FORWARD" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 7 "Crouch" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 27 "Crouch" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 51 "Crouch" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 73 "Crouch" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 95 "Crouch" }
	{ event AE_CL_PLAYSOUND 95 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_F_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_F_stumble_B.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 17 "Crouch" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 30 "Crouch" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "Crouch" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 71 "Crouch" }
	{ event AE_CL_PLAYSOUND 71 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_F_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_F_stumble_C.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 7 "Crouch" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "Crouch" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 49 "Crouch" }
	{ event AE_CL_PLAYSOUND 49 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 69 "Crouch" }
	{ event AE_CL_PLAYSOUND 69 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_B_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_B_stumble_A.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 7 "Crouch" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 17 "Crouch" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 38 "Crouch" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 60 "Crouch" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 87 "Crouch" }
	{ event AE_CL_PLAYSOUND 87 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_B_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_B_stumble_B.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_BACKWARD" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 19 "Crouch" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 31 "Crouch" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 43 "Crouch" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 64 "Crouch" }
	{ event AE_CL_PLAYSOUND 64 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_B_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_B_stumble_C.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_BACKWARD" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 17 "Crouch" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "Crouch" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 38 "Crouch" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 59 "Crouch" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 87 "Crouch" }
	{ event AE_CL_PLAYSOUND 87 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_B_stumble_D" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_B_stumble_D.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 36 "Crouch" }
	{ event AE_CL_PLAYSOUND 36 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "Crouch" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 72 "Crouch" }
	{ event AE_CL_PLAYSOUND 72 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_L_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_L_stumble_A.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 5 "Crouch" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 13 "Crouch" }
	{ event AE_CL_PLAYSOUND 13 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "Crouch" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 55 "Crouch" }
	{ event AE_CL_PLAYSOUND 55 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 78 "Crouch" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_L_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_L_stumble_B.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_LEFT" 3
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 20 "Crouch" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 39 "Crouch" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "Crouch" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 87 "Crouch" }
	{ event AE_CL_PLAYSOUND 87 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_L_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_L_stumble_C.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 12 "Crouch" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "Crouch" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "Crouch" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 57 "Crouch" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_R_stumble_A" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_R_stumble_A.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_RIGHT" 2
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 1 "Crouch" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "Crouch" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 48 "Crouch" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 71 "Crouch" }
	{ event AE_CL_PLAYSOUND 71 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 96 "Crouch" }
	{ event AE_CL_PLAYSOUND 96 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 121 "Crouch" }
	{ event AE_CL_PLAYSOUND 121 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_R_stumble_B" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_R_stumble_B.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 4 "Crouch" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "Crouch" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 61 "Crouch" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_MP_crouchwalk_R_stumble_C" {
	"titan_buddy_mp_core_anims\at_MP_crouchwalk_R_stumble_C.smd"
	activity "ACT_MP_STAGGERED_CROUCHWALK_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 1 "Crouch" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 26 "Crouch" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 50 "Crouch" }
	{ event AE_CL_PLAYSOUND 50 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 72 "Crouch" }
	{ event AE_CL_PLAYSOUND 72 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 97 "Crouch" }
	{ event AE_CL_PLAYSOUND 97 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Aim_doomed_MP" {
	"a_aim_doomed_up_left_MP"
	"a_aim_doomed_up_center_MP"
	"a_aim_doomed_up_right_MP"
	"a_aim_doomed_mid_left_MP"
	"a_aim_doomed_mid_center_MP"
	"a_aim_doomed_mid_right_MP"
	"a_aim_doomed_down_left_MP"
	"a_aim_doomed_down_center_MP"
	"a_aim_doomed_down_right_MP"
}

$sequence "at_doomed_idle" {
	"titan_buddy_mp_core_anims\at_doomed_idle.smd"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 101 "Stand" }
	{ event AE_CL_PLAYSOUND 101 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 174 "Stand" }
	{ event AE_CL_PLAYSOUND 174 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 234 "Stand" }
	{ event AE_CL_PLAYSOUND 234 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_doomed_MP"
	fps 30
	loop
}

$sequence "at_doomed_crouch_idle" {
	"titan_buddy_mp_core_anims\at_doomed_crouch_idle.smd"
	activity "ACT_MP_CROUCH_IDLE" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_L 38 "Stand" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 101 "Stand" }
	{ event AE_CL_PLAYSOUND 101 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 174 "Stand" }
	{ event AE_CL_PLAYSOUND 174 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 234 "Stand" }
	{ event AE_CL_PLAYSOUND 234 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_doomed_MP"
	fps 30
	loop
}

$sequence "at_doomed_pain_shoulder" {
	"titan_buddy_mp_core_anims\at_doomed_pain_shoulder.smd"
	activity "ACT_MP_STAND_IDLE" 1
	activitymodifier doomed
	activitymodifier 
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_doomed_pain_stumble" {
	"titan_buddy_mp_core_anims\at_doomed_pain_stumble.smd"
	activity "ACT_MP_STAND_IDLE" 2
	activitymodifier doomed
	activitymodifier 
	{ event AE_FOOTSTEP_R 14 "Stand" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 29 "Stand" }
	{ event AE_CL_PLAYSOUND 29 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 44 "Stand" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_doomed_pain_torso" {
	"titan_buddy_mp_core_anims\at_doomed_pain_torso.smd"
	activity "ACT_MP_STAND_IDLE" 2
	activitymodifier doomed
	activitymodifier 
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_doomed_walk_F" {
	"titan_buddy_mp_core_anims\at_doomed_walk_F.smd"
	activity "ACT_MP_WALK_FORWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 1 "Stand" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "Stand" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 58 "Stand" }
	{ event AE_CL_PLAYSOUND 58 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 79 "Stand" }
	{ event AE_CL_PLAYSOUND 79 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 90 "Stand" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 103 "Stand" }
	{ event AE_CL_PLAYSOUND 103 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 118 "Stand" }
	{ event AE_CL_PLAYSOUND 118 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 134 "Stand" }
	{ event AE_CL_PLAYSOUND 134 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 148 "Stand" }
	{ event AE_CL_PLAYSOUND 148 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 175 "Stand" }
	{ event AE_CL_PLAYSOUND 175 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "at_doomed_walk_B" {
	"titan_buddy_mp_core_anims\at_doomed_walk_B.smd"
	activity "ACT_MP_WALK_BACKWARD" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 6 "Stand" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 44 "Stand" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 53 "Stand" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 70 "Stand" }
	{ event AE_CL_PLAYSOUND 70 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 92 "Stand" }
	{ event AE_CL_PLAYSOUND 92 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 111 "Stand" }
	{ event AE_CL_PLAYSOUND 111 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 122 "Stand" }
	{ event AE_CL_PLAYSOUND 122 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 135 "Stand" }
	{ event AE_CL_PLAYSOUND 135 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "at_doomed_strafe_R" {
	"titan_buddy_mp_core_anims\at_doomed_strafe_R.smd"
	activity "ACT_MP_WALK_RIGHT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 3 "Stand" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 31 "Stand" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 43 "Stand" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 69 "Stand" }
	{ event AE_CL_PLAYSOUND 69 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 79 "Stand" }
	{ event AE_CL_PLAYSOUND 79 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 99 "Stand" }
	{ event AE_CL_PLAYSOUND 99 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "at_doomed_strafe_L" {
	"titan_buddy_mp_core_anims\at_doomed_strafe_L.smd"
	activity "ACT_MP_WALK_LEFT" 1
	activitymodifier doomed
	{ event AE_FOOTSTEP_R 4 "Stand" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "Stand" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 32 "Stand" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 52 "Stand" }
	{ event AE_CL_PLAYSOUND 52 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 66 "Stand" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 88 "Stand" }
	{ event AE_CL_PLAYSOUND 88 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}
