// Created by Crowbar 0.71

$modelname "titans/buddy/titan_buddy_SP_core.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_intBase" ""
$jointsurfaceprop "def_c_cam" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_l_hip" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_thighLow" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_hip" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_thighLow" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_c_hatchTop" ""
$jointsurfaceprop "def_c_hatchBot" ""
$jointsurfaceprop "def_c_hatchHead" ""
$jointsurfaceprop "def_c_neck1" ""
$jointsurfaceprop "def_c_eye_rotate" ""
$jointsurfaceprop "def_c_eye_detached" ""
$jointsurfaceprop "def_c_eyeball" ""
$jointsurfaceprop "def_c_eye_outer" ""
$jointsurfaceprop "def_c_eyelid" ""
$jointsurfaceprop "def_l_eyelid" ""
$jointsurfaceprop "def_r_eyelid" ""
$jointsurfaceprop "def_l_eye_side" ""
$jointsurfaceprop "def_r_eye_side" ""
$jointsurfaceprop "def_l_eye_side_cover" ""
$jointsurfaceprop "def_r_eye_side_cover" ""
$jointsurfaceprop "def_l_piston_rear_knee1" ""
$jointsurfaceprop "def_l_piston_rear_knee2" ""
$jointsurfaceprop "def_r_piston_rear_knee1" ""
$jointsurfaceprop "def_r_piston_rear_knee2" ""
$jointsurfaceprop "def_cam_shoulder" ""
$jointsurfaceprop "def_l_missile_root" ""
$jointsurfaceprop "def_l_missile_leg1" ""
$jointsurfaceprop "def_l_missile_leg2" ""
$jointsurfaceprop "def_l_missile_leg3" ""
$jointsurfaceprop "def_l_missile_leg4" ""
$jointsurfaceprop "def_l_missile_wing_out1" ""
$jointsurfaceprop "def_l_missile_wing_out2" ""
$jointsurfaceprop "def_l_missile_wing_out_hook1" ""
$jointsurfaceprop "def_l_missile_wing_out_hook2" ""
$jointsurfaceprop "def_l_missile_wing_in1" ""
$jointsurfaceprop "def_l_missile_wing_in2" ""
$jointsurfaceprop "def_l_missile_wing_in_hook1" ""
$jointsurfaceprop "def_l_missile_wing_in_hook2" ""
$jointsurfaceprop "def_l_missile_box" ""
$jointsurfaceprop "def_l_holder" ""
$jointsurfaceprop "def_l_holder_clip1" ""
$jointsurfaceprop "def_l_holder_clip2" ""
$jointsurfaceprop "def_r_missile_root" ""
$jointsurfaceprop "def_r_missile_leg1" ""
$jointsurfaceprop "def_r_missile_leg2" ""
$jointsurfaceprop "def_r_missile_leg3" ""
$jointsurfaceprop "def_r_missile_leg4" ""
$jointsurfaceprop "def_r_missile_wing_out1" ""
$jointsurfaceprop "def_r_missile_wing_out2" ""
$jointsurfaceprop "def_r_missile_wing_out_hook1" ""
$jointsurfaceprop "def_r_missile_wing_out_hook2" ""
$jointsurfaceprop "def_r_missile_wing_in1" ""
$jointsurfaceprop "def_r_missile_wing_in2" ""
$jointsurfaceprop "def_r_missile_wing_in_hook1" ""
$jointsurfaceprop "def_r_missile_wing_in_hook2" ""
$jointsurfaceprop "def_r_missile_box" ""
$jointsurfaceprop "def_r_holder" ""
$jointsurfaceprop "def_r_holder_clip1" ""
$jointsurfaceprop "def_r_holder_clip2" ""
$jointsurfaceprop "def_r_down_missile_doorA1" ""
$jointsurfaceprop "def_r_down_missile_doorB1" ""
$jointsurfaceprop "def_r_down_missile_doorC1" ""
$jointsurfaceprop "def_r_up_missile_doorA1" ""
$jointsurfaceprop "def_r_up_missile_doorB1" ""
$jointsurfaceprop "def_r_up_missile_doorC1" ""
$jointsurfaceprop "def_l_down_missile_doorC1" ""
$jointsurfaceprop "def_l_down_missile_doorB1" ""
$jointsurfaceprop "def_l_down_missile_doorA1" ""
$jointsurfaceprop "def_l_up_missile_doorC1" ""
$jointsurfaceprop "def_l_up_missile_doorB1" ""
$jointsurfaceprop "def_l_up_missile_doorA1" ""
$jointsurfaceprop "def_l_shock_waist_front_up" ""
$jointsurfaceprop "def_l_shock_waist_side_up" ""
$jointsurfaceprop "def_l_shock_waist_back_up" ""
$jointsurfaceprop "def_r_shock_waist_front_up" ""
$jointsurfaceprop "def_r_shock_waist_side_up" ""
$jointsurfaceprop "def_r_shock_waist_back_up" ""
$jointsurfaceprop "def_l_shock_waist_front_down" ""
$jointsurfaceprop "def_l_shock_waist_side_down" ""
$jointsurfaceprop "def_l_shock_waist_back_down" ""
$jointsurfaceprop "def_r_shock_waist_front_down" ""
$jointsurfaceprop "def_r_shock_waist_side_down" ""
$jointsurfaceprop "def_r_shock_waist_back_down" ""
$jointsurfaceprop "def_l_shock_knee_up" ""
$jointsurfaceprop "def_l_shock_knee_down" ""
$jointsurfaceprop "def_r_shock_knee_up" ""
$jointsurfaceprop "def_r_shock_knee_down" ""
$jointsurfaceprop "def_l_heel" ""
$jointsurfaceprop "def_l_heel_shock_start" ""
$jointsurfaceprop "def_l_heel_shock_end" ""
$jointsurfaceprop "def_r_heel" ""
$jointsurfaceprop "def_r_heel_shock_start" ""
$jointsurfaceprop "def_r_heel_shock_end" ""
$jointsurfaceprop "jx_l_ankle_hb" ""
$jointsurfaceprop "jx_r_ankle_hb" ""
$jointsurfaceprop "jx_c_hatch_1_hb" ""
$jointsurfaceprop "jx_c_hatch_2_hb" ""
$jointsurfaceprop "jx_c_hatch_3_hb" ""
$jointsurfaceprop "jx_c_hatch_4_hb" ""
$jointsurfaceprop "jx_c_hatch_5_hb" ""
$jointsurfaceprop "jx_vortex" ""
$jointsurfaceprop "def_l_battery1" ""
$jointsurfaceprop "def_l_battery2" ""
$jointsurfaceprop "def_l_battery3" ""
$jointsurfaceprop "jx_c_camera_2" ""
$jointsurfaceprop "jx_c_camera_3" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_intBase" "notsolid"
$jointcontents "def_c_cam" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_l_hip" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_thighLow" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_hip" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_thighLow" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_c_hatchTop" "notsolid"
$jointcontents "def_c_hatchBot" "notsolid"
$jointcontents "def_c_hatchHead" "notsolid"
$jointcontents "def_c_neck1" "notsolid"
$jointcontents "def_c_eye_rotate" "notsolid"
$jointcontents "def_c_eye_detached" "notsolid"
$jointcontents "def_c_eyeball" "notsolid"
$jointcontents "def_c_eye_outer" "notsolid"
$jointcontents "def_c_eyelid" "notsolid"
$jointcontents "def_l_eyelid" "notsolid"
$jointcontents "def_r_eyelid" "notsolid"
$jointcontents "def_l_eye_side" "notsolid"
$jointcontents "def_r_eye_side" "notsolid"
$jointcontents "def_l_eye_side_cover" "notsolid"
$jointcontents "def_r_eye_side_cover" "notsolid"
$jointcontents "def_l_piston_rear_knee1" "notsolid"
$jointcontents "def_l_piston_rear_knee2" "notsolid"
$jointcontents "def_r_piston_rear_knee1" "notsolid"
$jointcontents "def_r_piston_rear_knee2" "notsolid"
$jointcontents "def_cam_shoulder" "notsolid"
$jointcontents "def_l_missile_root" "notsolid"
$jointcontents "def_l_missile_leg1" "notsolid"
$jointcontents "def_l_missile_leg2" "notsolid"
$jointcontents "def_l_missile_leg3" "notsolid"
$jointcontents "def_l_missile_leg4" "notsolid"
$jointcontents "def_l_missile_wing_out1" "notsolid"
$jointcontents "def_l_missile_wing_out2" "notsolid"
$jointcontents "def_l_missile_wing_out_hook1" "notsolid"
$jointcontents "def_l_missile_wing_out_hook2" "notsolid"
$jointcontents "def_l_missile_wing_in1" "notsolid"
$jointcontents "def_l_missile_wing_in2" "notsolid"
$jointcontents "def_l_missile_wing_in_hook1" "notsolid"
$jointcontents "def_l_missile_wing_in_hook2" "notsolid"
$jointcontents "def_l_missile_box" "notsolid"
$jointcontents "def_l_holder" "notsolid"
$jointcontents "def_l_holder_clip1" "notsolid"
$jointcontents "def_l_holder_clip2" "notsolid"
$jointcontents "def_r_missile_root" "notsolid"
$jointcontents "def_r_missile_leg1" "notsolid"
$jointcontents "def_r_missile_leg2" "notsolid"
$jointcontents "def_r_missile_leg3" "notsolid"
$jointcontents "def_r_missile_leg4" "notsolid"
$jointcontents "def_r_missile_wing_out1" "notsolid"
$jointcontents "def_r_missile_wing_out2" "notsolid"
$jointcontents "def_r_missile_wing_out_hook1" "notsolid"
$jointcontents "def_r_missile_wing_out_hook2" "notsolid"
$jointcontents "def_r_missile_wing_in1" "notsolid"
$jointcontents "def_r_missile_wing_in2" "notsolid"
$jointcontents "def_r_missile_wing_in_hook1" "notsolid"
$jointcontents "def_r_missile_wing_in_hook2" "notsolid"
$jointcontents "def_r_missile_box" "notsolid"
$jointcontents "def_r_holder" "notsolid"
$jointcontents "def_r_holder_clip1" "notsolid"
$jointcontents "def_r_holder_clip2" "notsolid"
$jointcontents "def_r_down_missile_doorA1" "notsolid"
$jointcontents "def_r_down_missile_doorB1" "notsolid"
$jointcontents "def_r_down_missile_doorC1" "notsolid"
$jointcontents "def_r_up_missile_doorA1" "notsolid"
$jointcontents "def_r_up_missile_doorB1" "notsolid"
$jointcontents "def_r_up_missile_doorC1" "notsolid"
$jointcontents "def_l_down_missile_doorC1" "notsolid"
$jointcontents "def_l_down_missile_doorB1" "notsolid"
$jointcontents "def_l_down_missile_doorA1" "notsolid"
$jointcontents "def_l_up_missile_doorC1" "notsolid"
$jointcontents "def_l_up_missile_doorB1" "notsolid"
$jointcontents "def_l_up_missile_doorA1" "notsolid"
$jointcontents "def_l_shock_waist_front_up" "notsolid"
$jointcontents "def_l_shock_waist_side_up" "notsolid"
$jointcontents "def_l_shock_waist_back_up" "notsolid"
$jointcontents "def_r_shock_waist_front_up" "notsolid"
$jointcontents "def_r_shock_waist_side_up" "notsolid"
$jointcontents "def_r_shock_waist_back_up" "notsolid"
$jointcontents "def_l_shock_waist_front_down" "notsolid"
$jointcontents "def_l_shock_waist_side_down" "notsolid"
$jointcontents "def_l_shock_waist_back_down" "notsolid"
$jointcontents "def_r_shock_waist_front_down" "notsolid"
$jointcontents "def_r_shock_waist_side_down" "notsolid"
$jointcontents "def_r_shock_waist_back_down" "notsolid"
$jointcontents "def_l_shock_knee_up" "notsolid"
$jointcontents "def_l_shock_knee_down" "notsolid"
$jointcontents "def_r_shock_knee_up" "notsolid"
$jointcontents "def_r_shock_knee_down" "notsolid"
$jointcontents "def_l_heel" "notsolid"
$jointcontents "def_l_heel_shock_start" "notsolid"
$jointcontents "def_l_heel_shock_end" "notsolid"
$jointcontents "def_r_heel" "notsolid"
$jointcontents "def_r_heel_shock_start" "notsolid"
$jointcontents "def_r_heel_shock_end" "notsolid"
$jointcontents "jx_l_ankle_hb" "notsolid"
$jointcontents "jx_r_ankle_hb" "notsolid"
$jointcontents "jx_c_hatch_1_hb" "notsolid"
$jointcontents "jx_c_hatch_2_hb" "notsolid"
$jointcontents "jx_c_hatch_3_hb" "notsolid"
$jointcontents "jx_c_hatch_4_hb" "notsolid"
$jointcontents "jx_c_hatch_5_hb" "notsolid"
$jointcontents "jx_vortex" "notsolid"
$jointcontents "def_l_battery1" "notsolid"
$jointcontents "def_l_battery2" "notsolid"
$jointcontents "def_l_battery3" "notsolid"
$jointcontents "jx_c_camera_2" "notsolid"
$jointcontents "jx_c_camera_3" "notsolid"

$illumposition 0.001 14.247 165.982

$eyeposition 0 0 220

$cdmaterials ""

$attachment "HEADFOCUS" "def_c_eye_rotate" 0 0 0 rotate -90 -90 0

$cbox 0 0 0 0 0 0

$bbox -68.494 -167.616 -10.826 40 167.618 232.135

$hboxset "default"
$hbox 3 "def_c_hip" -26.056641 -28.256638 -32.149147 26.056641 16.637367 38.928268 ""
$hbox 2 "def_c_spineB" -19.684999 -2.114169 -19.684999 19.684999 8.119275 19.684999 ""
$hbox 2 "def_c_spineC" 17.113352 19.131458 -31.474346 46.786522 51.156982 15.303513 ""
$hbox 2 "def_c_spineC" -17.485792 22.0909 -53.867611 17.485792 59.975868 11.166513 ""
$hbox 2 "def_c_spineC" -23.121607 -9.501556 -29.323172 23.121607 2.900782 33.051903 ""
$hbox 2 "def_c_spineC" -27.716875 1.840941 -35.222767 27.716875 23.757038 34.452293 ""
$hbox 2 "def_c_spineC" -16.677132 22.961765 4.692904 16.677132 57.67902 42.772354 ""
$hbox 2 "def_c_spineC" -47.464867 19.720827 -32.483795 -13.937374 49.445572 10.003524 ""
$hbox 6 "def_l_ankle" -15.501938 -10.50864 -14.077925 29.804667 5.293296 14.077925 ""
$hbox 4 "def_l_elbow" -0.485038 -9.654705 -14.700365 41.759365 11.443678 10.303523 ""
$hbox 6 "def_l_knee" -0.416928 -14.385405 -11.154308 38.952679 8.759432 11.154308 ""
$hbox 4 "def_l_shoulder" -1.443304 -11.974386 -14.59249 38.138115 11.93974 14.59249 ""
$hbox 6 "def_l_thigh" -14.184224 -18.553112 -16.12792 54.436115 18.553112 16.12792 ""
$hbox 6 "def_l_thighLow" -0.082677 -11.30549 -11.317301 39.28693 18.594452 11.317301 ""
$hbox 4 "def_l_wrist" 0.570865 -5.599989 -13.025958 39.992046 7.89526 9.212187 ""
$hbox 7 "def_r_ankle" -29.804667 -5.293296 -14.077925 15.501938 10.50864 14.077925 ""
$hbox 5 "def_r_elbow" -41.759758 -11.448402 -10.305491 0.485038 9.649981 14.698396 ""
$hbox 7 "def_r_knee" -38.952679 -8.759432 -11.154308 0.416928 14.385405 11.154308 ""
$hbox 5 "def_r_shoulder" -38.138115 -11.93974 -14.59249 1.443304 11.974386 14.59249 ""
$hbox 7 "def_r_thigh" -54.436115 -18.553112 -16.12792 14.184224 18.553112 16.12792 ""
$hbox 7 "def_r_thighLow" -39.28693 -18.594452 -11.317301 0.082677 11.30549 11.317301 ""
$hbox 5 "def_r_wrist" -39.990868 -7.894866 -9.219273 -0.571652 5.599595 13.018872 ""
$hboxset "entryboxes"
$hbox 1 "jx_c_delta" -39.99992 0 0 39.99992 99.999802 139.999725 ""
$hboxset "EFFECTS_TORSO"
$hbox 3 "def_c_hip" -26.056641 -28.256638 -32.149147 26.056641 16.637367 38.928268 ""
$hbox 2 "def_c_spineB" -19.684999 -2.114169 -19.684999 19.684999 8.119275 19.684999 ""
$hbox 2 "def_c_spineC" 17.113352 19.131458 -31.474346 46.786522 51.156982 15.303513 ""
$hbox 2 "def_c_spineC" -17.485792 22.0909 -53.867611 17.485792 59.975868 11.166513 ""
$hbox 2 "def_c_spineC" -23.121607 -9.501556 -29.323172 23.121607 2.900782 33.051903 ""
$hbox 2 "def_c_spineC" -27.716875 1.840941 -35.222767 27.716875 23.757038 34.452293 ""
$hbox 2 "def_c_spineC" -16.677132 22.961765 4.692904 16.677132 57.67902 42.772354 ""
$hbox 2 "def_c_spineC" -47.464867 19.720827 -32.483795 -13.937374 49.445572 10.003524 ""
$skipboneinbbox

$screenalign def_l_thigh "sphere"
$screenalign def_l_ankle "cylinder"
$screenalign def_l_ball "cylinder"
$screenalign def_r_thigh "cylinder"
$screenalign def_r_thighLow "sphere"
$screenalign def_r_knee "sphere"
$screenalign def_r_ankle "sphere"
$screenalign def_r_ball "sphere"
$screenalign def_r_kneeB "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "sphere"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_l_finPinkyA "sphere"
$screenalign def_l_finRingA "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "sphere"
$screenalign def_l_finMidC "sphere"
$screenalign def_l_finIndexA "sphere"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finIndexC "sphere"
$screenalign def_r_piston_rear_knee1 "cylinder"
$screenalign def_r_piston_rear_knee2 "sphere"
$screenalign def_r_shock_knee_up "sphere"
$screenalign def_r_shock_knee_down "sphere"
$screenalign def_l_heel "cylinder"
$screenalign def_l_heel_shock_end "cylinder"
$screenalign def_r_heel "sphere"
$screenalign def_r_heel_shock_start "sphere"
$screenalign def_r_heel_shock_end "sphere"
$screenalign jx_r_ankle_hb "cylinder"
$screenalign jx_c_hatch_1_hb "sphere"
$screenalign jx_c_hatch_2_hb "sphere"
$screenalign jx_c_hatch_3_hb "sphere"
$screenalign jx_c_hatch_4_hb "sphere"
$screenalign jx_c_hatch_5_hb "sphere"
$screenalign def_l_battery1 "cylinder"
$screenalign def_l_battery2 "cylinder"
$screenalign def_l_battery3 "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 205.41214 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 128.382584 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 18.230331 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 18.101944 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -23.494019 32.095646 0 0 0 0 0 0 0 0 0
$definebone "def_c_intBase" "def_c_spineC" 0 22.637772 -10.026639 0 0 0 0 0 0 0 0 0
$definebone "def_c_cam" "def_c_spineC" 11.92436 58.197601 9.257601 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 27.730637 -0.770296 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 14.250473 3.081182 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 12.838257 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 21.440704 20.611954 -10.184802 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 26.678253 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 14.577797 -0.034866 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 30.95401 -0.036438 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 33.962181 -0.009247 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 22.262924 -0.009247 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulderMid" 30.95401 -0.036438 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -21.440704 20.611938 -10.184783 0 0 179.99995 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -26.678093 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -14.577923 0.035034 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -30.953876 0.036224 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -33.962532 0.009445 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -22.262947 0.009445 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulderMid" -30.953876 0.036224 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_hip" "def_c_hip" 10.269186 -7.287552 1.29411 0 0 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_l_hip" 13.153353 0 0 -5.975595 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_thighLow" "def_l_thigh" 46.445686 0 0 0 -58.138761 0 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thighLow" 27.332199 -0.000011 0 0 49.144864 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 30.113514 -0.000002 0.000004 0 23.663494 -179.99995 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 21.867176 0.000001 -0.000002 0 -58.296129 0 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thighLow" 27.332199 -0.000011 0 0 49.144864 0 0 0 0 0 0 0
$definebone "def_r_hip" "def_c_hip" -10.269192 -7.287552 1.294112 0 0 179.99995 0 0 0 0 0 0
$definebone "def_r_thigh" "def_r_hip" -13.153358 0 0 -5.975595 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_r_thighLow" "def_r_thigh" -46.445595 0.000001 0 0 -58.138761 0.000002 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thighLow" -27.332275 -0.000103 0 0.000001 49.144864 0.000003 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -30.113447 0.000004 -0.000002 0.000002 23.663493 179.999923 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -21.867199 0.000015 0 0 -58.296129 0 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thighLow" -27.332275 -0.000103 0 0.000001 49.144864 0.000003 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -18.072998 10.743011 -11.2882 0 -60.000002 0 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -9.96534 -0.000366 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -16.316849 0.000427 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -49.919006 2.60701 -12.5817 -7.986965 -4.034867 0.561547 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -17.335678 0.000046 0.000061 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -17.303375 0.000259 -0.000132 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -51.898987 1.989975 2.4909 2.664609 -3.774691 -0.175737 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -18.214111 -0.000793 -0.000067 -0.015875 0.022383 0.00104 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -18.289734 0.000381 0.000064 0 0 0 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -33.880005 1.194992 7.631501 0 0 0 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -14.29599 0 10.273399 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -17.335098 0.000366 0.000053 0.674843 0.004337 -0.044802 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -15.292389 0.000061 -0.000034 0.000002 0 0 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" -14.29599 0.000031 27.300001 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -17.335068 0.000351 0.00005 0.674843 0.004337 -0.044802 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -15.292389 0.000015 -0.000031 0.000002 0 0 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 33.880707 -1.195313 -7.631406 0 0 0 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" 10.343628 0 -27.299999 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 17.335297 0.000015 0.000011 0.674843 0.004338 -0.044802 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 15.292435 -0.000046 -0.000004 0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 14.295349 0 -10.273407 13.052609 -3.903627 -0.882914 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 17.335281 -0.000015 0.000002 0.674843 0.004338 -0.044802 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 15.29245 0.000031 -0.000002 0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 51.899139 -1.990082 -2.490812 2.664609 -3.774691 -0.175737 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 18.214203 0 0 -0.015875 0.022383 0.00104 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 18.289703 -0.000061 -0.000003 0 0 0 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 49.919678 -2.607758 12.58179 -7.986965 -4.034867 0.561547 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 17.335205 -0.000031 0 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 17.303894 0.000031 0.000002 -0.000001 0 0 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 18.073822 -10.743774 11.288211 0 -60.000002 0 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 9.965164 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 16.316956 0 0 0 0 0 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 12.846619 -4.144196 0.731267 -0.112595 0.077172 -0.000076 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -12.846436 4.144089 -0.731257 -0.112595 0.077172 -0.000076 0 0 0 0 0 0
$definebone "def_c_hatchTop" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hatchBot" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hatchHead" "def_c_spineC" 0 58.896729 -8.825905 0 0 0 0 0 0 0 0 0
$definebone "def_c_neck1" "def_c_hatchTop" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_rotate" "def_c_neck1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_detached" "def_c_eye_rotate" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eyeball" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eye_outer" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eyelid" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eye_side" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eye_side" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_eye_side_cover" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_eye_side_cover" "def_c_eye_detached" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_piston_rear_knee1" "def_l_thigh" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_piston_rear_knee2" "def_l_thighLow" 0 0 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_piston_rear_knee1" "def_r_thigh" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_piston_rear_knee2" "def_r_thighLow" 0 0 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_cam_shoulder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_root" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg1" "def_l_missile_root" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg2" "def_l_missile_leg1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg3" "def_l_missile_leg2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_leg4" "def_l_missile_leg3" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out1" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out2" "def_l_missile_wing_out1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out_hook1" "def_l_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_out_hook2" "def_l_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in1" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in2" "def_l_missile_wing_in1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in_hook1" "def_l_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_wing_in_hook2" "def_l_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_missile_box" "def_l_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder_clip1" "def_l_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_holder_clip2" "def_l_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_root" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg1" "def_r_missile_root" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg2" "def_r_missile_leg1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg3" "def_r_missile_leg2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_leg4" "def_r_missile_leg3" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out1" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out2" "def_r_missile_wing_out1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out_hook1" "def_r_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_out_hook2" "def_r_missile_wing_out2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in1" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in2" "def_r_missile_wing_in1" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in_hook1" "def_r_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_wing_in_hook2" "def_r_missile_wing_in2" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_missile_box" "def_r_missile_leg4" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder_clip1" "def_r_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_holder_clip2" "def_r_holder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_down_missile_doorA1" "def_r_missile_box" -3.012396 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_down_missile_doorB1" "def_r_missile_box" 0.027008 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_down_missile_doorC1" "def_r_missile_box" 3.114403 -15.315048 -4.038809 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_r_up_missile_doorA1" "def_r_missile_box" -3.012396 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_r_up_missile_doorB1" "def_r_missile_box" 0.027047 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_r_up_missile_doorC1" "def_r_missile_box" 3.1146 -15.315048 3.075555 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_down_missile_doorC1" "def_l_missile_box" -3.114389 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_down_missile_doorB1" "def_l_missile_box" -0.026994 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_down_missile_doorA1" "def_l_missile_box" 3.012392 15.315048 4.038964 0 90.000003 179.999978 0 0 0 0 0 0
$definebone "def_l_up_missile_doorC1" "def_l_missile_box" -3.114573 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_up_missile_doorB1" "def_l_missile_box" -0.027032 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_up_missile_doorA1" "def_l_missile_box" 3.012391 15.315048 -3.075454 0 90.000003 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_front_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_side_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_back_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_front_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_side_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_back_up" "def_c_spineC" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_front_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_side_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_waist_back_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_front_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_side_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_waist_back_down" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_knee_up" "def_l_thighLow" 0 0 -0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_l_shock_knee_down" "def_l_knee" 0 -0.000002 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_knee_up" "def_r_thighLow" 0 0 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_r_shock_knee_down" "def_r_knee" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel" "def_l_ankle" 0.000004 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel_shock_start" "def_l_knee" 0 -0.000002 0.000002 0 0 0 0 0 0 0 0 0
$definebone "def_l_heel_shock_end" "def_l_heel" 0.000004 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel" "def_r_ankle" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel_shock_start" "def_r_knee" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_heel_shock_end" "def_r_heel" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_l_ankle_hb" "def_l_ankle" 0.000004 -0.000001 0.000008 0 -54.429153 -90.000003 0 0 0 0 0 0
$definebone "jx_r_ankle_hb" "def_r_ankle" -0.000004 0.000002 0 0 125.570774 -90.000003 0 0 0 0 0 0
$definebone "jx_c_hatch_1_hb" "def_c_spineC" 0.000041 176.631027 -22.913513 -89.999962 0 0 0 0 0 0 0 0
$definebone "jx_c_hatch_2_hb" "jx_c_hatch_1_hb" 40 0 0 0 -20.55604 0 0 0 0 0 0 0
$definebone "jx_c_hatch_3_hb" "jx_c_hatch_2_hb" 42.720016 -0.000031 0 0 -18.103758 0 0 0 0 0 0 0
$definebone "jx_c_hatch_4_hb" "jx_c_hatch_3_hb" 64.031258 0 0 0 -35.394792 0 0 0 0 0 0 0
$definebone "jx_c_hatch_5_hb" "jx_c_hatch_4_hb" 36.400558 0 0 0 -15.945394 0 0 0 0 0 0 0
$definebone "jx_vortex" "def_r_elbow" -22.263123 0.009293 0.000049 -0.000158 -179.99995 -30.000001 0 0 0 0 0 0
$definebone "def_l_battery1" "def_c_spineC" 24.313248 -6.626495 12.072434 -20.247998 -43.921002 -11.247999 0 0 0 0 0 0
$definebone "def_l_battery2" "def_c_spineC" 26.246765 -8.354889 2.264471 -13.127999 -38.161992 -13.077999 0 0 0 0 0 0
$definebone "def_l_battery3" "def_c_spineC" 28.255947 -7.03009 -7.913634 -4.381 -30.610002 -13.026999 0 0 0 0 0 0
$definebone "jx_c_camera_2" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera_3" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0

$bonemerge "def_r_knee"
$bonemerge "def_r_kneeB"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"
$bonemerge "def_r_shock_knee_down"
$bonemerge "def_r_heel_shock_start"
$bonemerge "jx_c_hatch_1_hb"
$bonemerge "jx_c_hatch_2_hb"
$bonemerge "jx_c_hatch_3_hb"
$bonemerge "jx_c_hatch_4_hb"
$bonemerge "jx_c_hatch_5_hb"
$bonemerge "jx_vortex"


$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_thighLow" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position rotation
$bonesaveframe "def_r_ankle" position
$bonesaveframe "def_r_ball" position
$bonesaveframe "def_r_kneeB" position rotation
$bonesaveframe "def_r_finIndexA" position rotation
$bonesaveframe "def_r_finIndexB" position rotation
$bonesaveframe "def_r_finIndexC" position rotation
$bonesaveframe "def_r_finMidA" position rotation
$bonesaveframe "def_r_finMidB" position rotation
$bonesaveframe "def_r_finMidC" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finMidA" position rotation
$bonesaveframe "def_l_finMidB" position rotation
$bonesaveframe "def_l_finMidC" position rotation
$bonesaveframe "def_l_finIndexA" position rotation
$bonesaveframe "def_l_finIndexB" position rotation
$bonesaveframe "def_l_finIndexC" position rotation
$bonesaveframe "ja_l_propHand" position rotation
$bonesaveframe "ja_r_propHand" position rotation
$bonesaveframe "def_l_piston_rear_knee1" position
$bonesaveframe "def_l_piston_rear_knee2" position
$bonesaveframe "def_r_piston_rear_knee1" position
$bonesaveframe "def_l_shock_knee_up" position
$bonesaveframe "def_l_shock_knee_down" position
$bonesaveframe "def_r_shock_knee_down" position rotation
$bonesaveframe "def_l_heel_shock_start" position
$bonesaveframe "def_r_heel" position
$bonesaveframe "def_r_heel_shock_start" position rotation
$bonesaveframe "def_r_heel_shock_end" position
$bonesaveframe "jx_c_hatch_1_hb" rotation
$bonesaveframe "jx_c_hatch_2_hb" rotation
$bonesaveframe "jx_c_hatch_3_hb" rotation
$bonesaveframe "jx_c_hatch_4_hb" rotation
$bonesaveframe "jx_c_hatch_5_hb" rotation
$bonesaveframe "jx_vortex" rotation
$bonesaveframe "def_l_battery1" position rotation
$bonesaveframe "def_l_battery2" position rotation
$bonesaveframe "def_l_battery3" position rotation

$weightlist "weights_head_rot_z" {
	 "jx_c_delta" 0
	 "jx_c_start" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "def_c_spineA" 1
	 "def_c_spineB" 1
	 "def_c_spineC" 1
	 "ja_c_propGun" 1
	 "def_c_intBase" 1
	 "def_c_cam" 1
	 "def_c_neckA" 1
	 "jx_c_neckB" 1
	 "def_c_neckB" 1
	 "def_c_head" 1
	 "def_l_clav" 1
	 "def_l_shoulder" 1
	 "def_l_shoulderMid" 1
	 "def_l_elbow" 1
	 "def_l_wrist" 1
	 "def_l_forearm" 1
	 "def_l_elbowB" 1
	 "def_l_shoulderTwist" 1
	 "def_r_clav" 1
	 "def_r_shoulder" 1
	 "def_r_shoulderMid" 1
	 "def_r_elbow" 1
	 "def_r_wrist" 1
	 "def_r_forearm" 1
	 "def_r_elbowB" 1
	 "def_r_shoulderTwist" 1
	 "def_l_hip" 0
	 "def_l_thigh" 0
	 "def_l_thighLow" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_hip" 0
	 "def_r_thigh" 0
	 "def_r_thighLow" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "def_r_finThumbA" 1
	 "def_r_finThumbB" 1
	 "def_r_finThumbC" 1
	 "def_r_finIndexA" 1
	 "def_r_finIndexB" 1
	 "def_r_finIndexC" 1
	 "def_r_finMidA" 1
	 "def_r_finMidB" 1
	 "def_r_finMidC" 1
	 "def_r_finRingCarpal" 1
	 "def_r_finRingA" 1
	 "def_r_finRingB" 1
	 "def_r_finRingC" 1
	 "def_r_finPinkyA" 1
	 "def_r_finPinkyB" 1
	 "def_r_finPinkyC" 1
	 "def_l_finRingCarpal" 1
	 "def_l_finPinkyA" 1
	 "def_l_finPinkyB" 1
	 "def_l_finPinkyC" 1
	 "def_l_finRingA" 1
	 "def_l_finRingB" 1
	 "def_l_finRingC" 1
	 "def_l_finMidA" 1
	 "def_l_finMidB" 1
	 "def_l_finMidC" 1
	 "def_l_finIndexA" 1
	 "def_l_finIndexB" 1
	 "def_l_finIndexC" 1
	 "def_l_finThumbA" 1
	 "def_l_finThumbB" 1
	 "def_l_finThumbC" 1
	 "ja_l_propHand" 1
	 "ja_r_propHand" 1
	 "def_c_hatchTop" 1
	 "def_c_hatchBot" 1
	 "def_c_hatchHead" 1
	 "def_c_neck1" 1
	 "def_c_eye_rotate" 1
	 "def_c_eye_detached" 1
	 "def_c_eyeball" 1
	 "def_c_eye_outer" 1
	 "def_c_eyelid" 1
	 "def_l_eyelid" 1
	 "def_r_eyelid" 1
	 "def_l_eye_side" 1
	 "def_r_eye_side" 1
	 "def_l_eye_side_cover" 1
	 "def_r_eye_side_cover" 1
	 "def_l_piston_rear_knee1" 0
	 "def_l_piston_rear_knee2" 0
	 "def_r_piston_rear_knee1" 0
	 "def_r_piston_rear_knee2" 0
	 "def_cam_shoulder" 1
	 "def_l_missile_root" 1
	 "def_l_missile_leg1" 1
	 "def_l_missile_leg2" 1
	 "def_l_missile_leg3" 1
	 "def_l_missile_leg4" 1
	 "def_l_missile_wing_out1" 1
	 "def_l_missile_wing_out2" 1
	 "def_l_missile_wing_out_hook1" 1
	 "def_l_missile_wing_out_hook2" 1
	 "def_l_missile_wing_in1" 1
	 "def_l_missile_wing_in2" 1
	 "def_l_missile_wing_in_hook1" 1
	 "def_l_missile_wing_in_hook2" 1
	 "def_l_missile_box" 1
	 "def_l_holder" 1
	 "def_l_holder_clip1" 1
	 "def_l_holder_clip2" 1
	 "def_r_missile_root" 1
	 "def_r_missile_leg1" 1
	 "def_r_missile_leg2" 1
	 "def_r_missile_leg3" 1
	 "def_r_missile_leg4" 1
	 "def_r_missile_wing_out1" 1
	 "def_r_missile_wing_out2" 1
	 "def_r_missile_wing_out_hook1" 1
	 "def_r_missile_wing_out_hook2" 1
	 "def_r_missile_wing_in1" 1
	 "def_r_missile_wing_in2" 1
	 "def_r_missile_wing_in_hook1" 1
	 "def_r_missile_wing_in_hook2" 1
	 "def_r_missile_box" 1
	 "def_r_holder" 1
	 "def_r_holder_clip1" 1
	 "def_r_holder_clip2" 1
	 "def_r_down_missile_doorA1" 1
	 "def_r_down_missile_doorB1" 1
	 "def_r_down_missile_doorC1" 1
	 "def_r_up_missile_doorA1" 1
	 "def_r_up_missile_doorB1" 1
	 "def_r_up_missile_doorC1" 1
	 "def_l_down_missile_doorC1" 1
	 "def_l_down_missile_doorB1" 1
	 "def_l_down_missile_doorA1" 1
	 "def_l_up_missile_doorC1" 1
	 "def_l_up_missile_doorB1" 1
	 "def_l_up_missile_doorA1" 1
	 "def_l_shock_waist_front_up" 1
	 "def_l_shock_waist_side_up" 1
	 "def_l_shock_waist_back_up" 1
	 "def_r_shock_waist_front_up" 1
	 "def_r_shock_waist_side_up" 1
	 "def_r_shock_waist_back_up" 1
	 "def_l_shock_waist_front_down" 0
	 "def_l_shock_waist_side_down" 0
	 "def_l_shock_waist_back_down" 0
	 "def_r_shock_waist_front_down" 0
	 "def_r_shock_waist_side_down" 0
	 "def_r_shock_waist_back_down" 0
	 "def_l_shock_knee_up" 0
	 "def_l_shock_knee_down" 0
	 "def_r_shock_knee_up" 0
	 "def_r_shock_knee_down" 0
	 "def_l_heel" 0
	 "def_l_heel_shock_start" 0
	 "def_l_heel_shock_end" 0
	 "def_r_heel" 0
	 "def_r_heel_shock_start" 0
	 "def_r_heel_shock_end" 0
	 "jx_l_ankle_hb" 0
	 "jx_r_ankle_hb" 0
	 "jx_c_hatch_1_hb" 1
	 "jx_c_hatch_2_hb" 1
	 "jx_c_hatch_3_hb" 1
	 "jx_c_hatch_4_hb" 1
	 "jx_c_hatch_5_hb" 1
	 "jx_vortex" 1
	 "def_l_battery1" 1
	 "def_l_battery2" 1
	 "def_l_battery3" 1
	 "jx_c_camera_2" 0
	 "jx_c_camera_3" 0
}

$weightlist "weights_bt_vortex_arm_pose_add" {
	 "jx_c_delta" 0
	 "jx_c_start" 0
	 "jx_c_pov" 0
	 "jx_c_camera" 0
	 "def_c_hip" 0
	 "def_c_spineA" 0
	 "def_c_spineB" 0
	 "def_c_spineC" 0
	 "ja_c_propGun" 0
	 "def_c_intBase" 0
	 "def_c_cam" 0
	 "def_c_neckA" 0
	 "jx_c_neckB" 0
	 "def_c_neckB" 0
	 "def_c_head" 0
	 "def_l_clav" 0
	 "def_l_shoulder" 0
	 "def_l_shoulderMid" 0
	 "def_l_elbow" 0
	 "def_l_wrist" 0
	 "def_l_forearm" 0
	 "def_l_elbowB" 0
	 "def_l_shoulderTwist" 0
	 "def_r_clav" 1
	 "def_r_shoulder" 1
	 "def_r_shoulderMid" 1
	 "def_r_elbow" 1
	 "def_r_wrist" 1
	 "def_r_forearm" 1
	 "def_r_elbowB" 1
	 "def_r_shoulderTwist" 1
	 "def_l_hip" 0
	 "def_l_thigh" 0
	 "def_l_thighLow" 0
	 "def_l_knee" 0
	 "def_l_ankle" 0
	 "def_l_ball" 0
	 "def_l_kneeB" 0
	 "def_r_hip" 0
	 "def_r_thigh" 0
	 "def_r_thighLow" 0
	 "def_r_knee" 0
	 "def_r_ankle" 0
	 "def_r_ball" 0
	 "def_r_kneeB" 0
	 "def_r_finThumbA" 1
	 "def_r_finThumbB" 1
	 "def_r_finThumbC" 1
	 "def_r_finIndexA" 1
	 "def_r_finIndexB" 1
	 "def_r_finIndexC" 1
	 "def_r_finMidA" 1
	 "def_r_finMidB" 1
	 "def_r_finMidC" 1
	 "def_r_finRingCarpal" 1
	 "def_r_finRingA" 1
	 "def_r_finRingB" 1
	 "def_r_finRingC" 1
	 "def_r_finPinkyA" 1
	 "def_r_finPinkyB" 1
	 "def_r_finPinkyC" 1
	 "def_l_finRingCarpal" 0
	 "def_l_finPinkyA" 0
	 "def_l_finPinkyB" 0
	 "def_l_finPinkyC" 0
	 "def_l_finRingA" 0
	 "def_l_finRingB" 0
	 "def_l_finRingC" 0
	 "def_l_finMidA" 0
	 "def_l_finMidB" 0
	 "def_l_finMidC" 0
	 "def_l_finIndexA" 0
	 "def_l_finIndexB" 0
	 "def_l_finIndexC" 0
	 "def_l_finThumbA" 0
	 "def_l_finThumbB" 0
	 "def_l_finThumbC" 0
	 "ja_l_propHand" 0
	 "ja_r_propHand" 1
	 "def_c_hatchTop" 0
	 "def_c_hatchBot" 0
	 "def_c_hatchHead" 0
	 "def_c_neck1" 0
	 "def_c_eye_rotate" 0
	 "def_c_eye_detached" 0
	 "def_c_eyeball" 0
	 "def_c_eye_outer" 0
	 "def_c_eyelid" 0
	 "def_l_eyelid" 0
	 "def_r_eyelid" 0
	 "def_l_eye_side" 0
	 "def_r_eye_side" 0
	 "def_l_eye_side_cover" 0
	 "def_r_eye_side_cover" 0
	 "def_l_piston_rear_knee1" 0
	 "def_l_piston_rear_knee2" 0
	 "def_r_piston_rear_knee1" 0
	 "def_r_piston_rear_knee2" 0
	 "def_cam_shoulder" 0
	 "def_l_missile_root" 0
	 "def_l_missile_leg1" 0
	 "def_l_missile_leg2" 0
	 "def_l_missile_leg3" 0
	 "def_l_missile_leg4" 0
	 "def_l_missile_wing_out1" 0
	 "def_l_missile_wing_out2" 0
	 "def_l_missile_wing_out_hook1" 0
	 "def_l_missile_wing_out_hook2" 0
	 "def_l_missile_wing_in1" 0
	 "def_l_missile_wing_in2" 0
	 "def_l_missile_wing_in_hook1" 0
	 "def_l_missile_wing_in_hook2" 0
	 "def_l_missile_box" 0
	 "def_l_holder" 0
	 "def_l_holder_clip1" 0
	 "def_l_holder_clip2" 0
	 "def_r_missile_root" 0
	 "def_r_missile_leg1" 0
	 "def_r_missile_leg2" 0
	 "def_r_missile_leg3" 0
	 "def_r_missile_leg4" 0
	 "def_r_missile_wing_out1" 0
	 "def_r_missile_wing_out2" 0
	 "def_r_missile_wing_out_hook1" 0
	 "def_r_missile_wing_out_hook2" 0
	 "def_r_missile_wing_in1" 0
	 "def_r_missile_wing_in2" 0
	 "def_r_missile_wing_in_hook1" 0
	 "def_r_missile_wing_in_hook2" 0
	 "def_r_missile_box" 0
	 "def_r_holder" 0
	 "def_r_holder_clip1" 0
	 "def_r_holder_clip2" 0
	 "def_r_down_missile_doorA1" 0
	 "def_r_down_missile_doorB1" 0
	 "def_r_down_missile_doorC1" 0
	 "def_r_up_missile_doorA1" 0
	 "def_r_up_missile_doorB1" 0
	 "def_r_up_missile_doorC1" 0
	 "def_l_down_missile_doorC1" 0
	 "def_l_down_missile_doorB1" 0
	 "def_l_down_missile_doorA1" 0
	 "def_l_up_missile_doorC1" 0
	 "def_l_up_missile_doorB1" 0
	 "def_l_up_missile_doorA1" 0
	 "def_l_shock_waist_front_up" 0
	 "def_l_shock_waist_side_up" 0
	 "def_l_shock_waist_back_up" 0
	 "def_r_shock_waist_front_up" 0
	 "def_r_shock_waist_side_up" 0
	 "def_r_shock_waist_back_up" 0
	 "def_l_shock_waist_front_down" 0
	 "def_l_shock_waist_side_down" 0
	 "def_l_shock_waist_back_down" 0
	 "def_r_shock_waist_front_down" 0
	 "def_r_shock_waist_side_down" 0
	 "def_r_shock_waist_back_down" 0
	 "def_l_shock_knee_up" 0
	 "def_l_shock_knee_down" 0
	 "def_r_shock_knee_up" 0
	 "def_r_shock_knee_down" 0
	 "def_l_heel" 0
	 "def_l_heel_shock_start" 0
	 "def_l_heel_shock_end" 0
	 "def_r_heel" 0
	 "def_r_heel_shock_start" 0
	 "def_r_heel_shock_end" 0
	 "jx_l_ankle_hb" 0
	 "jx_r_ankle_hb" 0
	 "jx_c_hatch_1_hb" 0
	 "jx_c_hatch_2_hb" 0
	 "jx_c_hatch_3_hb" 0
	 "jx_c_hatch_4_hb" 0
	 "jx_c_hatch_5_hb" 0
	 "jx_vortex" 1
	 "def_l_battery1" 0
	 "def_l_battery2" 0
	 "def_l_battery3" 0
	 "jx_c_camera_2" 0
	 "jx_c_camera_3" 0
}

$animation "a_pose_neutral" "titan_buddy_sp_core_anims\a_pose_neutral.smd" {
	fps 30
}

$animation "a_body_rot" "titan_buddy_sp_core_anims\a_body_rot.smd" {
	fps 30
	noanimation
}

$animation "a_head_rot" "titan_buddy_sp_core_anims\a_head_rot.smd" {
	fps 30
	noanimation
	weightlist "weights_head_rot_z"
}

$animation "a_neck_trans" "titan_buddy_sp_core_anims\a_neck_trans.smd" {
	fps 30
	noanimation
}

$animation "a_head_rot_lt" "titan_buddy_sp_core_anims\a_head_rot_lt.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_head_rot_rt" "titan_buddy_sp_core_anims\a_head_rot_rt.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_neck_trans_fwd" "titan_buddy_sp_core_anims\a_neck_trans_fwd.smd" {
	fps 30
}

$animation "a_neck_trans_back" "titan_buddy_sp_core_anims\a_neck_trans_back.smd" {
	fps 30
}

$animation "a_head_rot_dwn" "titan_buddy_sp_core_anims\a_head_rot_dwn.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_head_rot_up" "titan_buddy_sp_core_anims\a_head_rot_up.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_head_rot_z_rt" "titan_buddy_sp_core_anims\a_head_rot_z_rt.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_head_rot_z_lt" "titan_buddy_sp_core_anims\a_head_rot_z_lt.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_neutral_stand" "titan_buddy_sp_core_anims\a_combat_aim_neutral_stand.smd" {
	fps 30
}

$animation "a_combat_aim_downright_stand" "titan_buddy_sp_core_anims\a_combat_aim_downright_stand.smd" {
	fps 30
}

$animation "a_combat_aim_downcenter_stand" "titan_buddy_sp_core_anims\a_combat_aim_downcenter_stand.smd" {
	fps 30
}

$animation "a_combat_aim_downleft_stand" "titan_buddy_sp_core_anims\a_combat_aim_downleft_stand.smd" {
	fps 30
}

$animation "a_combat_aim_midright_stand" "titan_buddy_sp_core_anims\a_combat_aim_midright_stand.smd" {
	fps 30
}

$animation "a_combat_aim_midcenter_stand" "titan_buddy_sp_core_anims\a_combat_aim_midcenter_stand.smd" {
	fps 30
}

$animation "a_combat_aim_midleft_stand" "titan_buddy_sp_core_anims\a_combat_aim_midleft_stand.smd" {
	fps 30
}

$animation "a_combat_aim_upright_stand" "titan_buddy_sp_core_anims\a_combat_aim_upright_stand.smd" {
	fps 30
}

$animation "a_combat_aim_upcenter_stand" "titan_buddy_sp_core_anims\a_combat_aim_upcenter_stand.smd" {
	fps 30
}

$animation "a_combat_aim_upleft_stand" "titan_buddy_sp_core_anims\a_combat_aim_upleft_stand.smd" {
	fps 30
}

$animation "a_combat_aim_straightup_stand" "titan_buddy_sp_core_anims\a_combat_aim_straightup_stand.smd" {
	fps 30
}

$animation "a_combat_aim_neutral_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_neutral_stand_no_ik.smd" {
	fps 30
}

$animation "a_combat_aim_downright_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_downright_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_downcenter_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_downcenter_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_downleft_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_downleft_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midright_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_midright_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midcenter_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_midcenter_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midleft_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_midleft_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upright_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_upright_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upcenter_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_upcenter_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upleft_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_upleft_stand_no_ik.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_straightup_stand_no_ik" "titan_buddy_sp_core_anims\a_combat_aim_straightup_stand_no_ik.smd" {
	fps 30
}

$animation "a_combat_aim_neutral_run" "titan_buddy_sp_core_anims\a_combat_aim_neutral_run.smd" {
	fps 30
}

$animation "a_combat_aim_downright_run" "titan_buddy_sp_core_anims\a_combat_aim_downright_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_downcenter_run" "titan_buddy_sp_core_anims\a_combat_aim_downcenter_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_downleft_run" "titan_buddy_sp_core_anims\a_combat_aim_downleft_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midright_run" "titan_buddy_sp_core_anims\a_combat_aim_midright_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midcenter_run" "titan_buddy_sp_core_anims\a_combat_aim_midcenter_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_midleft_run" "titan_buddy_sp_core_anims\a_combat_aim_midleft_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upright_run" "titan_buddy_sp_core_anims\a_combat_aim_upright_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upcenter_run" "titan_buddy_sp_core_anims\a_combat_aim_upcenter_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_upleft_run" "titan_buddy_sp_core_anims\a_combat_aim_upleft_run.smd" {
	fps 30
	weightlist "weights_head_rot_z"
}

$animation "a_combat_aim_straightup_run" "titan_buddy_sp_core_anims\a_combat_aim_straightup_run.smd" {
	fps 30
}

$animation "a_vortex_arm_pose" "titan_buddy_sp_core_anims\a_vortex_arm_pose.smd" {
	fps 1
	weightlist "weights_bt_vortex_arm_pose_add"
}

$animation "a_aim_crouch_neutral_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_neutral_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_down_left_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_down_left_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_down_center_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_down_center_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_down_right_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_down_right_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_left_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_mid_left_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_center_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_mid_center_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_mid_right_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_mid_right_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_up_left_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_up_left_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_up_center_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_up_center_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_up_right_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_up_right_2hand.smd" {
	fps 30
}

$animation "a_aim_crouch_straightup_2hand" "titan_buddy_sp_core_anims\a_aim_crouch_straightup_2hand.smd" {
	fps 30
}

$animation "a_walk_center" "titan_buddy_sp_core_anims\a_walk_center.smd" {
	fps 30
}

$animation "a_walk_forward" "titan_buddy_sp_core_anims\a_walk_forward.smd" {
	fps 30
}

$animation "a_walk_right" "titan_buddy_sp_core_anims\a_walk_right.smd" {
	fps 30
}

$animation "a_walk_backward" "titan_buddy_sp_core_anims\a_walk_backward.smd" {
	fps 30
	loop
}

$animation "a_walk_left" "titan_buddy_sp_core_anims\a_walk_left.smd" {
	fps 30
}

$animation "a_run_center" "titan_buddy_sp_core_anims\a_run_center.smd" {
	fps 30
}

$animation "a_run_forward" "titan_buddy_sp_core_anims\a_run_forward.smd" {
	fps 30
}

$animation "a_run_right" "titan_buddy_sp_core_anims\a_run_right.smd" {
	fps 30
}

$animation "a_run_backward" "titan_buddy_sp_core_anims\a_run_backward.smd" {
	fps 30
	loop
}

$animation "a_run_left" "titan_buddy_sp_core_anims\a_run_left.smd" {
	fps 30
}

$animation "a_combat_crouch_idle" "titan_buddy_sp_core_anims\a_combat_crouch_idle.smd" {
	fps 30
	loop
}

$animation "a_stand_2_crouch" "titan_buddy_sp_core_anims\a_stand_2_crouch.smd" {
	fps 30
}

$animation "a_crouch_2_stand" "titan_buddy_sp_core_anims\a_crouch_2_stand.smd" {
	fps 30
}

$animation "a_Fire_Crouch" "titan_buddy_sp_core_anims\a_Fire_Crouch.smd" {
	fps 40
}

$animation "a_shootGeneric" "titan_buddy_sp_core_anims\a_shootGeneric.smd" {
	fps 60
}

$animation "a_reload_additive" "titan_buddy_sp_core_anims\a_reload_additive.smd" {
	fps 50
	weightlist "weights_head_rot_z"
}

$sequence "ref" {
	"titan_buddy_sp_core_anims\ref.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "bt_lookat_matrix" {
	"titan_buddy_sp_core_anims\bt_lookat_matrix.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "head_rot_z" {
	"a_head_rot_z_lt"
	"a_head_rot"
	"a_head_rot_z_rt"
	autoplay
}

$sequence "head_rot_y" {
	"a_head_rot_up"
	"a_head_rot"
	"a_head_rot_dwn"
	autoplay
}

$sequence "head_rot_x" {
	"a_head_rot_lt"
	"a_head_rot"
	"a_head_rot_rt"
	autoplay
}

$sequence "combat_aim_stand" {
	"a_combat_aim_upright_stand"
	"a_combat_aim_upcenter_stand"
	"a_combat_aim_upleft_stand"
	"a_combat_aim_midright_stand"
	"a_combat_aim_midcenter_stand"
	"a_combat_aim_midleft_stand"
	"a_combat_aim_downright_stand"
	"a_combat_aim_downcenter_stand"
	"a_combat_aim_downleft_stand"
}

$sequence "combat_aim_stand_no_ik" {
	"a_combat_aim_upright_stand_no_ik"
	"a_combat_aim_upcenter_stand_no_ik"
	"a_combat_aim_upleft_stand_no_ik"
	"a_combat_aim_midright_stand_no_ik"
	"a_combat_aim_midcenter_stand_no_ik"
	"a_combat_aim_midleft_stand_no_ik"
	"a_combat_aim_downright_stand_no_ik"
	"a_combat_aim_downcenter_stand_no_ik"
	"a_combat_aim_downleft_stand_no_ik"
}

$sequence "combat_aim_run" {
	"a_combat_aim_upright_run"
	"a_combat_aim_upcenter_run"
	"a_combat_aim_upleft_run"
	"a_combat_aim_midright_run"
	"a_combat_aim_midcenter_run"
	"a_combat_aim_midleft_run"
	"a_combat_aim_downright_run"
	"a_combat_aim_downcenter_run"
	"a_combat_aim_downleft_run"
}

$sequence "bt_vortex_arm_pose_add" {
	"a_vortex_arm_pose"
	activity "ACT_MP_OFFHAND_CHARGING" -1
	activitymodifier mp_titanweapon_vortex_shield
	{ event AE_NO_GESTURE_PAIN 0 "" }
	fadein 0.2
	fadeout 0.2
	fps 1
	weightlist "weights_bt_vortex_arm_pose_add"
}

$sequence "bt_vortex_ion_arm_pose_add" {
	"a_vortex_arm_pose"
	activity "ACT_MP_OFFHAND_CHARGING" -1
	activitymodifier mp_titanweapon_vortex_shield_ion
	{ event AE_NO_GESTURE_PAIN 0 "" }
	fadein 0.2
	fadeout 0.2
	fps 1
	weightlist "weights_bt_vortex_arm_pose_add"
}

$sequence "bt_sonar_pulse" {
	"a_vortex_arm_pose"
	activity "ACT_MP_OFFHAND_CHARGING" -1
	activitymodifier mp_titanability_sonar_pulse
	{ event AE_NO_GESTURE_PAIN 0 "" }
	fadein 0.2
	fadeout 0.2
	fps 1
	weightlist "weights_bt_vortex_arm_pose_add"
}

$sequence "crouch_Aim_all" {
	"a_aim_crouch_up_left_2hand"
	"a_aim_crouch_up_center_2hand"
	"a_aim_crouch_up_right_2hand"
	"a_aim_crouch_mid_left_2hand"
	"a_aim_crouch_mid_center_2hand"
	"a_aim_crouch_mid_right_2hand"
	"a_aim_crouch_down_left_2hand"
	"a_aim_crouch_down_center_2hand"
	"a_aim_crouch_down_right_2hand"
}

$sequence "bt_casual_idle" {
	"titan_buddy_sp_core_anims\bt_casual_idle.smd"
	activity "ACT_IDLE_CASUAL" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_casual_idle" }
	fadein 0.2
	fadeout 0.2
	node "idle"
	fps 30
	loop
}

$sequence "bt_casual_idle_turn_45_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_45_left.smd"
	activity "ACT_45_LEFT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 13 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_CL_PLAYSOUND 29 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 43 "" }
	{ event AE_CL_PLAYSOUND 43 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_45_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_45_right.smd"
	activity "ACT_45_RIGHT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 13 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_CL_PLAYSOUND 28 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_90_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_90_left.smd"
	activity "ACT_90_LEFT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 19 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 16 "" }
	{ event AE_CL_PLAYSOUND 16 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 48 "" }
	{ event AE_CL_PLAYSOUND 48 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_90_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_90_right.smd"
	activity "ACT_90_RIGHT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 19 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_CL_PLAYSOUND 16 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 47 "" }
	{ event AE_CL_PLAYSOUND 47 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 55 "" }
	{ event AE_CL_PLAYSOUND 55 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_135_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_135_left.smd"
	activity "ACT_135_LEFT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 9 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 15 "" }
	{ event AE_CL_PLAYSOUND 15 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 47 "" }
	{ event AE_CL_PLAYSOUND 47 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 56 "" }
	{ event AE_CL_PLAYSOUND 56 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_135_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_135_right.smd"
	activity "ACT_135_RIGHT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 9 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_CL_PLAYSOUND 29 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 43 "" }
	{ event AE_CL_PLAYSOUND 43 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_180_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_180_left.smd"
	activity "ACT_180_LEFT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 3 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 44 "" }
	{ event AE_CL_PLAYSOUND 44 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_turn_180_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_turn_180_right.smd"
	activity "ACT_180_RIGHT_NONCOMBAT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 3 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 52 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_CL_PLAYSOUND 38 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 52 "" }
	{ event AE_CL_PLAYSOUND 52 "buddy_shuffle_generic_3p" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_forward" {
	"titan_buddy_sp_core_anims\bt_casual_walk_forward.smd"
	activity "ACT_WALK_CASUAL" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 90 "" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 11 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 28 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 45 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 65 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 81 "buddy_Movement_jog_generic_3p" }
	{ event AE_CL_PLAYSOUND 98 "buddy_Movement_jog_generic_3p" }
	fadein 0.2
	fadeout 0.2
	node "idle"
	fps 30
	loop
}

$sequence "bt_casual_walk_turn_45_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_45_left.smd"
	activity "ACT_WALK_CASUAL_TURN_45_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 58 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_CL_PLAYSOUND 29 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 56 "" }
	{ event AE_CL_PLAYSOUND 56 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_45_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_45_right.smd"
	activity "ACT_WALK_CASUAL_TURN_45_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 72 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 63 "" }
	{ event AE_CL_PLAYSOUND 63 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_90_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_90_left.smd"
	activity "ACT_WALK_CASUAL_TURN_90_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 46 "" }
	{ event AE_FOOTSTEP_L 13 "" }
	{ event AE_CL_PLAYSOUND 13 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 51 "" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_90_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_90_right.smd"
	activity "ACT_WALK_CASUAL_TURN_90_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 35 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 44 "" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 62 "" }
	{ event AE_CL_PLAYSOUND 62 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_135_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_135_left.smd"
	activity "ACT_WALK_CASUAL_TURN_135_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 36 "" }
	{ event AE_FOOTSTEP_L 11 "" }
	{ event AE_CL_PLAYSOUND 11 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 45 "" }
	{ event AE_CL_PLAYSOUND 45 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 64 "" }
	{ event AE_CL_PLAYSOUND 64 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 79 "" }
	{ event AE_CL_PLAYSOUND 79 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_135_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_135_right.smd"
	activity "ACT_WALK_CASUAL_TURN_135_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 36 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 64 "" }
	{ event AE_CL_PLAYSOUND 64 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_180_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_180_left.smd"
	activity "ACT_WALK_CASUAL_TURN_180_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 39 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 63 "" }
	{ event AE_CL_PLAYSOUND 63 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 79 "" }
	{ event AE_CL_PLAYSOUND 79 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_turn_180_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_turn_180_right.smd"
	activity "ACT_WALK_CASUAL_TURN_180_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 39 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_CL_PLAYSOUND 11 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 63 "" }
	{ event AE_CL_PLAYSOUND 63 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_forward" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_forward.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_FORWARD" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_45_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_45_left.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_45_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 43 "" }
	{ event AE_CL_PLAYSOUND 43 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 56 "" }
	{ event AE_CL_PLAYSOUND 56 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_45_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_45_right.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_45_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 58 "" }
	{ event AE_CL_PLAYSOUND 58 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_90_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_90_left.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_90_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 28 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 46 "" }
	{ event AE_CL_PLAYSOUND 46 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 63 "" }
	{ event AE_CL_PLAYSOUND 63 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_90_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_90_right.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_90_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 31 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 39 "" }
	{ event AE_CL_PLAYSOUND 39 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 54 "" }
	{ event AE_CL_PLAYSOUND 54 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 70 "" }
	{ event AE_CL_PLAYSOUND 70 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 77 "" }
	{ event AE_CL_PLAYSOUND 77 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_135_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_135_left.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_135_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 27 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_CL_PLAYSOUND 37 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 54 "" }
	{ event AE_CL_PLAYSOUND 54 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 70 "" }
	{ event AE_CL_PLAYSOUND 70 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 78 "" }
	{ event AE_CL_PLAYSOUND 78 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_135_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_135_right.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_135_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 37 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_CL_PLAYSOUND 37 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 54 "" }
	{ event AE_CL_PLAYSOUND 54 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 68 "" }
	{ event AE_CL_PLAYSOUND 68 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_180_left" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_180_left.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_180_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 46 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 47 "" }
	{ event AE_CL_PLAYSOUND 47 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 61 "" }
	{ event AE_CL_PLAYSOUND 61 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 77 "" }
	{ event AE_CL_PLAYSOUND 77 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_walk_to_idle_180_right" {
	"titan_buddy_sp_core_anims\bt_casual_walk_to_idle_180_right.smd"
	activity "ACT_WALK_CASUAL_TO_STAND_180_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 48 "buddy_movement_casual_turns" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 61 "" }
	{ event AE_CL_PLAYSOUND 61 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_forward_01" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_forward_01.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_FORWARD" 2
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_metal_3p" }
	{ event AE_CL_PLAYSOUND 20 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 37 "" }
	{ event AE_FOOTSTEP_R 35 "" }
	{ event AE_CL_PLAYSOUND 35 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_forward_02" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_forward_02.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_FORWARD" 1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 16 "" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_45_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_45_left.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_45_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 12 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 45 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 47 "" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_CL_PLAYSOUND 29 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 45 "" }
	{ event AE_CL_PLAYSOUND 45 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 65 "" }
	{ event AE_CL_PLAYSOUND 65 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_45_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_45_right.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_45_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 10 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 49 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 59 "" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_CL_PLAYSOUND 29 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_CL_PLAYSOUND 41 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_90_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_90_left.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_90_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 1 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 41 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 51 "" }
	{ event AE_FOOTSTEP_R 15 "" }
	{ event AE_CL_PLAYSOUND 15 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 49 "" }
	{ event AE_CL_PLAYSOUND 49 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 69 "" }
	{ event AE_CL_PLAYSOUND 69 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_90_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_90_right.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_90_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 2 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 56 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 68 "" }
	{ event AE_FOOTSTEP_L 15 "" }
	{ event AE_CL_PLAYSOUND 15 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 47 "" }
	{ event AE_CL_PLAYSOUND 47 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 66 "" }
	{ event AE_CL_PLAYSOUND 66 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 84 "" }
	{ event AE_CL_PLAYSOUND 84 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_135_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_135_left.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_135_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 44 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 75 "" }
	{ event AE_FOOTSTEP_R 15 "" }
	{ event AE_CL_PLAYSOUND 15 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 47 "" }
	{ event AE_CL_PLAYSOUND 47 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 56 "" }
	{ event AE_CL_PLAYSOUND 56 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 73 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 91 "" }
	{ event AE_CL_PLAYSOUND 91 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_135_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_135_right.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_135_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 8 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 63 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 72 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_CL_PLAYSOUND 29 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 43 "" }
	{ event AE_CL_PLAYSOUND 43 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 70 "" }
	{ event AE_CL_PLAYSOUND 70 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 88 "" }
	{ event AE_CL_PLAYSOUND 88 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_180_left" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_180_left.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_180_LEFT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 57 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 72 "" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 44 "" }
	{ event AE_CL_PLAYSOUND 44 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 70 "" }
	{ event AE_CL_PLAYSOUND 70 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 88 "" }
	{ event AE_CL_PLAYSOUND 88 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_casual_idle_to_walk_180_right" {
	"titan_buddy_sp_core_anims\bt_casual_idle_to_walk_180_right.smd"
	activity "ACT_STAND_TO_WALK_CASUAL_180_RIGHT" -1
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "buddy_movement_casual_turns" }
	{ event AE_CL_PLAYSOUND 65 "buddy_Movement_generic_3p" }
	{ event AE_NPC_PATH_ALIGN 78 "" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_CL_PLAYSOUND 25 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_CL_PLAYSOUND 38 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 52 "" }
	{ event AE_CL_PLAYSOUND 52 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 76 "" }
	{ event AE_CL_PLAYSOUND 76 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 94 "" }
	{ event AE_CL_PLAYSOUND 94 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	node "idle"
	fps 30
}

$sequence "bt_alert_idle" {
	"titan_buddy_sp_core_anims\bt_alert_idle.smd"
	activity "ACT_IDLE" -1
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_combat_idle" }
	{ event AE_FOOTSTEP_R 518 "" }
	{ event AE_CL_PLAYSOUND 518 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 786 "" }
	{ event AE_CL_PLAYSOUND 786 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 800 "" }
	{ event AE_CL_PLAYSOUND 800 "buddy_shuffle_generic_3p" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	fps 30
	loop
}

$sequence "bt_combat_idle" {
	"titan_buddy_sp_core_anims\bt_combat_idle.smd"
	activity "ACT_IDLE_COMBAT" -1
	{ event AE_CL_PLAYSOUND 0 "buddy_Movement_combat_idle" }
	{ event AE_FOOTSTEP_R 518 "" }
	{ event AE_CL_PLAYSOUND 518 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_R 786 "" }
	{ event AE_CL_PLAYSOUND 786 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 800 "" }
	{ event AE_CL_PLAYSOUND 800 "buddy_shuffle_generic_3p" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	fps 30
	loop
}

$sequence "bt_combat_idle_turn_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_45_left.smd"
	activity "ACT_45_LEFT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 2 "exo_hip" }
	{ event AE_CL_PLAYSOUND 7 "exo_knee" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 19 "" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_45_right.smd"
	activity "ACT_45_RIGHT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_90_left.smd"
	activity "ACT_90_LEFT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 2 "exo_hip" }
	{ event AE_CL_PLAYSOUND 7 "exo_knee" }
	{ event AE_CL_PLAYSOUND 8 "exo_hip" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_CL_PLAYSOUND 29 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_90_right.smd"
	activity "ACT_90_RIGHT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_FOOTSTEP_R 6 "" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_CL_PLAYSOUND 29 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_135_left.smd"
	activity "ACT_135_LEFT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 14 "exo_hip" }
	{ event AE_FOOTSTEP_R 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_135_right.smd"
	activity "ACT_135_RIGHT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 14 "exo_hip" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 27 "" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_180_left.smd"
	activity "ACT_180_LEFT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 14 "exo_hip" }
	{ event AE_FOOTSTEP_R 6 "" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 38 "" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_turn_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_turn_180_right.smd"
	activity "ACT_180_RIGHT" -1
	{ event AE_CL_PLAYSOUND 2 "exo_servo" }
	{ event AE_CL_PLAYSOUND 14 "exo_hip" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 17 "" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Jog.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_walk_all_directions" {
	"a_walk_backward"
	"a_walk_right"
	"a_walk_forward"
	"a_walk_left"
	"a_walk_backward"
	activity "ACT_WALK_AIM" -1
}

$sequence "bt_combat_walk_forward" {
	"titan_buddy_sp_core_anims\bt_combat_walk_forward.smd"
	activity "ACT_WALK_AIM_FORWARD" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_CL_PLAYSOUND 41 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 90 "" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_backward" {
	"titan_buddy_sp_core_anims\bt_combat_walk_backward.smd"
	activity "ACT_WALK_AIM_BACKWARD" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 49 "" }
	{ event AE_CL_PLAYSOUND 49 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 59 "" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_left.smd"
	activity "ACT_WALK_AIM_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 56 "" }
	{ event AE_CL_PLAYSOUND 56 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 90 "" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_right.smd"
	activity "ACT_WALK_AIM_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 4 "" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 55 "" }
	{ event AE_CL_PLAYSOUND 55 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 72 "" }
	{ event AE_CL_PLAYSOUND 72 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 87 "" }
	{ event AE_CL_PLAYSOUND 87 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 93 "" }
	{ event AE_CL_PLAYSOUND 93 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 109 "" }
	{ event AE_CL_PLAYSOUND 109 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_forward_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_walk_forward_noaim.smd"
	activity "ACT_WALK" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_CL_PLAYSOUND 41 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 90 "" }
	{ event AE_CL_PLAYSOUND 90 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_walk_turn_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_45_left.smd"
	activity "ACT_WALK_TURN_45_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 58 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_FOOTSTEP_L 47 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_45_right.smd"
	activity "ACT_WALK_TURN_45_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 72 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 27 "" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_FOOTSTEP_L 63 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_90_left.smd"
	activity "ACT_WALK_TURN_90_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 46 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_FOOTSTEP_L 51 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_90_right.smd"
	activity "ACT_WALK_TURN_90_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 35 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_FOOTSTEP_R 44 "" }
	{ event AE_FOOTSTEP_L 61 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_135_left.smd"
	activity "ACT_WALK_TURN_135_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 36 "" }
	{ event AE_FOOTSTEP_L 11 "" }
	{ event AE_FOOTSTEP_R 27 "" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_FOOTSTEP_R 63 "" }
	{ event AE_FOOTSTEP_L 78 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_135_right.smd"
	activity "ACT_WALK_TURN_135_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 36 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_FOOTSTEP_L 63 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_180_left.smd"
	activity "ACT_WALK_TURN_180_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 39 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_FOOTSTEP_R 63 "" }
	{ event AE_FOOTSTEP_L 79 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_turn_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_turn_180_right.smd"
	activity "ACT_WALK_TURN_180_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 39 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_FOOTSTEP_L 63 "" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_walk_to_idle_forward" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_forward.smd"
	activity "ACT_WALK_TO_STAND_FORWARD" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_CL_PLAYSOUND 8 "exo_knee" }
	{ event AE_CL_PLAYSOUND 17 "exo_servo" }
	{ event AE_CL_PLAYSOUND 24 "exo_hip" }
	{ event AE_CL_PLAYSOUND 29 "exo_knee" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_forward" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_CL_PLAYSOUND 24 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_CL_PLAYSOUND 33 "buddy_shuffle_generic_3p" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_45_left.smd"
	activity "ACT_WALK_TO_STAND_45_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_45" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 40 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_45_right.smd"
	activity "ACT_WALK_TO_STAND_45_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_45" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_FOOTSTEP_R 45 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_90_left.smd"
	activity "ACT_WALK_TO_STAND_90_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_90" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_FOOTSTEP_R 49 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_90_right.smd"
	activity "ACT_WALK_TO_STAND_90_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_90" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_FOOTSTEP_R 56 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_135_left.smd"
	activity "ACT_WALK_TO_STAND_135_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_135" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_R 35 "" }
	{ event AE_FOOTSTEP_L 45 "" }
	{ event AE_FOOTSTEP_R 53 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_135_right.smd"
	activity "ACT_WALK_TO_STAND_135_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_135" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_FOOTSTEP_L 49 "" }
	{ event AE_FOOTSTEP_R 54 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_180_left.smd"
	activity "ACT_WALK_TO_STAND_180_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_180" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_L 45 "" }
	{ event AE_FOOTSTEP_R 53 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_walk_to_idle_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_walk_to_idle_180_right.smd"
	activity "ACT_WALK_TO_STAND_180_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_to_idle_180" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_R 33 "" }
	{ event AE_FOOTSTEP_L 45 "" }
	{ event AE_FOOTSTEP_R 53 "" }
	fadein 0.4
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_forward" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_forward.smd"
	activity "ACT_STAND_TO_WALK_FORWARD" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 1 "exo_servo" }
	{ event AE_NPC_PATH_ALIGN 13 "" }
	{ event AE_CL_PLAYSOUND 13 "exo_hip" }
	{ event AE_CL_PLAYSOUND 22 "exo_knee" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "buddy_shuffle_generic_3p" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Jog.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_forward" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_45_left" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_45_left.smd"
	activity "ACT_STAND_TO_WALK_45_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_45" }
	{ event AE_FOOTSTEP_L 15 "" }
	{ event AE_FOOTSTEP_R 27 "" }
	{ event AE_FOOTSTEP_L 44 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_45_right" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_45_right.smd"
	activity "ACT_STAND_TO_WALK_45_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_45" }
	{ event AE_FOOTSTEP_L 15 "" }
	{ event AE_FOOTSTEP_R 26 "" }
	{ event AE_FOOTSTEP_L 43 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_90_left" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_90_left.smd"
	activity "ACT_STAND_TO_WALK_90_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_90" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_FOOTSTEP_L 54 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_90_right" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_90_right.smd"
	activity "ACT_STAND_TO_WALK_90_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_90" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_FOOTSTEP_L 53 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_135_left" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_135_left.smd"
	activity "ACT_STAND_TO_WALK_135_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_135" }
	{ event AE_FOOTSTEP_R 10 "" }
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_FOOTSTEP_L 53 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_135_right" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_135_right.smd"
	activity "ACT_STAND_TO_WALK_135_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_135" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_FOOTSTEP_L 53 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_180_left" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_180_left.smd"
	activity "ACT_STAND_TO_WALK_180_LEFT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_180" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_FOOTSTEP_R 40 "" }
	{ event AE_FOOTSTEP_L 56 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_alert_idle_to_walk_180_right" {
	"titan_buddy_sp_core_anims\bt_alert_idle_to_walk_180_right.smd"
	activity "ACT_STAND_TO_WALK_180_RIGHT" -1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_alert_idle_to_walk_180" }
	{ event AE_FOOTSTEP_L 17 "" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_FOOTSTEP_R 34 "" }
	{ event AE_FOOTSTEP_L 51 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_all_directions" {
	"a_run_backward"
	"a_run_right"
	"a_run_forward"
	"a_run_left"
	"a_run_backward"
	activity "ACT_RUN_AIM" -1
}

$sequence "bt_combat_run_forward" {
	"titan_buddy_sp_core_anims\bt_combat_run_forward.smd"
	activity "ACT_RUN_AIM_FORWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_run_backward" {
	"titan_buddy_sp_core_anims\bt_combat_run_backward.smd"
	activity "ACT_RUN_AIM_BACKWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 68 "" }
	{ event AE_CL_PLAYSOUND 68 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 99 "" }
	{ event AE_CL_PLAYSOUND 99 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_run_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_left.smd"
	activity "ACT_RUN_AIM_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 86 "" }
	{ event AE_CL_PLAYSOUND 86 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_run_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_right.smd"
	activity "ACT_RUN_AIM_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_run_forward_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_run_forward_noaim.smd"
	activity "ACT_RUN" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_CL_PLAYSOUND 33 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 45 "" }
	{ event AE_CL_PLAYSOUND 45 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 70 "" }
	{ event AE_CL_PLAYSOUND 70 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_run_forward_noaim_dupe" {
	"titan_buddy_sp_core_anims\bt_combat_run_forward_noaim_dupe.smd"
	activity "ACT_RUN_FORWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_CL_PLAYSOUND 33 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 45 "" }
	{ event AE_CL_PLAYSOUND 45 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 70 "" }
	{ event AE_CL_PLAYSOUND 70 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_run_backward_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_run_backward_noaim.smd"
	activity "ACT_RUN_BACKWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 68 "" }
	{ event AE_CL_PLAYSOUND 68 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 99 "" }
	{ event AE_CL_PLAYSOUND 99 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_run_left_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_run_left_noaim.smd"
	activity "ACT_RUN_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 86 "" }
	{ event AE_CL_PLAYSOUND 86 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_run_right_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_run_right_noaim.smd"
	activity "ACT_RUN_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_sprint_forward_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_sprint_forward_noaim.smd"
	activity "ACT_SPRINT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_sprint_forward_noaim_dupe" {
	"titan_buddy_sp_core_anims\bt_combat_sprint_forward_noaim_dupe.smd"
	activity "ACT_SPRINT_FORWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_sprint_backward_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_sprint_backward_noaim.smd"
	activity "ACT_SPRINT_BACKWARD" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 68 "" }
	{ event AE_CL_PLAYSOUND 68 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 78 "" }
	{ event AE_CL_PLAYSOUND 78 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 99 "" }
	{ event AE_CL_PLAYSOUND 99 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_sprint_left_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_sprint_left_noaim.smd"
	activity "ACT_SPRINT_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_L 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 53 "" }
	{ event AE_CL_PLAYSOUND 53 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 86 "" }
	{ event AE_CL_PLAYSOUND 86 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_sprint_right_noaim" {
	"titan_buddy_sp_core_anims\bt_combat_sprint_right_noaim.smd"
	activity "ACT_SPRINT_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "exo_hip" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_CL_PLAYSOUND 44 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 66 "" }
	{ event AE_CL_PLAYSOUND 66 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 73 "" }
	{ event AE_CL_PLAYSOUND 73 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 85 "" }
	{ event AE_CL_PLAYSOUND 85 "Buddy.Sprint.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "bt_combat_run_turn_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_45_left.smd"
	activity "ACT_RUN_TURN_45_LEFT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 36 "" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_45" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_45_right.smd"
	activity "ACT_RUN_TURN_45_RIGHT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 44 "" }
	{ event AE_FOOTSTEP_R 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_45" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_90_left.smd"
	activity "ACT_RUN_TURN_90_LEFT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 21 "" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_90" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_90_right.smd"
	activity "ACT_RUN_TURN_90_RIGHT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 26 "" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_90" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_135_left.smd"
	activity "ACT_RUN_TURN_135_LEFT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 29 "" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_CL_PLAYSOUND 19 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 51 "" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_135" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_135_right.smd"
	activity "ACT_RUN_TURN_135_RIGHT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 30 "" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_135" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_180_left.smd"
	activity "ACT_RUN_TURN_180_LEFT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 29 "" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 41 "" }
	{ event AE_CL_PLAYSOUND 41 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 47 "" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 62 "" }
	{ event AE_CL_PLAYSOUND 62 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 75 "" }
	{ event AE_CL_PLAYSOUND 75 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_180" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_turn_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_turn_180_right.smd"
	activity "ACT_RUN_TURN_180_RIGHT" -1
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 30 "" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_turn_180" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_run_to_idle_forward" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_forward.smd"
	activity "ACT_RUN_TO_STAND_FORWARD" -1
	{ event AE_CL_PLAYSOUND 1 "exo_hip" }
	{ event AE_CL_PLAYSOUND 8 "exo_knee" }
	{ event AE_CL_PLAYSOUND 14 "exo_servo" }
	{ event AE_CL_PLAYSOUND 18 "exo_hip" }
	{ event AE_CL_PLAYSOUND 28 "exo_knee" }
	{ event AE_FOOTSTEP_L 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_CL_PLAYSOUND 13 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_forward" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_45_left.smd"
	activity "ACT_RUN_TO_STAND_45_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_45" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 29 "" }
	{ event AE_FOOTSTEP_R 33 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_45_right.smd"
	activity "ACT_RUN_TO_STAND_45_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_45" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_FOOTSTEP_R 35 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_90_left.smd"
	activity "ACT_RUN_TO_STAND_90_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_90" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_FOOTSTEP_R 39 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_90_right.smd"
	activity "ACT_RUN_TO_STAND_90_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_90" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_FOOTSTEP_R 42 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_135_left.smd"
	activity "ACT_RUN_TO_STAND_135_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_135" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_FOOTSTEP_L 35 "" }
	{ event AE_FOOTSTEP_R 43 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_135_right.smd"
	activity "ACT_RUN_TO_STAND_135_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_135" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_R 23 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 41 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_180_left.smd"
	activity "ACT_RUN_TO_STAND_180_LEFT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_180" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 44 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_run_to_idle_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_run_to_idle_180_right.smd"
	activity "ACT_RUN_TO_STAND_180_RIGHT" -1
	{ event AE_CL_PLAYSOUND 0 "bt_combat_run_to_idle_180" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_FOOTSTEP_R 39 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_forward" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_forward.smd"
	activity "ACT_STAND_TO_RUN_FORWARD" -1
	{ event AE_CL_PLAYSOUND 1 "exo_servo" }
	{ event AE_CL_PLAYSOUND 8 "exo_hip" }
	{ event AE_CL_PLAYSOUND 22 "exo_knee" }
	{ event AE_NPC_PATH_ALIGN 24 "" }
	{ event AE_FOOTSTEP_R 17 "" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_idle_to_run_forward" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_45_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_45_left.smd"
	activity "ACT_STAND_TO_RUN_45_LEFT" -1
	{ event AE_FOOTSTEP_L 14 "" }
	{ event AE_FOOTSTEP_L 24 "" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_FOOTSTEP_L 47 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_45_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_45_right.smd"
	activity "ACT_STAND_TO_RUN_45_RIGHT" -1
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_FOOTSTEP_L 46 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_90_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_90_left.smd"
	activity "ACT_STAND_TO_RUN_90_LEFT" -1
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 41 "" }
	{ event AE_FOOTSTEP_L 59 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_90_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_90_right.smd"
	activity "ACT_STAND_TO_RUN_90_RIGHT" -1
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_FOOTSTEP_L 56 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_135_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_135_left.smd"
	activity "ACT_STAND_TO_RUN_135_LEFT" -1
	{ event AE_FOOTSTEP_L 19 "" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_FOOTSTEP_R 41 "" }
	{ event AE_FOOTSTEP_L 60 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_135_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_135_right.smd"
	activity "ACT_STAND_TO_RUN_135_RIGHT" -1
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_FOOTSTEP_L 30 "" }
	{ event AE_FOOTSTEP_R 35 "" }
	{ event AE_FOOTSTEP_L 53 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_180_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_180_left.smd"
	activity "ACT_STAND_TO_RUN_180_LEFT" -1
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 41 "" }
	{ event AE_FOOTSTEP_L 60 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_combat_idle_to_run_180_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_run_180_right.smd"
	activity "ACT_STAND_TO_RUN_180_RIGHT" -1
	{ event AE_FOOTSTEP_L 17 "" }
	{ event AE_FOOTSTEP_L 28 "" }
	{ event AE_FOOTSTEP_R 33 "" }
	{ event AE_FOOTSTEP_L 52 "" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "at_CrouchIdle" {
	"a_combat_crouch_idle"
	activity "ACT_CROUCHIDLE_SCAN" 1
	fadein 0.2
	fadeout 0.2
	node "crouch"
	fps 30
	loop
}

$sequence "at_Crouch_Aim" {
	"a_combat_crouch_idle"
	activity "ACT_CROUCHIDLE_AIM" 1
	fadein 0.2
	fadeout 0.2
	addlayer "crouch_Aim_all"
	node "crouch"
	fps 30
	loop
}

$sequence "at_crouchturn_90L" {
	"titan_buddy_sp_core_anims\at_crouchturn_90L.smd"
	activity "ACT_90_LEFT_CROUCH" 1
	{ event AE_FOOTSTEP_L 4 "Crouch" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 8 "exo_knee" }
	{ event AE_FOOTSTEP_R 11 "Crouch" }
	{ event AE_CL_PLAYSOUND 11 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "Crouch" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_crouchturn_90R" {
	"titan_buddy_sp_core_anims\at_crouchturn_90R.smd"
	activity "ACT_90_RIGHT_CROUCH" 1
	{ event AE_FOOTSTEP_L 4 "Crouch" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 8 "exo_knee" }
	{ event AE_FOOTSTEP_R 11 "Crouch" }
	{ event AE_CL_PLAYSOUND 11 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 22 "Crouch" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_crouchturn_180_fast" {
	"titan_buddy_sp_core_anims\at_crouchturn_180_fast.smd"
	activity "ACT_180_LEFT_CROUCH" 1
	{ event AE_CL_PLAYSOUND 3 "exo_servo" }
	{ event AE_FOOTSTEP_R 18 "Crouch" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 22 "exo_knee" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_crouchturn_180_slow" {
	"titan_buddy_sp_core_anims\at_crouchturn_180_slow.smd"
	activity "ACT_180_RIGHT_CROUCH" 1
	{ event AE_FOOTSTEP_R 3 "Crouch" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 9 "exo_servo" }
	{ event AE_FOOTSTEP_L 18 "Crouch" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "Crouch" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Crouch.Generic_3P" }
	{ event AE_CL_PLAYSOUND 32 "exo_knee" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_stand_2_crouch_act" {
	"a_stand_2_crouch"
	activity "ACT_CROUCH" -1
	{ event AE_FOOTSTEP_L 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 35 "" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Jog.Generic_3P" }
	{ event AE_NPC_SET_STANCE 27 "crouch" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_crouch_2_stand_act" {
	"a_crouch_2_stand"
	activity "ACT_STAND" -1
	{ event AE_FOOTSTEP_L 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 22 "" }
	{ event AE_CL_PLAYSOUND 22 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_CL_PLAYSOUND 36 "Buddy.Jog.Generic_3P" }
	{ event AE_NPC_SET_STANCE 9 "stand" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_run_2_crouch_F" {
	"titan_buddy_sp_core_anims\at_run_2_crouch_F.smd"
	activity "ACT_RUN_TO_CROUCH_FORWARD" -1
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_run_2_crouch_45L" {
	"titan_buddy_sp_core_anims\at_run_2_crouch_45L.smd"
	activity "ACT_RUN_TO_CROUCH_45_LEFT" -1
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_run_2_crouch_45R" {
	"titan_buddy_sp_core_anims\at_run_2_crouch_45R.smd"
	activity "ACT_RUN_TO_CROUCH_45_RIGHT" -1
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_run_2_crouch_90R" {
	"titan_buddy_sp_core_anims\at_run_2_crouch_90R.smd"
	activity "ACT_RUN_TO_CROUCH_90_RIGHT" -1
	{ event AE_NPC_SET_STANCE 10 "crouch" }
	{ event AE_FOOTSTEP_L 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Crouch.Generic_3P" }
	{ event AE_FOOTSTEP_R 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Crouch.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "at_crouch_2_run_90L" {
	"titan_buddy_sp_core_anims\at_crouch_2_run_90L.smd"
	activity "ACT_CROUCH_TO_RUN_90_LEFT" -1
	{ event AE_NPC_SET_STANCE 15 "stand" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 45 "" }
	{ event AE_CL_PLAYSOUND 45 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 80 "" }
	{ event AE_CL_PLAYSOUND 80 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "bt_combat_idle_to_strafe_left" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_strafe_left.smd"
	activity "ACT_STAND_TO_STRAFE_LEFT" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_PATH_ALIGN 31 "" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 38 "" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_idle_to_strafe_left" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_to_strafe_right" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_strafe_right.smd"
	activity "ACT_STAND_TO_STRAFE_RIGHT" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_PATH_ALIGN 26 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 16 "" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 35 "" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_idle_to_strafe_left" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_combat_idle_to_backpedal" {
	"titan_buddy_sp_core_anims\bt_combat_idle_to_backpedal.smd"
	activity "ACT_STAND_TO_BACKPEDAL" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_PATH_ALIGN 26 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 17 "" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 33 "" }
	{ event AE_CL_PLAYSOUND 33 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_idle_to_backpedal" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_strafe_left_to_combat_idle" {
	"titan_buddy_sp_core_anims\bt_strafe_left_to_combat_idle.smd"
	activity "ACT_STRAFE_TO_STAND_LEFT" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_FOOTSTEP_L 1 "" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 13 "" }
	{ event AE_CL_PLAYSOUND 13 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 17 "" }
	{ event AE_CL_PLAYSOUND 17 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_CL_PLAYSOUND 36 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_strafe_right_to_combat_idle" {
	"titan_buddy_sp_core_anims\bt_strafe_right_to_combat_idle.smd"
	activity "ACT_STRAFE_TO_STAND_RIGHT" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_FOOTSTEP_R 1 "" }
	{ event AE_CL_PLAYSOUND 1 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 21 "" }
	{ event AE_CL_PLAYSOUND 21 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_backpedal_to_combat_idle" {
	"titan_buddy_sp_core_anims\bt_backpedal_to_combat_idle.smd"
	activity "ACT_STRAFE_TO_STAND_BACKPEDAL" -1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 20 "" }
	{ event AE_CL_PLAYSOUND 20 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_backpedal_to_combat" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_weapon_draw_01" {
	"titan_buddy_sp_core_anims\bt_weapon_draw_01.smd"
	activity "ACT_TRANSITION" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_CL_PLAYSOUND 0 "bt_weapon_draw" }
	{ event AE_NPC_ENEMY_ALIGN 33 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 44 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 45 "" }
	{ event AE_FOOTSTEP_L 38 "" }
	{ event AE_CL_PLAYSOUND 38 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	transition "idle" "default"
	fps 30
}

$sequence "bt_weapon_stow" {
	"titan_buddy_sp_core_anims\bt_weapon_stow.smd"
	activity "ACT_TRANSITION" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_LOOKAT_PLAYER 0 "" }
	{ event AE_CL_PLAYSOUND 0 "bt_weapon_stow" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 83 "" }
	{ event AE_CL_PLAYSOUND 83 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 110 "" }
	{ event AE_CL_PLAYSOUND 110 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	transition "default" "idle"
	fps 30
}

$sequence "bt_fire_single" {
	"titan_buddy_sp_core_anims\bt_fire_single.smd"
	activity "ACT_RANGE_ATTACK1_SINGLE" 1
	{ event AE_CL_PLAYSOUND 3 "exo_hip" }
	{ event AE_CL_PLAYSOUND 7 "exo_elbow" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	fps 30
}

$sequence "bt_fire_kickup" {
	"titan_buddy_sp_core_anims\bt_fire_kickup.smd"
	activity "ACT_RANGE_ATTACK1_SINGLE" 1
	{ event AE_CL_PLAYSOUND 6 "exo_knee" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	fps 30
}

$sequence "bt_fire_knockback" {
	"titan_buddy_sp_core_anims\bt_fire_knockback.smd"
	activity "ACT_RANGE_ATTACK1_SINGLE" 1
	{ event AE_CL_PLAYSOUND 3 "exo_elbow" }
	{ event AE_CL_PLAYSOUND 14 "exo_hip" }
	{ event AE_FOOTSTEP_L 22 "" }
	{ event AE_CL_PLAYSOUND 22 "" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "" }
	{ event AE_CL_PLAYSOUND 37 "exo_servo" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_fire_stand" {
	"titan_buddy_sp_core_anims\bt_fire_stand.smd"
	activity "ACT_RANGE_ATTACK1" -1
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand"
	fps 30
}

$sequence "bt_evade_fire_left" {
	"titan_buddy_sp_core_anims\bt_evade_fire_left.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 1
	{ event AE_NPC_SHOOT_OVERLAY_ON 0 "" }
	{ event AE_FOOTSTEP_R 4 "" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 51 "" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 59 "" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_evade_fire_right" {
	"titan_buddy_sp_core_anims\bt_evade_fire_right.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 1
	{ event AE_NPC_SHOOT_OVERLAY_ON 0 "" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 57 "" }
	{ event AE_CL_PLAYSOUND 57 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 61 "" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_evade_fire_forward" {
	"titan_buddy_sp_core_anims\bt_evade_fire_forward.smd"
	activity "ACT_RANGE_ATTACK1_EVASIVE" 1
	{ event AE_NPC_SHOOT_OVERLAY_ON 0 "" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 56 "" }
	{ event AE_CL_PLAYSOUND 56 "Buddy.Jog.Generic_3P" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_fire_crouch" {
	"a_Fire_Crouch"
	activity "ACT_RANGE_ATTACK1_LOW" -1
	{ event AE_CL_PLAYSOUND 1 "exo_elbow" }
	fadein 0.2
	fadeout 0.2
	addlayer "crouch_Aim_all"
	fps 40
}

$sequence "bt_fire_crouch_single" {
	"a_Fire_Crouch"
	activity "ACT_RANGE_ATTACK1_LOW_SINGLE" -1
	{ event AE_CL_PLAYSOUND 1 "exo_elbow" }
	fadein 0.2
	fadeout 0.2
	addlayer "crouch_Aim_all"
	fps 40
}

$sequence "bt_fire_additive" {
	"a_shootGeneric"
	activity "ACT_GESTURE_RANGE_ATTACK1" -1
	delta
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "bt_fire_grenade" {
	"titan_buddy_sp_core_anims\bt_fire_grenade.smd"
	activity "ACT_RANGE_ATTACK2" -1
	{ event AE_GRENADE_THROW 1 "" }
	{ event AE_CL_PLAYSOUND 26 "exo_footstep_small" }
	{ event AE_CL_PLAYSOUND 1 "exo_servo" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "bt_stand_reload_01" {
	"titan_buddy_sp_core_anims\bt_stand_reload_01.smd"
	activity "ACT_RELOAD" 1
	{ event AE_NPC_WEAPON_RELOAD 39 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 47 "" }
	{ event AE_CL_PLAYSOUND 0 "bt_stand_reload_01" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_stand_reload_02" {
	"titan_buddy_sp_core_anims\bt_stand_reload_02.smd"
	activity "ACT_RELOAD" 1
	{ event AE_NPC_WEAPON_RELOAD 38 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 41 "" }
	{ event AE_CL_PLAYSOUND 0 "bt_stand_reload_02" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "a_crouch_reload_low" {
	"titan_buddy_sp_core_anims\a_crouch_reload_low.smd"
	activity "ACT_RELOAD_LOW" 1
	{ event AE_NPC_WEAPON_RELOAD 3 "" }
	{ event AE_CL_PLAYSOUND 0 "Titan_3P_Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "a_crouch_reload_high" {
	"titan_buddy_sp_core_anims\a_crouch_reload_high.smd"
	activity "ACT_RELOAD_LOW" 1
	{ event AE_NPC_WEAPON_RELOAD 3 "" }
	{ event AE_CL_PLAYSOUND 0 "Titan_3P_Reload" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "bt_reload_additive" {
	"a_reload_additive"
	activity "ACT_GESTURE_RELOAD" -1
	delta
	{ event AE_NPC_WEAPON_RELOAD 18 "" }
	{ event AE_CL_PLAYSOUND 0 "Titan_3P_Reload" }
	fadein 0.2
	fadeout 0.2
	fps 50
	weightlist "weights_head_rot_z"
}

$sequence "bt_reload_dodge_left_01" {
	"titan_buddy_sp_core_anims\bt_reload_dodge_left_01.smd"
	activity "ACT_RELOAD_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_WEAPON_RELOAD 35 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 44 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 44 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_reload_dodge_left_01" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_FOOTSTEP_R 26 "" }
	{ event AE_FOOTSTEP_L 38 "" }
	{ event AE_FOOTSTEP_R 45 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_reload_dodge_left_02" {
	"titan_buddy_sp_core_anims\bt_reload_dodge_left_02.smd"
	activity "ACT_RELOAD_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_WEAPON_RELOAD 42 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 45 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 44 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_reload_dodge_left_02" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 15 "" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_FOOTSTEP_L 39 "" }
	{ event AE_FOOTSTEP_R 49 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_reload_dodge_left_03" {
	"titan_buddy_sp_core_anims\bt_reload_dodge_left_03.smd"
	activity "ACT_RELOAD_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_WEAPON_RELOAD 30 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 41 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 44 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_reload_dodge_left_03" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_FOOTSTEP_L 11 "" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_FOOTSTEP_R 47 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_reload_dodge_right_01" {
	"titan_buddy_sp_core_anims\bt_reload_dodge_right_01.smd"
	activity "ACT_RELOAD_DODGE_RIGHT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_WEAPON_RELOAD 38 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 43 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 44 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_reload_dodge_right_01" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_FOOTSTEP_R 33 "" }
	{ event AE_FOOTSTEP_L 44 "" }
	{ event AE_FOOTSTEP_R 51 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_reload_dodge_right_02" {
	"titan_buddy_sp_core_anims\bt_reload_dodge_right_02.smd"
	activity "ACT_RELOAD_DODGE_RIGHT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_WEAPON_RELOAD 31 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 35 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 44 "xo_atlas_jet_large" }
	{ event AE_CL_PLAYSOUND 0 "bt_reload_dodge_right_02" }
	{ event AE_FOOTSTEP_L 6 "" }
	{ event AE_FOOTSTEP_R 11 "" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_FOOTSTEP_L 45 "" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_forward_01" {
	"titan_buddy_sp_core_anims\bt_dash_forward_01.smd"
	activity "ACT_DODGE_FORWARD" 1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 16 "" }
	{ event AE_NPC_PATH_ALIGN 22 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 25 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 36 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 37 "0" }
	{ event AE_FOOTSTEP_R 4 "" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 43 "" }
	{ event AE_CL_PLAYSOUND 43 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 51 "" }
	{ event AE_CL_PLAYSOUND 51 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 60 "" }
	{ event AE_CL_PLAYSOUND 60 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_forward_01" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_forward_02" {
	"titan_buddy_sp_core_anims\bt_dash_forward_02.smd"
	activity "ACT_DODGE_FORWARD" 1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 16 "" }
	{ event AE_NPC_PATH_ALIGN 22 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 25 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 36 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 37 "0" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 23 "" }
	{ event AE_CL_PLAYSOUND 23 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 49 "" }
	{ event AE_CL_PLAYSOUND 49 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 54 "" }
	{ event AE_CL_PLAYSOUND 54 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_forward_02" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_backward_01" {
	"titan_buddy_sp_core_anims\bt_dash_backward_01.smd"
	activity "ACT_DODGE_BACKWARD" 1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 13 "" }
	{ event AE_NPC_PATH_ALIGN 22 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 26 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 40 "0" }
	{ event AE_FOOTSTEP_L 6 "" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 24 "" }
	{ event AE_CL_PLAYSOUND 24 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 42 "" }
	{ event AE_CL_PLAYSOUND 42 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 52 "" }
	{ event AE_CL_PLAYSOUND 52 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_backward_01" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_backward_02" {
	"titan_buddy_sp_core_anims\bt_dash_backward_02.smd"
	activity "ACT_DODGE_BACKWARD" 1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 13 "" }
	{ event AE_NPC_PATH_ALIGN 22 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 26 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 30 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 40 "0" }
	{ event AE_FOOTSTEP_R 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 49 "" }
	{ event AE_CL_PLAYSOUND 49 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_backward_02" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_left" {
	"titan_buddy_sp_core_anims\bt_dash_left.smd"
	activity "ACT_DODGE_LEFT_FAR" -1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 6 "" }
	{ event AE_NPC_PATH_ALIGN 27 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 37 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 40 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 26 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 38 "0" }
	{ event AE_FOOTSTEP_R 0 "" }
	{ event AE_CL_PLAYSOUND 0 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 35 "" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 48 "" }
	{ event AE_CL_PLAYSOUND 48 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_left" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dash_right" {
	"titan_buddy_sp_core_anims\bt_dash_right.smd"
	activity "ACT_DODGE_RIGHT_FAR" -1
	{ event AE_LOCK_ANIM_DELTA_YAW 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 1 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 6 "" }
	{ event AE_NPC_PATH_ALIGN 27 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 34 "" }
	{ event AE_NPC_TEST_ANIM_PATH_ENDPOS 40 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 26 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 38 "0" }
	{ event AE_FOOTSTEP_L 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 50 "" }
	{ event AE_CL_PLAYSOUND 50 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 59 "" }
	{ event AE_CL_PLAYSOUND 59 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dash_right" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_left_01" {
	"titan_buddy_sp_core_anims\bt_dodge_left_01.smd"
	activity "ACT_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 24 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_CL_PLAYSOUND 36 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_01" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_left_02" {
	"titan_buddy_sp_core_anims\bt_dodge_left_02.smd"
	activity "ACT_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 19 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 28 "" }
	{ event AE_CL_PLAYSOUND 28 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 33 "" }
	{ event AE_CL_PLAYSOUND 33 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_02" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_left_03" {
	"titan_buddy_sp_core_anims\bt_dodge_left_03.smd"
	activity "ACT_DODGE_LEFT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 21 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 27 "" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_03" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_left_04" {
	"titan_buddy_sp_core_anims\bt_dodge_left_04.smd"
	activity "ACT_DODGE_LEFT" 2
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 30 "" }
	{ event AE_NPC_ENEMY_ALIGN 31 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 41 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 4 "" }
	{ event AE_CL_PLAYSOUND 4 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 18 "" }
	{ event AE_CL_PLAYSOUND 18 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 46 "" }
	{ event AE_CL_PLAYSOUND 46 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_04" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_right_01" {
	"titan_buddy_sp_core_anims\bt_dodge_right_01.smd"
	activity "ACT_DODGE_RIGHT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 22 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 27 "" }
	{ event AE_CL_PLAYSOUND 27 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 32 "" }
	{ event AE_CL_PLAYSOUND 32 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 40 "" }
	{ event AE_CL_PLAYSOUND 40 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_01" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_right_02" {
	"titan_buddy_sp_core_anims\bt_dodge_right_02.smd"
	activity "ACT_DODGE_RIGHT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 33 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_L 6 "" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 8 "" }
	{ event AE_CL_PLAYSOUND 8 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_02" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_right_03" {
	"titan_buddy_sp_core_anims\bt_dodge_right_03.smd"
	activity "ACT_DODGE_RIGHT" 2
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_ENEMY_ALIGN 22 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 26 "" }
	{ event AE_NPC_ENEMY_ALIGN_OFF 33 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 6 "" }
	{ event AE_CL_PLAYSOUND 6 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 16 "" }
	{ event AE_CL_PLAYSOUND 16 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 26 "" }
	{ event AE_CL_PLAYSOUND 26 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 34 "" }
	{ event AE_CL_PLAYSOUND 34 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 37 "" }
	{ event AE_CL_PLAYSOUND 37 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 47 "" }
	{ event AE_CL_PLAYSOUND 47 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_03" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_dodge_right_04" {
	"titan_buddy_sp_core_anims\bt_dodge_right_04.smd"
	activity "ACT_DODGE_RIGHT" 1
	{ event AE_NO_GESTURE_PAIN 0 "" }
	{ event AE_NPC_SHOOT_OVERLAY_ON 18 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_L 5 "" }
	{ event AE_CL_PLAYSOUND 5 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 25 "" }
	{ event AE_CL_PLAYSOUND 25 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 29 "" }
	{ event AE_CL_PLAYSOUND 29 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 39 "" }
	{ event AE_CL_PLAYSOUND 39 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 45 "" }
	{ event AE_CL_PLAYSOUND 45 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_dodge_left_04" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_stand_no_ik"
	fps 30
}

$sequence "bt_run_dodge_left" {
	"titan_buddy_sp_core_anims\bt_run_dodge_left.smd"
	activity "ACT_DODGE_LEFT_RUN" -1
	{ event AE_NPC_SHOOT_OVERLAY_ON 22 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_R 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 14 "" }
	{ event AE_CL_PLAYSOUND 14 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 36 "" }
	{ event AE_CL_PLAYSOUND 36 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 50 "" }
	{ event AE_CL_PLAYSOUND 50 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_run_dodge_left" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_run_dodge_right" {
	"titan_buddy_sp_core_anims\bt_run_dodge_right.smd"
	activity "ACT_DODGE_RIGHT_RUN" -1
	{ event AE_NPC_SHOOT_OVERLAY_ON 22 "" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_right" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment vent_left" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 1 "xo_atlas_jet_large follow_attachment THRUST" }
	{ event AE_CL_DODGE_GROUND_EFFECT 2 "1" }
	{ event AE_CL_STOP_PARTICLE_EFFECT 21 "xo_atlas_jet_large" }
	{ event AE_CL_DODGE_GROUND_EFFECT 24 "0" }
	{ event AE_FOOTSTEP_L 7 "" }
	{ event AE_CL_PLAYSOUND 7 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 12 "" }
	{ event AE_CL_PLAYSOUND 12 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Sprint.Generic_3P" }
	{ event AE_FOOTSTEP_L 35 "" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Sprint.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_run_dodge_left" }
	fadein 0.3
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
}

$sequence "bt_traverse_down_128" {
	"titan_buddy_sp_core_anims\bt_traverse_down_128.smd"
	activity "ACT_TRAVERSE_DOWN_128" -1
	{ event AE_NPC_START_ADJUST_POS 23 "9" }
	{ event AE_ENABLE_PLANTING 34 "" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 31 "" }
	{ event AE_CL_PLAYSOUND 31 "buddy_land_generic_scripted_3p" }
	{ event AE_FOOTSTEP_R 32 "" }
	fadein 0.3
	fadeout 0.3
	node "notransition"
	fps 30
}

$sequence "bt_traverse_down_256" {
	"titan_buddy_sp_core_anims\bt_traverse_down_256.smd"
	activity "ACT_TRAVERSE_DOWN_256" -1
	{ event AE_NPC_START_ADJUST_POS 22 "16" }
	{ event AE_ENABLE_PLANTING 39 "" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 36 "" }
	{ event AE_CL_PLAYSOUND 36 "buddy_land_generic_scripted_3p" }
	{ event AE_FOOTSTEP_R 37 "" }
	fadein 0.3
	fadeout 0.3
	node "notransition"
	fps 30
}

$sequence "bt_traverse_down_640" {
	"titan_buddy_sp_core_anims\bt_traverse_down_640.smd"
	activity "ACT_TRAVERSE_DOWN_640" -1
	{ event AE_NPC_START_ADJUST_POS 23 "18" }
	{ event AE_ENABLE_PLANTING 44 "" }
	{ event AE_FOOTSTEP_L 3 "" }
	{ event AE_CL_PLAYSOUND 3 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 41 "" }
	{ event AE_CL_PLAYSOUND 41 "buddy_land_generic_scripted_3p" }
	{ event AE_FOOTSTEP_R 42 "" }
	fadein 0.3
	fadeout 0.3
	node "notransition"
	fps 30
}

$sequence "bt_combat_walk_stumble_01" {
	"titan_buddy_sp_core_anims\bt_combat_walk_stumble_01.smd"
	activity "ACT_WALK_STUMBLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 31 "" }
	{ event AE_CL_PLAYSOUND 31 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 52 "" }
	{ event AE_CL_PLAYSOUND 52 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 76 "" }
	{ event AE_CL_PLAYSOUND 76 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 94 "" }
	{ event AE_CL_PLAYSOUND 94 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 116 "" }
	{ event AE_CL_PLAYSOUND 116 "Buddy.Jog.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_stumble_01" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_stumble_02" {
	"titan_buddy_sp_core_anims\bt_combat_walk_stumble_02.smd"
	activity "ACT_WALK_STUMBLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_FOOTSTEP_L 10 "" }
	{ event AE_CL_PLAYSOUND 10 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 35 "" }
	{ event AE_CL_PLAYSOUND 35 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 61 "" }
	{ event AE_CL_PLAYSOUND 61 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 67 "" }
	{ event AE_CL_PLAYSOUND 67 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 91 "" }
	{ event AE_CL_PLAYSOUND 91 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 113 "" }
	{ event AE_CL_PLAYSOUND 113 "Buddy.Jog.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_stumble_02" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}

$sequence "bt_combat_walk_stumble_03" {
	"titan_buddy_sp_core_anims\bt_combat_walk_stumble_03.smd"
	activity "ACT_WALK_STUMBLE" 1
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "xo_atlas_jet_large" }
	{ event AE_FOOTSTEP_L 9 "" }
	{ event AE_CL_PLAYSOUND 9 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 30 "" }
	{ event AE_CL_PLAYSOUND 30 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 55 "" }
	{ event AE_CL_PLAYSOUND 55 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 67 "" }
	{ event AE_CL_PLAYSOUND 67 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_L 82 "" }
	{ event AE_CL_PLAYSOUND 82 "Buddy.Jog.Generic_3P" }
	{ event AE_FOOTSTEP_R 94 "" }
	{ event AE_CL_PLAYSOUND 94 "Buddy.Jog.Generic_3P" }
	{ event AE_CL_PLAYSOUND 0 "bt_combat_walk_stumble_03" }
	fadein 0.2
	fadeout 0.2
	addlayer "combat_aim_run"
	fps 30
	loop
}
