// Created by Crowbar 0.71

$modelname "Weapons/arms/pov_pete_core.mdl"

$surfaceprop "default"

$jointsurfaceprop "jx_c_delta" ""
$jointsurfaceprop "jx_c_pov" ""
$jointsurfaceprop "jx_c_camera" ""
$jointsurfaceprop "def_c_hip" ""
$jointsurfaceprop "jx_c_start" ""
$jointsurfaceprop "def_c_spineA" ""
$jointsurfaceprop "def_c_spineB" ""
$jointsurfaceprop "def_c_spineC" ""
$jointsurfaceprop "ja_c_propGun" ""
$jointsurfaceprop "def_c_neckA" ""
$jointsurfaceprop "jx_c_neckB" ""
$jointsurfaceprop "def_c_neckB" ""
$jointsurfaceprop "def_c_head" ""
$jointsurfaceprop "def_l_clav" ""
$jointsurfaceprop "def_l_shoulder" ""
$jointsurfaceprop "def_l_shoulderTwist" ""
$jointsurfaceprop "def_l_elbowB" ""
$jointsurfaceprop "def_l_shoulderMid" ""
$jointsurfaceprop "def_l_elbow" ""
$jointsurfaceprop "def_l_forearm" ""
$jointsurfaceprop "def_l_wrist" ""
$jointsurfaceprop "def_l_finIndexA" ""
$jointsurfaceprop "def_l_finIndexB" ""
$jointsurfaceprop "def_l_finIndexC" ""
$jointsurfaceprop "def_l_finMidA" ""
$jointsurfaceprop "def_l_finMidB" ""
$jointsurfaceprop "def_l_finMidC" ""
$jointsurfaceprop "def_l_finThumbA" ""
$jointsurfaceprop "def_l_finThumbB" ""
$jointsurfaceprop "def_l_finThumbC" ""
$jointsurfaceprop "def_l_finRingCarpal" ""
$jointsurfaceprop "def_l_finRingA" ""
$jointsurfaceprop "def_l_finRingB" ""
$jointsurfaceprop "def_l_finRingC" ""
$jointsurfaceprop "def_l_finPinkyA" ""
$jointsurfaceprop "def_l_finPinkyB" ""
$jointsurfaceprop "def_l_finPinkyC" ""
$jointsurfaceprop "def_r_clav" ""
$jointsurfaceprop "def_r_shoulder" ""
$jointsurfaceprop "def_r_shoulderTwist" ""
$jointsurfaceprop "def_r_elbowB" ""
$jointsurfaceprop "def_r_shoulderMid" ""
$jointsurfaceprop "def_r_elbow" ""
$jointsurfaceprop "def_r_forearm" ""
$jointsurfaceprop "def_r_wrist" ""
$jointsurfaceprop "def_r_finIndexA" ""
$jointsurfaceprop "def_r_finIndexB" ""
$jointsurfaceprop "def_r_finIndexC" ""
$jointsurfaceprop "def_r_finMidA" ""
$jointsurfaceprop "def_r_finMidB" ""
$jointsurfaceprop "def_r_finMidC" ""
$jointsurfaceprop "def_r_finThumbA" ""
$jointsurfaceprop "def_r_finThumbB" ""
$jointsurfaceprop "def_r_finThumbC" ""
$jointsurfaceprop "def_r_finRingCarpal" ""
$jointsurfaceprop "def_r_finRingA" ""
$jointsurfaceprop "def_r_finRingB" ""
$jointsurfaceprop "def_r_finRingC" ""
$jointsurfaceprop "def_r_finPinkyA" ""
$jointsurfaceprop "def_r_finPinkyB" ""
$jointsurfaceprop "def_r_finPinkyC" ""
$jointsurfaceprop "def_l_thigh" ""
$jointsurfaceprop "def_l_knee" ""
$jointsurfaceprop "def_l_ankle" ""
$jointsurfaceprop "def_l_ball" ""
$jointsurfaceprop "def_l_kneeB" ""
$jointsurfaceprop "def_r_thigh" ""
$jointsurfaceprop "def_r_knee" ""
$jointsurfaceprop "def_r_ankle" ""
$jointsurfaceprop "def_r_ball" ""
$jointsurfaceprop "def_r_kneeB" ""
$jointsurfaceprop "ja_l_propHand" ""
$jointsurfaceprop "ja_r_propHand" ""
$jointsurfaceprop "def_l_cable1" ""
$jointsurfaceprop "def_l_cable2" ""
$jointsurfaceprop "def_l_cable3" ""
$jointsurfaceprop "def_l_cable4" ""
$jointsurfaceprop "def_l_cable5" ""
$jointsurfaceprop "def_l_cable6" ""
$jointsurfaceprop "def_ts_wheel" ""
$jointsurfaceprop "def_l_strap_link" ""
$jointsurfaceprop "def_l_strap1" ""
$jointsurfaceprop "def_l_strap2" ""
$jointsurfaceprop "def_l_strap3" ""
$jointsurfaceprop "def_l_strap4" ""
$jointsurfaceprop "def_l_band1" ""
$jointsurfaceprop "def_l_band2" ""
$jointsurfaceprop "jx_c_origin" ""

$contents "solid"

$jointcontents "jx_c_delta" "notsolid"
$jointcontents "jx_c_pov" "notsolid"
$jointcontents "jx_c_camera" "notsolid"
$jointcontents "def_c_hip" "notsolid"
$jointcontents "jx_c_start" "notsolid"
$jointcontents "def_c_spineA" "notsolid"
$jointcontents "def_c_spineB" "notsolid"
$jointcontents "def_c_spineC" "notsolid"
$jointcontents "ja_c_propGun" "notsolid"
$jointcontents "def_c_neckA" "notsolid"
$jointcontents "jx_c_neckB" "notsolid"
$jointcontents "def_c_neckB" "notsolid"
$jointcontents "def_c_head" "notsolid"
$jointcontents "def_l_clav" "notsolid"
$jointcontents "def_l_shoulder" "notsolid"
$jointcontents "def_l_shoulderTwist" "notsolid"
$jointcontents "def_l_elbowB" "notsolid"
$jointcontents "def_l_shoulderMid" "notsolid"
$jointcontents "def_l_elbow" "notsolid"
$jointcontents "def_l_forearm" "notsolid"
$jointcontents "def_l_wrist" "notsolid"
$jointcontents "def_l_finIndexA" "notsolid"
$jointcontents "def_l_finIndexB" "notsolid"
$jointcontents "def_l_finIndexC" "notsolid"
$jointcontents "def_l_finMidA" "notsolid"
$jointcontents "def_l_finMidB" "notsolid"
$jointcontents "def_l_finMidC" "notsolid"
$jointcontents "def_l_finThumbA" "notsolid"
$jointcontents "def_l_finThumbB" "notsolid"
$jointcontents "def_l_finThumbC" "notsolid"
$jointcontents "def_l_finRingCarpal" "notsolid"
$jointcontents "def_l_finRingA" "notsolid"
$jointcontents "def_l_finRingB" "notsolid"
$jointcontents "def_l_finRingC" "notsolid"
$jointcontents "def_l_finPinkyA" "notsolid"
$jointcontents "def_l_finPinkyB" "notsolid"
$jointcontents "def_l_finPinkyC" "notsolid"
$jointcontents "def_r_clav" "notsolid"
$jointcontents "def_r_shoulder" "notsolid"
$jointcontents "def_r_shoulderTwist" "notsolid"
$jointcontents "def_r_elbowB" "notsolid"
$jointcontents "def_r_shoulderMid" "notsolid"
$jointcontents "def_r_elbow" "notsolid"
$jointcontents "def_r_forearm" "notsolid"
$jointcontents "def_r_wrist" "notsolid"
$jointcontents "def_r_finIndexA" "notsolid"
$jointcontents "def_r_finIndexB" "notsolid"
$jointcontents "def_r_finIndexC" "notsolid"
$jointcontents "def_r_finMidA" "notsolid"
$jointcontents "def_r_finMidB" "notsolid"
$jointcontents "def_r_finMidC" "notsolid"
$jointcontents "def_r_finThumbA" "notsolid"
$jointcontents "def_r_finThumbB" "notsolid"
$jointcontents "def_r_finThumbC" "notsolid"
$jointcontents "def_r_finRingCarpal" "notsolid"
$jointcontents "def_r_finRingA" "notsolid"
$jointcontents "def_r_finRingB" "notsolid"
$jointcontents "def_r_finRingC" "notsolid"
$jointcontents "def_r_finPinkyA" "notsolid"
$jointcontents "def_r_finPinkyB" "notsolid"
$jointcontents "def_r_finPinkyC" "notsolid"
$jointcontents "def_l_thigh" "notsolid"
$jointcontents "def_l_knee" "notsolid"
$jointcontents "def_l_ankle" "notsolid"
$jointcontents "def_l_ball" "notsolid"
$jointcontents "def_l_kneeB" "notsolid"
$jointcontents "def_r_thigh" "notsolid"
$jointcontents "def_r_knee" "notsolid"
$jointcontents "def_r_ankle" "notsolid"
$jointcontents "def_r_ball" "notsolid"
$jointcontents "def_r_kneeB" "notsolid"
$jointcontents "ja_l_propHand" "notsolid"
$jointcontents "ja_r_propHand" "notsolid"
$jointcontents "def_l_cable1" "notsolid"
$jointcontents "def_l_cable2" "notsolid"
$jointcontents "def_l_cable3" "notsolid"
$jointcontents "def_l_cable4" "notsolid"
$jointcontents "def_l_cable5" "notsolid"
$jointcontents "def_l_cable6" "notsolid"
$jointcontents "def_ts_wheel" "notsolid"
$jointcontents "def_l_strap_link" "notsolid"
$jointcontents "def_l_strap1" "notsolid"
$jointcontents "def_l_strap2" "notsolid"
$jointcontents "def_l_strap3" "notsolid"
$jointcontents "def_l_strap4" "notsolid"
$jointcontents "def_l_band1" "notsolid"
$jointcontents "def_l_band2" "notsolid"
$jointcontents "jx_c_origin" "notsolid"

$illumposition 0 -1.676 53.371

$cdmaterials ""

$attachment "KNIFE" "ja_r_propHand" 0 0 0 rotate -90 -90 0

$cbox 0 0 0 0 0 0

$bbox -6.315 -22.898 -0.339 9.667 22.898 71.5

$hboxset "default"
$hbox 1 "def_c_head" -2.389365 -6.197625 0.915353 2.389365 -0.738975 4.97125 ""
$hbox 1 "def_c_head" -2.191334 -1.288186 3.938969 2.191334 2.88149 6.08109 ""
$hbox 1 "def_c_head" -2.443696 -3.336608 -5.300383 2.443696 2.54842 -3.845268 ""
$hbox 1 "def_c_head" -2.804325 1.687792 -2.713381 2.804325 4.177157 3.911803 ""
$hbox 1 "def_c_head" -3.917709 -3.348025 -3.852355 3.917709 2.550782 3.933457 ""
$hbox 1 "def_c_head" -2.069287 -6.102744 4.963376 2.069287 -2.68779 6.2055 ""
$hbox 2 "def_c_neckA" -3.599599 0.33307 -4.669676 3.599599 4.963769 3.804717 ""
$hbox 2 "def_c_spineC" -7.513371 0.003543 -6.315342 7.513371 8.838566 6.079122 ""
$hbox 3 "def_c_hip" -7.513371 -7.049199 -6.197232 7.513371 0.000394 6.197232 ""
$hbox 3 "def_c_spineA" -7.513371 0 -6.197232 7.513371 5.59054 6.197232 ""
$hbox 3 "def_c_spineB" -7.513371 0 -6.197232 7.513371 5.55117 6.197232 ""
$hbox 4 "def_l_shoulder" -2.066138 -2.014563 -2.835034 11.231867 2.014563 2.835034 ""
$hbox 4 "def_l_elbow" -1.651965 -1.791335 -1.64606 9.750375 1.791335 1.64606 ""
$hbox 4 "def_l_wrist" -0.291732 -1.342123 -1.670075 3.675583 0.581495 1.894484 ""
$hbox 5 "def_r_shoulder" -11.215726 -2.014563 -2.835034 2.081886 2.014563 2.835034 ""
$hbox 5 "def_r_elbow" -9.74998 -1.791335 -1.64606 1.651965 1.791335 1.64606 ""
$hbox 5 "def_r_wrist" -3.675583 -0.581495 -1.894484 0.291732 1.342123 1.670075 ""
$hbox 6 "def_l_thigh" 0 -2.208657 -3.148813 18.097996 4.371645 3.148813 ""
$hbox 6 "def_l_knee" 0 -2.686215 -3.148813 17.311777 2.686215 3.148813 ""
$hbox 6 "def_l_ankle" -2.103145 -1.918107 -2.531885 3.188576 1.918107 2.531885 ""
$hbox 6 "def_l_ball" -1.637005 -0.124016 -2.520074 3.419285 2.612987 2.520074 ""
$hbox 7 "def_r_thigh" -18.097996 -4.371251 -3.148813 0 2.208657 3.148813 ""
$hbox 7 "def_r_knee" -17.311777 -2.686215 -3.148813 0 2.686215 3.148813 ""
$hbox 7 "def_r_ankle" -3.188576 -1.918107 -2.531885 2.103145 1.918107 2.531885 ""
$hbox 7 "def_r_ball" -3.418891 -2.615349 -2.520074 1.636611 0.121653 2.520074 ""
$skipboneinbbox

$screenalign def_l_clav "sphere"
$screenalign def_l_shoulderTwist "sphere"
$screenalign def_l_elbowB "sphere"
$screenalign def_l_shoulderMid "sphere"
$screenalign def_l_elbow "cylinder"
$screenalign def_l_wrist "sphere"
$screenalign def_l_finIndexA "cylinder"
$screenalign def_l_finIndexB "sphere"
$screenalign def_l_finMidA "sphere"
$screenalign def_l_finMidB "cylinder"
$screenalign def_l_finMidC "cylinder"
$screenalign def_l_finThumbA "cylinder"
$screenalign def_l_finThumbC "sphere"
$screenalign def_l_finRingCarpal "sphere"
$screenalign def_l_finRingB "sphere"
$screenalign def_l_finRingC "sphere"
$screenalign def_l_finPinkyA "cylinder"
$screenalign def_l_finPinkyB "cylinder"
$screenalign def_l_finPinkyC "cylinder"
$screenalign def_r_clav "sphere"
$screenalign def_r_shoulderMid "sphere"
$screenalign def_r_elbow "sphere"
$screenalign def_r_wrist "sphere"
$screenalign def_r_finIndexA "sphere"
$screenalign def_r_finIndexB "sphere"
$screenalign def_r_finIndexC "cylinder"
$screenalign def_r_finMidA "sphere"
$screenalign def_r_finMidB "sphere"
$screenalign def_r_finMidC "sphere"
$screenalign def_r_finThumbA "cylinder"
$screenalign def_r_finThumbC "cylinder"
$screenalign def_r_finRingCarpal "cylinder"
$screenalign def_r_finRingA "sphere"
$screenalign def_r_finPinkyA "sphere"
$screenalign def_r_finPinkyB "sphere"
$screenalign def_r_finPinkyC "sphere"
$screenalign def_l_thigh "sphere"
$screenalign def_l_knee "sphere"
$screenalign def_l_ankle "sphere"
$screenalign def_l_ball "sphere"
$screenalign def_l_kneeB "sphere"
$screenalign def_r_thigh "sphere"
$screenalign def_r_ankle "cylinder"
$screenalign def_r_kneeB "sphere"
$screenalign ja_l_propHand "cylinder"
$screenalign ja_r_propHand "sphere"
$screenalign def_l_cable1 "cylinder"
$screenalign def_l_cable2 "cylinder"
$screenalign def_l_cable3 "sphere"
$screenalign def_l_cable4 "sphere"
$screenalign def_l_cable5 "cylinder"
$screenalign def_l_cable6 "cylinder"
$screenalign def_ts_wheel "cylinder"
$screenalign def_l_strap_link "sphere"
$screenalign def_l_strap1 "sphere"
$screenalign def_l_strap2 "sphere"

$definebone "jx_c_delta" "" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_pov" "jx_c_delta" 0 62.992001 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_camera" "jx_c_pov" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_hip" "jx_c_delta" 0 39.369999 0 0 0 0 0 0 0 0 0 0
$definebone "jx_c_start" "jx_c_delta" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineA" "def_c_hip" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineB" "def_c_spineA" 0 5.590542 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_spineC" "def_c_spineB" 0 5.55117 0 0 0 0 0 0 0 0 0 0
$definebone "ja_c_propGun" "def_c_spineC" 0 -7.204712 9.8425 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckA" "def_c_spineC" 0 8.503922 -0.23622 0 0 0 0 0 0 0 0 0
$definebone "jx_c_neckB" "def_c_neckA" 0 4.370071 0.94488 0 0 0 0 0 0 0 0 0
$definebone "def_c_neckB" "jx_c_neckB" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_c_head" "def_c_neckB" 0 3.936996 0 0 0 0 0 0 0 0 0 0
$definebone "def_l_clav" "def_c_spineC" 1.176218 6.023808 -0.588109 6.983374 3.661928 0.44582 0 0 0 0 0 0
$definebone "def_l_shoulder" "def_l_clav" 5.448854 0.000011 0 -4.860232 -48.915267 4.890265 0 0 0 0 0 0
$definebone "def_l_shoulderTwist" "def_l_shoulder" 0 0 0 0 0.000002 0 0 0 0 0 0 0
$definebone "def_l_elbowB" "def_l_shoulder" 11.630213 -0.000008 0.000027 -44.997331 -0.027096 0.877916 0 0 0 0 0 0
$definebone "def_l_shoulderMid" "def_l_shoulder" 4.890762 0.000004 0 -2.688722 -0.057131 0.006099 0 0 0 0 0 0
$definebone "def_l_elbow" "def_l_shoulderMid" 6.444214 -0.000004 0 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_l_forearm" "def_l_elbow" 4.63045 0.000011 0.000002 -5.291108 -0.116958 0.007797 0 0 0 0 0 0
$definebone "def_l_wrist" "def_l_elbow" 9.956749 -0.010864 0.493276 -5.403714 -0.039456 -0.000075 0 0 0 0 0 0
$definebone "def_l_finIndexA" "def_l_wrist" 3.077315 -0.138939 1.24732 -3.532782 -45.109219 3.539624 0 0 0 0 0 0
$definebone "def_l_finIndexB" "def_l_finIndexA" 1.748371 0 0.000002 -0.001187 -45.000005 0.001192 0 0 0 0 0 0
$definebone "def_l_finIndexC" "def_l_finIndexB" 1.19545 -0.000003 0.000002 0.000615 -45.000008 -0.000614 0 0 0 0 0 0
$definebone "def_l_finMidA" "def_l_wrist" 3.080781 -0.067951 0.349253 6.351203 -45.354918 -6.390478 0 0 0 0 0 0
$definebone "def_l_finMidB" "def_l_finMidA" 1.836349 0.000002 0.000002 0.000002 -45.000005 0.000002 0 0 0 0 0 0
$definebone "def_l_finMidC" "def_l_finMidB" 1.309196 -0.000001 0.000008 -0.002988 -45.000008 0.00298 0 0 0 0 0 0
$definebone "def_l_finThumbA" "def_l_wrist" 0.504171 -0.563503 0.770155 -42.349748 -57.483275 126.990511 0 0 0 0 0 0
$definebone "def_l_finThumbB" "def_l_finThumbA" 2.132282 0.000006 0.000004 3.259416 -22.647167 2.460338 0 0 0 0 0 0
$definebone "def_l_finThumbC" "def_l_finThumbB" 1.240841 -0.000003 0 0.074487 -45.185656 0.008913 0 0 0 0 0 0
$definebone "def_l_finRingCarpal" "def_l_wrist" 2.513066 -0.138184 -0.333538 17.995868 0.000025 0.000075 0 0 0 0 0 0
$definebone "def_l_finRingA" "def_l_finRingCarpal" 0.316793 0.000004 -0.000001 0.003163 -44.999994 -0.003168 0 0 0 0 0 0
$definebone "def_l_finRingB" "def_l_finRingA" 1.966316 0.000002 -0.000002 0.000002 -45.000001 0.000001 0 0 0 0 0 0
$definebone "def_l_finRingC" "def_l_finRingB" 1.00687 0.000001 0.000008 0.000598 -45.000008 -0.000594 0 0 0 0 0 0
$definebone "def_l_finPinkyA" "def_l_finRingCarpal" -0.030562 -0.172359 -0.590865 18.727351 -48.299806 -19.816788 0 0 0 0 0 0
$definebone "def_l_finPinkyB" "def_l_finPinkyA" 1.644444 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_l_finPinkyC" "def_l_finPinkyB" 0.763287 -0.000002 0 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_clav" "def_c_spineC" -1.176218 6.024002 -0.588109 -6.983374 -3.661928 -179.554171 0 0 0 0 0 0
$definebone "def_r_shoulder" "def_r_clav" -5.448845 0.000145 0 -4.860235 -48.915264 4.890268 0 0 0 0 0 0
$definebone "def_r_shoulderTwist" "def_r_shoulder" 0 0 0 0 0 0 0 0 0 0 0 0
$definebone "def_r_elbowB" "def_r_shoulder" -11.630196 0.000011 -0.000028 -44.997327 -0.027091 0.877916 0 0 0 0 0 0
$definebone "def_r_shoulderMid" "def_r_shoulder" -4.890709 -0.000069 -0.000002 -2.688722 -0.057138 0.006099 0 0 0 0 0 0
$definebone "def_r_elbow" "def_r_shoulderMid" -6.444286 0.00013 0.000005 -37.014561 0.164812 0.006865 0 0 0 0 0 0
$definebone "def_r_forearm" "def_r_elbow" -4.630386 -0.000137 -0.000053 -5.291104 -0.116958 0.007796 0 0 0 0 0 0
$definebone "def_r_wrist" "def_r_elbow" -9.956816 0.010937 -0.493216 -5.403711 -0.039457 -0.000077 0 0 0 0 0 0
$definebone "def_r_finIndexA" "def_r_wrist" -3.077376 0.138977 -1.247286 -3.532781 -45.109219 3.539621 0 0 0 0 0 0
$definebone "def_r_finIndexB" "def_r_finIndexA" -1.748192 0.000002 -0.000114 -0.001197 -45.000001 0.001184 0 0 0 0 0 0
$definebone "def_r_finIndexC" "def_r_finIndexB" -1.195347 0.00008 -0.000078 0.000611 -45.000005 -0.000613 0 0 0 0 0 0
$definebone "def_r_finMidA" "def_r_wrist" -3.08066 0.067764 -0.349348 6.351203 -45.354908 -6.390478 0 0 0 0 0 0
$definebone "def_r_finMidB" "def_r_finMidA" -1.836304 -0.000002 -0.00005 -0.000003 -44.999994 0.000005 0 0 0 0 0 0
$definebone "def_r_finMidC" "def_r_finMidB" -1.309258 -0.000061 0.000052 -0.002987 -45.000008 0.002984 0 0 0 0 0 0
$definebone "def_r_finThumbA" "def_r_wrist" -0.504133 0.563412 -0.770212 -42.349741 -57.483255 126.990511 0 0 0 0 0 0
$definebone "def_r_finThumbB" "def_r_finThumbA" -2.132332 0.000069 -0.00008 3.25942 -22.647166 2.460342 0 0 0 0 0 0
$definebone "def_r_finThumbC" "def_r_finThumbB" -1.240768 -0.000023 0.00005 0.074482 -45.185656 0.008905 0 0 0 0 0 0
$definebone "def_r_finRingCarpal" "def_r_wrist" -2.513052 0.138145 0.333541 17.995867 0.000031 0.000083 0 0 0 0 0 0
$definebone "def_r_finRingA" "def_r_finRingCarpal" -0.316674 -0.000145 -0.000084 0.003161 -45.000001 -0.003161 0 0 0 0 0 0
$definebone "def_r_finRingB" "def_r_finRingA" -1.966396 0.000031 0.000019 0.000002 -45.000005 0.000004 0 0 0 0 0 0
$definebone "def_r_finRingC" "def_r_finRingB" -1.006874 -0.000014 -0.000002 0.000599 -45.000005 -0.000595 0 0 0 0 0 0
$definebone "def_r_finPinkyA" "def_r_finRingCarpal" 0.030523 0.172421 0.590875 18.727346 -48.299795 -19.816788 0 0 0 0 0 0
$definebone "def_r_finPinkyB" "def_r_finPinkyA" -1.644104 -0.000021 0.00001 0 -45.000005 0 0 0 0 0 0 0
$definebone "def_r_finPinkyC" "def_r_finPinkyB" -0.763535 -0.000238 -0.000006 0 -45.000001 0 0 0 0 0 0 0
$definebone "def_l_thigh" "def_c_hip" 5.219006 -1.00618 -0.600196 -0.050695 -90.000003 90.000003 0 0 0 0 0 0
$definebone "def_l_knee" "def_l_thigh" 18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_l_ankle" "def_l_knee" 17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_l_ball" "def_l_ankle" 5.292377 0 0 0.427673 29.592491 1.875762 0 0 0 0 0 0
$definebone "def_l_kneeB" "def_l_thigh" 18.246761 1.130153 0 0 -7.498168 0 0 0 0 0 0 0
$definebone "def_r_thigh" "def_c_hip" -5.219006 -1.00618 -0.600196 0.050695 90.000003 -90.000003 0 0 0 0 0 0
$definebone "def_r_knee" "def_r_thigh" -18.098003 0 0 0 -3.72269 0 0 0 0 0 0 0
$definebone "def_r_ankle" "def_r_knee" -17.311804 0 0 -3.795738 61.268573 0 0 0 0 0 0 0
$definebone "def_r_ball" "def_r_ankle" -5.292377 0 0 0.427673 29.592491 1.875761 0 0 0 0 0 0
$definebone "def_r_kneeB" "def_r_thigh" -18.246761 -1.130153 0 0 -7.498168 -0.000001 0 0 0 0 0 0
$definebone "ja_l_propHand" "def_l_wrist" 4.441361 -1.883156 0.77133 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "ja_r_propHand" "def_r_wrist" -4.441751 1.88372 -0.770998 0.000002 0 0.000003 0 0 0 0 0 0
$definebone "def_l_cable1" "def_l_wrist" -0.594381 1.407345 0.734905 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "def_l_cable2" "def_l_cable1" 0.97291 -0.059795 -0.040682 42.372407 -9.237773 -164.259684 0 0 0 0 0 0
$definebone "def_l_cable3" "def_l_cable2" 0.973484 0.000004 0.000002 -30.043277 2.383739 -0.575788 0 0 0 0 0 0
$definebone "def_l_cable4" "def_l_cable3" 0.973483 0 0 -36.826539 3.166195 -5.012322 0 0 0 0 0 0
$definebone "def_l_cable5" "def_l_cable4" 0.973485 0 0.000002 -38.201245 4.122105 92.126691 0 0 0 0 0 0
$definebone "def_l_cable6" "def_l_cable5" 0.973485 0.000002 0 13.18221 8.439121 13.133897 0 0 0 0 0 0
$definebone "def_ts_wheel" "def_l_wrist" 1.661965 1.075058 0.708656 0.000002 0 -0.000002 0 0 0 0 0 0
$definebone "def_l_strap_link" "def_l_wrist" -0.76113 0.947525 1.096483 0.000017 0.00007 -0.000075 0 0 0 0 0 0
$definebone "def_l_strap1" "def_l_strap_link" 0.173687 0.000023 0.016428 -0.000002 0.000002 0.000003 0 0 0 0 0 0
$definebone "def_l_strap2" "def_l_strap1" 0.433304 -0.055321 0.012999 -4.805906 -31.204867 0.000002 0 0 0 0 0 0
$definebone "def_l_strap3" "def_l_strap2" 0.437016 0 -0.000002 4.660942 -19.947445 -1.637881 0 0 0 0 0 0
$definebone "def_l_strap4" "def_l_strap3" 0.437016 -0.000002 0 3.225216 -17.355738 0.04245 0 0 0 0 0 0
$definebone "def_l_band1" "def_l_wrist" -0.496252 -0.887684 0.063665 -7.61457 -0.000055 0.000055 0 0 0 0 0 0
$definebone "def_l_band2" "def_l_wrist" -1.547748 -0.987106 0.010374 -2.362407 -0.00005 0.000055 0 0 0 0 0 0
$definebone "jx_c_origin" "" -44.84877 27.903734 -24.119677 0 0 0 0 0 0 0 0 0

$bonemerge "def_l_clav"
$bonemerge "def_l_shoulder"
$bonemerge "def_l_shoulderTwist"
$bonemerge "def_l_elbowB"
$bonemerge "def_l_shoulderMid"
$bonemerge "def_l_elbow"
$bonemerge "def_l_forearm"
$bonemerge "def_l_wrist"
$bonemerge "def_l_finIndexA"
$bonemerge "def_l_finIndexB"
$bonemerge "def_l_finIndexC"
$bonemerge "def_l_finMidA"
$bonemerge "def_l_finMidB"
$bonemerge "def_l_finMidC"
$bonemerge "def_l_finRingCarpal"
$bonemerge "def_l_finRingA"
$bonemerge "def_l_finRingB"
$bonemerge "def_l_finRingC"
$bonemerge "def_l_finPinkyA"
$bonemerge "def_l_finPinkyB"
$bonemerge "def_l_finPinkyC"
$bonemerge "def_r_clav"
$bonemerge "def_r_shoulder"
$bonemerge "def_r_shoulderTwist"
$bonemerge "def_r_elbowB"
$bonemerge "def_r_shoulderMid"
$bonemerge "def_r_elbow"
$bonemerge "def_r_forearm"
$bonemerge "def_r_wrist"
$bonemerge "def_r_finIndexA"
$bonemerge "def_r_finIndexB"
$bonemerge "def_r_finIndexC"
$bonemerge "def_r_finMidA"
$bonemerge "def_r_finMidB"
$bonemerge "def_r_finMidC"
$bonemerge "def_r_finRingCarpal"
$bonemerge "def_r_finRingA"
$bonemerge "def_r_finRingB"
$bonemerge "def_r_finRingC"
$bonemerge "def_r_finPinkyA"
$bonemerge "def_r_finPinkyB"
$bonemerge "def_r_finPinkyC"
$bonemerge "def_l_ankle"
$bonemerge "def_l_ball"
$bonemerge "def_r_ankle"
$bonemerge "def_r_ball"
$bonemerge "ja_l_propHand"
$bonemerge "ja_r_propHand"
$bonemerge "def_l_cable1"
$bonemerge "def_l_cable2"
$bonemerge "def_l_cable4"
$bonemerge "def_l_cable5"
$bonemerge "def_ts_wheel"
$bonemerge "def_l_strap_link"
$bonemerge "def_l_strap1"
$bonemerge "def_l_strap2"
$bonemerge "def_l_strap3"
$bonemerge "def_l_band2"


$bonesaveframe "def_l_clav" position rotation
$bonesaveframe "def_l_shoulder" position rotation
$bonesaveframe "def_l_shoulderTwist" position rotation
$bonesaveframe "def_l_elbowB" position
$bonesaveframe "def_l_shoulderMid" position rotation
$bonesaveframe "def_l_elbow" rotation
$bonesaveframe "def_l_forearm" position
$bonesaveframe "def_l_wrist" position
$bonesaveframe "def_l_finIndexA" position
$bonesaveframe "def_l_finIndexB" position
$bonesaveframe "def_l_finIndexC" position
$bonesaveframe "def_l_finMidA" rotation
$bonesaveframe "def_l_finMidB" rotation
$bonesaveframe "def_l_finMidC" rotation
$bonesaveframe "def_l_finThumbA" position
$bonesaveframe "def_l_finRingCarpal" position rotation
$bonesaveframe "def_l_finRingA" position rotation
$bonesaveframe "def_l_finRingB" position rotation
$bonesaveframe "def_l_finRingC" position rotation
$bonesaveframe "def_l_finPinkyA" position rotation
$bonesaveframe "def_l_finPinkyB" position rotation
$bonesaveframe "def_l_finPinkyC" position rotation
$bonesaveframe "def_r_clav" position rotation
$bonesaveframe "def_r_shoulder" position rotation
$bonesaveframe "def_r_shoulderTwist" position rotation
$bonesaveframe "def_r_elbowB" position
$bonesaveframe "def_r_shoulderMid" position rotation
$bonesaveframe "def_r_elbow" rotation
$bonesaveframe "def_r_forearm" position
$bonesaveframe "def_r_wrist" position
$bonesaveframe "def_r_finIndexA" position
$bonesaveframe "def_r_finIndexB" position
$bonesaveframe "def_r_finIndexC" position
$bonesaveframe "def_r_finMidA" rotation
$bonesaveframe "def_r_finMidB" rotation
$bonesaveframe "def_r_finMidC" rotation
$bonesaveframe "def_r_finThumbA" position
$bonesaveframe "def_r_finRingCarpal" position rotation
$bonesaveframe "def_r_finRingA" position rotation
$bonesaveframe "def_r_finRingB" position rotation
$bonesaveframe "def_r_finRingC" position rotation
$bonesaveframe "def_r_finPinkyA" position rotation
$bonesaveframe "def_r_finPinkyB" position rotation
$bonesaveframe "def_r_finPinkyC" position rotation
$bonesaveframe "def_l_thigh" position
$bonesaveframe "def_l_knee" position
$bonesaveframe "def_l_ankle" position rotation
$bonesaveframe "def_l_ball" rotation
$bonesaveframe "def_l_kneeB" position
$bonesaveframe "def_r_thigh" position
$bonesaveframe "def_r_knee" position
$bonesaveframe "def_r_ankle" position rotation
$bonesaveframe "def_r_ball" rotation
$bonesaveframe "ja_l_propHand" position
$bonesaveframe "ja_r_propHand" position
$bonesaveframe "def_l_cable1" position
$bonesaveframe "def_l_cable2" position rotation
$bonesaveframe "def_l_cable3" rotation
$bonesaveframe "def_l_cable4" rotation
$bonesaveframe "def_l_cable5" position rotation
$bonesaveframe "def_l_cable6" position rotation
$bonesaveframe "def_ts_wheel" position
$bonesaveframe "def_l_strap_link" position
$bonesaveframe "def_l_strap1" position
$bonesaveframe "def_l_strap2" position
$bonesaveframe "def_l_strap3" position
$bonesaveframe "def_l_strap4" position
$bonesaveframe "def_l_band2" position

$animation "a_ptpov_Into_Window_L_0" "pov_pete_core_anims\a_ptpov_Into_Window_L_0.smd" {
	fps 30
}

$animation "a_ptpov_Into_Window_L_90" "pov_pete_core_anims\a_ptpov_Into_Window_L_90.smd" {
	fps 30
}

$animation "a_ptpov_Into_Window_R_0" "pov_pete_core_anims\a_ptpov_Into_Window_R_0.smd" {
	fps 30
}

$animation "a_ptpov_Into_Window_R_90" "pov_pete_core_anims\a_ptpov_Into_Window_R_90.smd" {
	fps 30
}

$animation "a_ptpov_Mantle_Idle" "pov_pete_core_anims\a_ptpov_Mantle_Idle.smd" {
	fps 30
}

$animation "a_ptpov_Mantle_Idle_LedgeAngleLeft" "pov_pete_core_anims\a_ptpov_Mantle_Idle_LedgeAngleLeft.smd" {
	fps 30
	loop
}

$animation "a_ptpov_Mantle_Idle_LedgeAngleRight" "pov_pete_core_anims\a_ptpov_Mantle_Idle_LedgeAngleRight.smd" {
	fps 30
}

$animation "a_ptpov_wallrun_hang_left" "pov_pete_core_anims\a_ptpov_wallrun_hang_left.smd" {
	fps 30
}

$animation "a_ptpov_wallrun_hang_right" "pov_pete_core_anims\a_ptpov_wallrun_hang_right.smd" {
	fps 30
}

$animation "a_ptpov_wallrun_hang_up" "pov_pete_core_anims\a_ptpov_wallrun_hang_up.smd" {
	fps 30
}

$animation "a_ptpov_wallrun_hang_front" "pov_pete_core_anims\a_ptpov_wallrun_hang_front.smd" {
	fps 30
}

$animation "a_ptpov_wallrun_hang_idle" "pov_pete_core_anims\a_ptpov_wallrun_hang_idle.smd" {
	fps 30
}

$animation "ptpov_data_knife_console_leech_remoteturret_start_anim" "pov_pete_core_anims\ptpov_data_knife_console_leech_remoteturret_start_anim.smd" {
	fps 30
}

$animation "a_aim_ride_neutral" "pov_pete_core_anims\a_aim_ride_neutral.smd" {
	fps 30
}

$animation "a_aim_ride_down_left" "pov_pete_core_anims\a_aim_ride_down_left.smd" {
	fps 30
}

$animation "a_aim_ride_down_center" "pov_pete_core_anims\a_aim_ride_down_center.smd" {
	fps 30
}

$animation "a_aim_ride_down_right" "pov_pete_core_anims\a_aim_ride_down_right.smd" {
	fps 30
}

$animation "a_aim_ride_mid_left" "pov_pete_core_anims\a_aim_ride_mid_left.smd" {
	fps 30
}

$animation "a_aim_ride_mid_center" "pov_pete_core_anims\a_aim_ride_mid_center.smd" {
	fps 30
}

$animation "a_aim_ride_mid_right" "pov_pete_core_anims\a_aim_ride_mid_right.smd" {
	fps 30
}

$animation "a_aim_ride_up_left" "pov_pete_core_anims\a_aim_ride_up_left.smd" {
	fps 30
}

$animation "a_aim_ride_up_center" "pov_pete_core_anims\a_aim_ride_up_center.smd" {
	fps 30
}

$animation "a_aim_ride_up_right" "pov_pete_core_anims\a_aim_ride_up_right.smd" {
	fps 30
}

$animation "a_aim_ride_straightup" "pov_pete_core_anims\a_aim_ride_straightup.smd" {
	fps 30
}

$animation "a_aim_joystick_R" "pov_pete_core_anims\a_aim_joystick_R.smd" {
	fps 30
}

$animation "a_aim_joystick_R_down_left" "pov_pete_core_anims\a_aim_joystick_R_down_left.smd" {
	fps 30
}

$animation "a_aim_joystick_R_down_center" "pov_pete_core_anims\a_aim_joystick_R_down_center.smd" {
	fps 30
}

$animation "a_aim_joystick_R_down_right" "pov_pete_core_anims\a_aim_joystick_R_down_right.smd" {
	fps 30
}

$animation "a_aim_joystick_R_mid_left" "pov_pete_core_anims\a_aim_joystick_R_mid_left.smd" {
	fps 30
}

$animation "a_aim_joystick_R_mid_center" "pov_pete_core_anims\a_aim_joystick_R_mid_center.smd" {
	fps 30
}

$animation "a_aim_joystick_R_mid_right" "pov_pete_core_anims\a_aim_joystick_R_mid_right.smd" {
	fps 30
}

$animation "a_aim_joystick_R_up_left" "pov_pete_core_anims\a_aim_joystick_R_up_left.smd" {
	fps 30
}

$animation "a_aim_joystick_R_up_center" "pov_pete_core_anims\a_aim_joystick_R_up_center.smd" {
	fps 30
}

$animation "a_aim_joystick_R_up_right" "pov_pete_core_anims\a_aim_joystick_R_up_right.smd" {
	fps 30
}

$animation "a_aim_joystick_R_straightup" "pov_pete_core_anims\a_aim_joystick_R_straightup.smd" {
	fps 30
}

$sequence "idle" {
	"pov_pete_core_anims\idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "basepose" {
	"pov_pete_core_anims\basepose.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_preanim" {
	"pov_pete_core_anims\ptpov_preanim.smd"
	fadein 1
	fadeout 1
	fps 30
	loop
}

$sequence "ptpov_postanim" {
	"pov_pete_core_anims\ptpov_postanim.smd"
	fadein 0.5
	fadeout 1
	fps 30
	loop
}

$sequence "enter1" {
	"pov_pete_core_anims\enter1.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_atlas_getin" {
	"pov_pete_core_anims\ptpov_atlas_getin.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_atlas_getout" {
	"pov_pete_core_anims\ptpov_atlas_getout.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dp_exit" {
	"pov_pete_core_anims\ptpov_dp_exit.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 122 "signal:player_exits_droppod" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dp_idle" {
	"pov_pete_core_anims\ptpov_dp_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "petepov_dp_turret_aim" {
	"pov_pete_core_anims\petepov_dp_turret_aim.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "ptpov_cqb_traverse_over" {
	"pov_pete_core_anims\ptpov_cqb_traverse_over.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_front" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_front.smd"
	fadein 0.3
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_behind" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_right" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_left" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_above_right" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_above_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_above_left" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_above_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_stand_front" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_stand_behind" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_stand_airgrab" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_airgrab.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_mount_atlas_above_right" {
	"pov_pete_core_anims\ptpov_mount_atlas_above_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_above_left" {
	"pov_pete_core_anims\ptpov_mount_atlas_above_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_atlas_kneel_front_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_front_fast.smd"
	fadein 0.3
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_kneel_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_behind_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_kneel_right_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_kneel_left_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_kneel_above_right_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_above_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_kneel_above_left_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_kneel_above_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_stand_front_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_front_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_stand_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_behind_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_stand_airgrab_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_stand_airgrab_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_mount_atlas_above_right_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_above_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_atlas_above_left_fast" {
	"pov_pete_core_anims\ptpov_mount_atlas_above_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_Ogre_Kneel_Front" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_behind" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_Right" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_left" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_Front" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_Behind" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_Behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_AirGrab" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_AirGrab.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Above_Right" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Above_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Above_Left" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Above_Left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_kneel_Above_Right" {
	"pov_pete_core_anims\ptpov_mount_Ogre_kneel_Above_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_kneel_Above_Left" {
	"pov_pete_core_anims\ptpov_mount_Ogre_kneel_Above_Left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_Front_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_Front_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_behind_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_Right_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Kneel_left_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Kneel_left_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_Front_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_Front_fast.smd"
	{ event AE_PLAYER_PHASE_SHIFT_ENTER 15 "" }
	{ event AE_PLAYER_PHASE_SHIFT_EXIT 20 "" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_Behind_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_Behind_fast.smd"
	{ event AE_PLAYER_PHASE_SHIFT_ENTER 34 "" }
	{ event AE_PLAYER_PHASE_SHIFT_EXIT 39 "" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_stand_AirGrab_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_stand_AirGrab_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Above_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Above_Right_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_Above_Left_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_Above_Left_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_kneel_Above_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_kneel_Above_Right_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Ogre_kneel_Above_Left_fast" {
	"pov_pete_core_anims\ptpov_mount_Ogre_kneel_Above_Left_fast.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_Front" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_behind" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_Right" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_left" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_kneel_Above_Right" {
	"pov_pete_core_anims\ptpov_mount_Stryder_kneel_Above_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_kneel_Above_Left" {
	"pov_pete_core_anims\ptpov_mount_Stryder_kneel_Above_Left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_Front" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_Behind" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_Behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_AirGrab" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_AirGrab.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Above_Right" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Above_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Above_Left" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Above_Left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_Front_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Kneel_left_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Kneel_left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_kneel_Above_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_kneel_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_kneel_Above_Left_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_kneel_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_Front_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_Front_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_Behind_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_Behind_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 12 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_stand_AirGrab_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_stand_AirGrab_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Above_Right_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Above_Right_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_Stryder_Above_Left_fast" {
	"pov_pete_core_anims\ptpov_mount_Stryder_Above_Left_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 10 "phase_shift_start" }
	{ event AE_SV_VSCRIPT_CALLBACK 17 "phase_shift_stop" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_front" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_front.smd"
	fadein 0.3
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_behind" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_right" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_left" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_above_right" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_above_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_above_left" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_above_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_stand_front" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_stand_behind" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_stand_airgrab" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_airgrab.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_mount_buddy_above_right" {
	"pov_pete_core_anims\ptpov_mount_buddy_above_right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_above_left" {
	"pov_pete_core_anims\ptpov_mount_buddy_above_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_mount_buddy_kneel_front_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_front_fast.smd"
	fadein 0.3
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_kneel_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_behind_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_kneel_right_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_kneel_left_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_kneel_above_right_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_above_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_kneel_above_left_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_kneel_above_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_stand_front_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_front_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_stand_behind_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_behind_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_stand_airgrab_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_stand_airgrab_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_mount_buddy_above_right_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_above_right_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_mount_buddy_above_left_fast" {
	"pov_pete_core_anims\ptpov_mount_buddy_above_left_fast.smd"
	fadein 0
	fadeout 0
	fps 60
}

$sequence "ptpov_buddy_getin" {
	"pov_pete_core_anims\ptpov_buddy_getin.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_buddy_getout" {
	"pov_pete_core_anims\ptpov_buddy_getout.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_preanim_stand" {
	"pov_pete_core_anims\ptpov_preanim_stand.smd"
	fadein 0
	fadeout 1
	fps 30
}

$sequence "ptpov_preanim_crouch" {
	"pov_pete_core_anims\ptpov_preanim_crouch.smd"
	fadein 0
	fadeout 1
	fps 30
}

$sequence "ptpov_postanim_stand" {
	"pov_pete_core_anims\ptpov_postanim_stand.smd"
	fadein 0.25
	fadeout 1
	fps 30
}

$sequence "ptpov_postanim_crouch" {
	"pov_pete_core_anims\ptpov_postanim_crouch.smd"
	fadein 0.25
	fadeout 1
	fps 30
}

$sequence "ptpov_redeye_turret_getin_right" {
	"pov_pete_core_anims\ptpov_redeye_turret_getin_right.smd"
	{ event AE_CL_PLAYSOUND 0 "player_ballturret_mount" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_redeye_turret_idle_right" {
	"pov_pete_core_anims\ptpov_redeye_turret_idle_right.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "ptpov_redeye_turret_getin_left" {
	"pov_pete_core_anims\ptpov_redeye_turret_getin_left.smd"
	{ event AE_CL_PLAYSOUND 0 "player_ballturret_mount" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_redeye_turret_idle_left" {
	"pov_pete_core_anims\ptpov_redeye_turret_idle_left.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "ptpov_rspn101_melee_necksnap_rear" {
	"pov_pete_core_anims\ptpov_rspn101_melee_necksnap_rear.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_rspn101_melee_necksnap_left" {
	"pov_pete_core_anims\ptpov_rspn101_melee_necksnap_left.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_rspn101_melee_necksnap_right" {
	"pov_pete_core_anims\ptpov_rspn101_melee_necksnap_right.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_rspn101_melee_necksnap_front" {
	"pov_pete_core_anims\ptpov_rspn101_melee_necksnap_front.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_rspn101_melee_necksnap_above_back" {
	"pov_pete_core_anims\ptpov_rspn101_melee_necksnap_above_back.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_melee_necksnap_rear_attacked" {
	"pov_pete_core_anims\ptpov_melee_necksnap_rear_attacked.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 19 "screen_blackout" }
	fadein 0.2
	fadeout 0.25
	fps 30
}

$sequence "ptpov_assassin_melee_necksnap_rear" {
	"pov_pete_core_anims\ptpov_assassin_melee_necksnap_rear.smd"
	fadein 0
	fadeout 0.25
	fps 30
}

$sequence "ptpov_assassin_melee_necksnap_rear_attacked" {
	"pov_pete_core_anims\ptpov_assassin_melee_necksnap_rear_attacked.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 19 "screen_blackout" }
	fadein 0.2
	fadeout 0.25
	fps 30
}

$sequence "ptpov_prowler_synced_death_back" {
	"pov_pete_core_anims\ptpov_prowler_synced_death_back.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_prowler_synced_death_front" {
	"pov_pete_core_anims\ptpov_prowler_synced_death_front.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_prowler_synced_death_left" {
	"pov_pete_core_anims\ptpov_prowler_synced_death_left.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_prowler_synced_death_right" {
	"pov_pete_core_anims\ptpov_prowler_synced_death_right.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_vs_prowler_synced_counter" {
	"pov_pete_core_anims\ptpov_vs_prowler_synced_counter.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_prowler_victory_execution" {
	"pov_pete_core_anims\ptpov_synced_prowler_victory_execution.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_weapon_toss_alt" {
	"pov_pete_core_anims\ptpov_weapon_toss_alt.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_workerbase_jumpdown_idle" {
	"pov_pete_core_anims\ptpov_workerbase_jumpdown_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "ptpov_workerbase_jumpdown_intro" {
	"pov_pete_core_anims\ptpov_workerbase_jumpdown_intro.smd"
	{ event AE_CL_PLAYSOUND 24 "Player_JumpLand" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_workerbase_hatch_open" {
	"pov_pete_core_anims\ptpov_workerbase_hatch_open.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_workerbase_hatch_open_idle" {
	"pov_pete_core_anims\ptpov_workerbase_hatch_open_idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_workerbase_hatch_open_loop" {
	"pov_pete_core_anims\ptpov_workerbase_hatch_open_loop.smd"
	fadein 0.7
	fadeout 0.7
	fps 30
	loop
}

$sequence "ptpov_workerbase_hatch_getout" {
	"pov_pete_core_anims\ptpov_workerbase_hatch_getout.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_hatch_open_from_below2" }
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "ptpov_workerbase_hatch_getout_brokenCam" {
	"pov_pete_core_anims\ptpov_workerbase_hatch_getout_brokenCam.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_hatch_open_from_below2" }
	fadein 0.3
	fadeout 0.3
	fps 30
}

$sequence "ptpov_workerbase_jumpdown_hatch_open" {
	"pov_pete_core_anims\ptpov_workerbase_jumpdown_hatch_open.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_hatch_open_from_above" }
	fadein 0.5
	fadeout 0.5
	fps 30
}

$sequence "ptpov_marvin_leech_start" {
	"pov_pete_core_anims\ptpov_marvin_leech_start.smd"
	{ event AE_CL_PLAYSOUND 0 "leech_marvin1" }
	fadein 0.2
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_marvin_leech_idle" {
	"pov_pete_core_anims\ptpov_marvin_leech_idle.smd"
	{ event AE_CL_PLAYSOUND 0 "leech_marvin2" }
	fadein 0.2
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_marvin_leech_end" {
	"pov_pete_core_anims\ptpov_marvin_leech_end.smd"
	{ event AE_CL_PLAYSOUND 0 "leech_marvin3" }
	fadein 0.2
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_satchel_charge_start" {
	"pov_pete_core_anims\ptpov_satchel_charge_start.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_satchel_charge_start" }
	fadein 0.2
	fadeout 0.3
	snap
	fps 30
}

$sequence "ptpov_satchel_charge_idle" {
	"pov_pete_core_anims\ptpov_satchel_charge_idle.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_satchel_charge_idle" }
	fadein 0.3
	fadeout 0.3
	fps 30
	loop
}

$sequence "ptpov_satchel_charge_end" {
	"pov_pete_core_anims\ptpov_satchel_charge_end.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_satchel_charge_end" }
	fadein 0.3
	fadeout 0.2
	fps 30
}

$sequence "ptpov_satchel_charge_interrupt" {
	"pov_pete_core_anims\ptpov_satchel_charge_interrupt.smd"
	{ event AE_CL_PLAYSOUND 0 "workerbase_satchel_charge_interrupt" }
	fadein 0.2
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_flyerdeath_01" {
	"pov_pete_core_anims\ptpov_flyerdeath_01.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_top_hatch_kill_01" {
	"pov_pete_core_anims\ptpov_top_hatch_kill_01.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_flyerdeath_02" {
	"pov_pete_core_anims\ptpov_flyerdeath_02.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_zipline_start" {
	"pov_pete_core_anims\ptpov_zipline_start.smd"
	activity "ACT_VM_ZIPLINE_MOUNT" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_window_grab_right" {
	"pov_pete_core_anims\ptpov_window_grab_right.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_window_grab_left" {
	"pov_pete_core_anims\ptpov_window_grab_left.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_Into_Window_L" {
	"a_ptpov_Into_Window_L_0"
	"a_ptpov_Into_Window_L_90"
	activity "ACT_VM_TRAVERSAL_WINDOW_LEFT" 1
}

$sequence "ptpov_Into_Window_R" {
	"a_ptpov_Into_Window_R_0"
	"a_ptpov_Into_Window_R_90"
	activity "ACT_VM_TRAVERSAL_WINDOW_RIGHT" 1
}

$sequence "ptpov_mantle_test" {
	"pov_pete_core_anims\ptpov_mantle_test.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_HighAbove" {
	"pov_pete_core_anims\ptpov_WallMantle_HighAbove.smd"
	activity "ACT_VM_MANTLE_HIGH" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_smallmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Above" {
	"pov_pete_core_anims\ptpov_WallMantle_Above.smd"
	activity "ACT_VM_MANTLE_ABOVE" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_mediummantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Level" {
	"pov_pete_core_anims\ptpov_WallMantle_Level.smd"
	activity "ACT_VM_MANTLE_LEVEL" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_lowmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Below" {
	"pov_pete_core_anims\ptpov_WallMantle_Below.smd"
	activity "ACT_VM_MANTLE_BELOW" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_extralowmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_HighAbove_Crouch" {
	"pov_pete_core_anims\ptpov_WallMantle_HighAbove_Crouch.smd"
	activity "ACT_VM_MANTLE_CROUCH_HIGH" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_smallmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Above_Crouch" {
	"pov_pete_core_anims\ptpov_WallMantle_Above_Crouch.smd"
	activity "ACT_VM_MANTLE_CROUCH_ABOVE" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_mediummantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Level_Crouch" {
	"pov_pete_core_anims\ptpov_WallMantle_Level_Crouch.smd"
	activity "ACT_VM_MANTLE_CROUCH_LEVEL" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_lowmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_WallMantle_Below_Crouch" {
	"pov_pete_core_anims\ptpov_WallMantle_Below_Crouch.smd"
	activity "ACT_VM_MANTLE_CROUCH_BELOW" 1
	{ event AE_CL_VSCRIPT_CALLBACK 0 "mantle_extralowmantle" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_mantle_jumpoff" {
	"pov_pete_core_anims\ptpov_mantle_jumpoff.smd"
	activity "ACT_VM_MANTLE_JUMPOFF" 1
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_Mantle_Idle" {
	"a_ptpov_Mantle_Idle_LedgeAngleLeft"
	"a_ptpov_Mantle_Idle"
	"a_ptpov_Mantle_Idle_LedgeAngleRight"
	activity "ACT_VM_MANTLE_IDLE" 1
}

$sequence "ptpov_flyin_A_center_pos3" {
	"pov_pete_core_anims\ptpov_flyin_A_center_pos3.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_flyin_A_left_pos3" {
	"pov_pete_core_anims\ptpov_flyin_A_left_pos3.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_flyin_A_right_pos3" {
	"pov_pete_core_anims\ptpov_flyin_A_right_pos3.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_dropship_rider_R_A_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_R_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_dropship_rider_R_B_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_R_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_dropship_rider_R_C_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_R_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_dropship_rider_L_A_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_L_A_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_dropship_rider_L_B_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_L_B_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_dropship_rider_L_C_idle" {
	"pov_pete_core_anims\ptpov_dropship_rider_L_C_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 15
	loop
}

$sequence "ptpov_e3_ridin_start_player" {
	"pov_pete_core_anims\ptpov_e3_ridin_start_player.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_end_player" {
	"pov_pete_core_anims\ptpov_e3_ridin_end_player.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_start_playerA" {
	"pov_pete_core_anims\ptpov_e3_ridin_start_playerA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_end_playerA" {
	"pov_pete_core_anims\ptpov_e3_ridin_end_playerA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_e3_ridin_start_playerB" {
	"pov_pete_core_anims\ptpov_e3_ridin_start_playerB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_end_playerB" {
	"pov_pete_core_anims\ptpov_e3_ridin_end_playerB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_e3_ridin_start_playerC" {
	"pov_pete_core_anims\ptpov_e3_ridin_start_playerC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_end_playerC" {
	"pov_pete_core_anims\ptpov_e3_ridin_end_playerC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_e3_ridin_start_playerD" {
	"pov_pete_core_anims\ptpov_e3_ridin_start_playerD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_e3_ridin_end_playerD" {
	"pov_pete_core_anims\ptpov_e3_ridin_end_playerD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinA_idle_povA" {
	"pov_pete_core_anims\Militia_flyinA_idle_povA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Militia_flyinA_countdown_povA" {
	"pov_pete_core_anims\Militia_flyinA_countdown_povA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinA_idle_povB" {
	"pov_pete_core_anims\Militia_flyinA_idle_povB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Militia_flyinA_countdown_povB" {
	"pov_pete_core_anims\Militia_flyinA_countdown_povB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinA_idle_povC" {
	"pov_pete_core_anims\Militia_flyinA_idle_povC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Militia_flyinA_countdown_povC" {
	"pov_pete_core_anims\Militia_flyinA_countdown_povC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinA_idle_povD" {
	"pov_pete_core_anims\Militia_flyinA_idle_povD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "Militia_flyinA_countdown_povD" {
	"pov_pete_core_anims\Militia_flyinA_countdown_povD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_warp_povA" {
	"pov_pete_core_anims\Militia_flyinB_warp_povA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_exit_povA" {
	"pov_pete_core_anims\Militia_flyinB_exit_povA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_warp_povB" {
	"pov_pete_core_anims\Militia_flyinB_warp_povB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_exit_povB" {
	"pov_pete_core_anims\Militia_flyinB_exit_povB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_warp_povC" {
	"pov_pete_core_anims\Militia_flyinB_warp_povC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_exit_povC" {
	"pov_pete_core_anims\Militia_flyinB_exit_povC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_warp_povD" {
	"pov_pete_core_anims\Militia_flyinB_warp_povD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_flyinB_exit_povD" {
	"pov_pete_core_anims\Militia_flyinB_exit_povD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_militia_Flyin_A" {
	"pov_pete_core_anims\ptpov_militia_Flyin_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_militia_Flyin_B" {
	"pov_pete_core_anims\ptpov_militia_Flyin_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_militia_Flyin_C" {
	"pov_pete_core_anims\ptpov_militia_Flyin_C.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_militia_Flyin_D" {
	"pov_pete_core_anims\ptpov_militia_Flyin_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_menu_countdown" {
	"pov_pete_core_anims\ptpov_menu_countdown.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "piggyback_idle_back" {
	"pov_pete_core_anims\piggyback_idle_back.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_piggyback_entrance_back" {
	"pov_pete_core_anims\ptpov_piggyback_entrance_back.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ogre_rodeo_panel_aim_idle" {
	"pov_pete_core_anims\ptpov_ogre_rodeo_panel_aim_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_ogre_rodeo_panel_aim_idle_move_fast" {
	"pov_pete_core_anims\ptpov_ogre_rodeo_panel_aim_idle_move_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
}

$sequence "ptpov_rodeo_move_ogre_back_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_front_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_front_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_front_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_front_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_left_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_left_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_right_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_right_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_back_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_back_mid_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_mid_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_ogre_back_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_front_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_front_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_front_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_front_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_left_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_left_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_right_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_right_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_back_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_ogre_back_mid_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_ogre_back_mid_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_ogre_R_hijack_battery" {
	"pov_pete_core_anims\ptpov_rodeo_ogre_R_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_ogre_R_return_battery" {
	"pov_pete_core_anims\ptpov_rodeo_ogre_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_heavy_grenade_1st" {
	"pov_pete_core_anims\ptpov_rodeo_heavy_grenade_1st.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_nuke_rodeo_ogre_R_return_battery" {
	"pov_pete_core_anims\ptpov_nuke_rodeo_ogre_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_Rodeo_ogre_player_side_lean" {
	"pov_pete_core_anims\ptpov_Rodeo_ogre_player_side_lean.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_rodeo_ogre_panel_opening" {
	"pov_pete_core_anims\ptpov_rodeo_ogre_panel_opening.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "ptpov_rodeo_move_atlas_back_idle" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_back_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_front_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_front_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_front_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_front_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_left_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_left_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_right_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_right_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_back_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_back_mid_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_mid_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_atlas_back_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_front_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_front_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_front_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_front_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_left_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_left_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_right_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_right_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_back_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_atlas_back_mid_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_atlas_back_mid_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_panel_opening" {
	"pov_pete_core_anims\ptpov_rodeo_panel_opening.smd"
	fadein 0.25
	fadeout 0.25
	fps 30
}

$sequence "ptpov_Rodeo_Friendly_Aim_2_Enemy_Aim" {
	"pov_pete_core_anims\ptpov_Rodeo_Friendly_Aim_2_Enemy_Aim.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_Rodeo_Enemy_Aim_Idle" {
	"pov_pete_core_anims\ptpov_Rodeo_Enemy_Aim_Idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_Rodeo_player_side_lean" {
	"pov_pete_core_anims\ptpov_Rodeo_player_side_lean.smd"
	fadein 0
	fadeout 0
	fps 20
}

$sequence "ptpov_Rodeo_player_side_lean_wide" {
	"pov_pete_core_anims\ptpov_Rodeo_player_side_lean_wide.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_Rodeo_player_side_lean_friendly" {
	"pov_pete_core_anims\ptpov_Rodeo_player_side_lean_friendly.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_rodeo_panel_fire" {
	"pov_pete_core_anims\ptpov_rodeo_panel_fire.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_back_idle" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_stryder_back_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_front_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_front_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_front_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_front_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_back_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_back_mid_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_mid_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_left_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_left_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_right_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_right_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_stryder_back_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_front_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_front_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_front_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_front_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_back_lower_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_lower_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_back_mid_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_back_mid_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_left_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_left_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_move_stryder_right_entrance_fast" {
	"pov_pete_core_anims\ptpov_rodeo_move_stryder_right_entrance_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
}

$sequence "ptpov_rodeo_stryder_R_hijack_battery" {
	"pov_pete_core_anims\ptpov_rodeo_stryder_R_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_stryder_R_return_battery" {
	"pov_pete_core_anims\ptpov_rodeo_stryder_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_light_grenade_1st" {
	"pov_pete_core_anims\ptpov_rodeo_light_grenade_1st.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_nuke_rodeo_stryder_R_return_battery" {
	"pov_pete_core_anims\ptpov_nuke_rodeo_stryder_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_stryder_panel_opening" {
	"pov_pete_core_anims\ptpov_rodeo_stryder_panel_opening.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "ptpov_Rodeo_stryder_Friendly_Aim_2_Enemy_Aim" {
	"pov_pete_core_anims\ptpov_Rodeo_stryder_Friendly_Aim_2_Enemy_Aim.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_Rodeo_stryder_Enemy_Aim_Idle" {
	"pov_pete_core_anims\ptpov_Rodeo_stryder_Enemy_Aim_Idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_Rodeo_stryder_player_side_lean" {
	"pov_pete_core_anims\ptpov_Rodeo_stryder_player_side_lean.smd"
	fadein 0
	fadeout 0
	fps 20
	loop
}

$sequence "ptpov_Rodeo_stryder_player_side_lean_wide" {
	"pov_pete_core_anims\ptpov_Rodeo_stryder_player_side_lean_wide.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_Rodeo_stryder_player_side_lean_friendly" {
	"pov_pete_core_anims\ptpov_Rodeo_stryder_player_side_lean_friendly.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_rodeo_stryder_panel_fire" {
	"pov_pete_core_anims\ptpov_rodeo_stryder_panel_fire.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_stryder_rodeo_panel_aim_idle" {
	"pov_pete_core_anims\ptpov_stryder_rodeo_panel_aim_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_stryder_rodeo_panel_aim_idle_move" {
	"pov_pete_core_anims\ptpov_stryder_rodeo_panel_aim_idle_move.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_stryder_rodeo_panel_aim_idle_move_fast" {
	"pov_pete_core_anims\ptpov_stryder_rodeo_panel_aim_idle_move_fast.smd"
	fadein 0.2
	fadeout 0.2
	fps 60
	loop
}

$sequence "ptpov_rodeo_move_buddy_back_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_back_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_back_idle" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_back_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_move_buddy_back_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_back_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_back_mid_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_back_mid_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_front_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_front_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_front_lower_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_front_lower_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_left_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_left_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_move_buddy_right_entrance" {
	"pov_pete_core_anims\ptpov_rodeo_move_buddy_right_entrance.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_sspec_attack_rodeo_idle" {
	"pov_pete_core_anims\ptpov_sspec_attack_rodeo_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_sspec_attack_rodeo_cancel" {
	"pov_pete_core_anims\ptpov_sspec_attack_rodeo_cancel.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_sspec_attack_powerdown_hack" {
	"pov_pete_core_anims\ptpov_sspec_attack_powerdown_hack.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 0 "create_dataknife" }
	{ event AE_CL_PLAYSOUND 13 "DataKnife_Hack_Console_Pt2" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "knife_popout" }
	{ event AE_CL_VSCRIPT_CALLBACK 20 "knife_popout" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_sspec_attack_hack_idle" {
	"pov_pete_core_anims\ptpov_sspec_attack_hack_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_sspec_attack_hack_cancel" {
	"pov_pete_core_anims\ptpov_sspec_attack_hack_cancel.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_MP_ogre_disembark" {
	"pov_pete_core_anims\ptpov_MP_ogre_disembark.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_MP_ogre_disembark_idle" {
	"pov_pete_core_anims\ptpov_MP_ogre_disembark_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_ogre_stand" {
	"pov_pete_core_anims\ptpov_dismount_ogre_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 21 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 36 "SetVelocity" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_dismount_ogre_stand_fast" {
	"pov_pete_core_anims\ptpov_dismount_ogre_stand_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 21 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 36 "SetVelocity" }
	fadein 0
	fadeout 0
	snap
	fps 60
}

$sequence "ptpov_dismount_ogre_crouch" {
	"pov_pete_core_anims\ptpov_dismount_ogre_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_ogre_crouch_fast" {
	"pov_pete_core_anims\ptpov_dismount_ogre_crouch_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 20 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_dismount_atlas_stand" {
	"pov_pete_core_anims\ptpov_dismount_atlas_stand.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_atlas_crouch" {
	"pov_pete_core_anims\ptpov_dismount_atlas_crouch.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_atlas_stand_fast" {
	"pov_pete_core_anims\ptpov_dismount_atlas_stand_fast.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_dismount_atlas_crouch_fast" {
	"pov_pete_core_anims\ptpov_dismount_atlas_crouch_fast.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_dismount_stryder_stand" {
	"pov_pete_core_anims\ptpov_dismount_stryder_stand.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_stryder_crouch" {
	"pov_pete_core_anims\ptpov_dismount_stryder_crouch.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_dismount_stryder_stand_fast" {
	"pov_pete_core_anims\ptpov_dismount_stryder_stand_fast.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_dismount_stryder_crouch_fast" {
	"pov_pete_core_anims\ptpov_dismount_stryder_crouch_fast.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 60
}

$sequence "ptpov_dismount_buddy_stand" {
	"pov_pete_core_anims\ptpov_dismount_buddy_stand.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_dismount_buddy_crouch" {
	"pov_pete_core_anims\ptpov_dismount_buddy_crouch.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_dismount_buddy_stand_fast" {
	"pov_pete_core_anims\ptpov_dismount_buddy_stand_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "ptpov_dismount_buddy_crouch_fast" {
	"pov_pete_core_anims\ptpov_dismount_buddy_crouch_fast.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 16 "RecordOrigin" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "SetVelocity" }
	fadein 0
	fadeout 0.2
	fps 60
}

$sequence "ptpov_MP_disembark" {
	"pov_pete_core_anims\ptpov_MP_disembark.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_MP_disembark_idle" {
	"pov_pete_core_anims\ptpov_MP_disembark_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_MP_disembark_idle_alt" {
	"pov_pete_core_anims\ptpov_MP_disembark_idle_alt.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_data_knife_spectre_leech_start" {
	"pov_pete_core_anims\ptpov_data_knife_spectre_leech_start.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "PlaySound_DataKnife_Hack_Spectre_Pt1" }
	{ event AE_SV_VSCRIPT_CALLBACK 9 "PlaySound_Spectre_Servo_Heavy_Short" }
	{ event AE_SV_VSCRIPT_CALLBACK 7 "PlaySound_DataKnife_Hack_Spectre_ArmorRattle" }
	{ event AE_SV_VSCRIPT_CALLBACK 14 "PlaySound_DataKnife_Hack_Spectre_Pt2" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 14 "reload_pilot_small" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_data_knife_spectre_leech_idle" {
	"pov_pete_core_anims\ptpov_data_knife_spectre_leech_idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "ptpov_data_knife_spectre_leech_end" {
	"pov_pete_core_anims\ptpov_data_knife_spectre_leech_end.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 1 "PlaySound_DataKnife_Hack_Spectre_Pt3" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "PlaySound_DataKnife_Hack_Spectre_ArmorRattle" }
	{ event AE_SV_VSCRIPT_CALLBACK 1 "PlaySound_Spectre_Servo_Heavy_Short" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "reload_pilot_small" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_data_knife_console_leech_start" {
	"pov_pete_core_anims\ptpov_data_knife_console_leech_start.smd"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_Hack_Console_Pt1" }
	{ event AE_CL_PLAYSOUND 11 "DataKnife_Hack_Console_Pt2" }
	{ event AE_CL_PLAYSOUND 26 "DataKnife_Hack_Console_Pt3" }
	{ event AE_CL_PLAYSOUND 49 "DataKnife_Hack_Console_Pt4" }
	{ event AE_CL_PLAYSOUND 67 "DataKnife_Hack_Console_Pt5" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 13 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 28 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 51 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 73 "reload_pilot_small" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_core_leech_start" {
	"pov_pete_core_anims\ptpov_data_core_leech_start.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 48 "timeshift_scan_start" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_core_scan_end" {
	"pov_pete_core_anims\ptpov_core_scan_end.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 14 "timeshift_scan_end" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_knife_console_leech_remoteturret_start" {
	"ptpov_data_knife_console_leech_remoteturret_start_anim"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_Hack_Console_Pt3" }
	{ event AE_CL_PLAYSOUND 18 "DataKnife_Hack_Console_Pt4" }
	{ event AE_CL_PLAYSOUND 32 "DataKnife_Hack_Console_Pt5" }
	{ event AE_CL_VSCRIPT_CALLBACK 38 "remoteturret_fadeout" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_knife_console_leech_idle" {
	"pov_pete_core_anims\ptpov_data_knife_console_leech_idle.smd"
	fadein 0
	fadeout 0
	snap
	fps 30
	loop
}

$sequence "ptpov_data_knife_console_leech_end" {
	"pov_pete_core_anims\ptpov_data_knife_console_leech_end.smd"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_HackComplete_Console_Pt1" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 13 "reload_pilot_small" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_mobile_hardpoint_laptop_start" {
	"pov_pete_core_anims\ptpov_mobile_hardpoint_laptop_start.smd"
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_mobile_hardpoint_laptop_idle" {
	"pov_pete_core_anims\ptpov_mobile_hardpoint_laptop_idle.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
	loop
}

$sequence "ptpov_mobile_hardpoint_laptop_end" {
	"pov_pete_core_anims\ptpov_mobile_hardpoint_laptop_end.smd"
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_gpmm_into" {
	"pov_pete_core_anims\ptpov_gpmm_into.smd"
	fadein 0.2
	fadeout 0
	snap
	fps 30
}

$sequence "Militia_O2_flyinA_povA" {
	"pov_pete_core_anims\Militia_O2_flyinA_povA.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_O2_flyinA_povB" {
	"pov_pete_core_anims\Militia_O2_flyinA_povB.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_O2_flyinA_povC" {
	"pov_pete_core_anims\Militia_O2_flyinA_povC.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Militia_O2_flyinA_povD" {
	"pov_pete_core_anims\Militia_O2_flyinA_povD.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ready_front_L" {
	"pov_pete_core_anims\ptpov_droppod_ready_front_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ready_front_R" {
	"pov_pete_core_anims\ptpov_droppod_ready_front_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ready_back_L" {
	"pov_pete_core_anims\ptpov_droppod_ready_back_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ready_back_R" {
	"pov_pete_core_anims\ptpov_droppod_ready_back_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_drop_front_L" {
	"pov_pete_core_anims\ptpov_droppod_drop_front_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_drop_front_R" {
	"pov_pete_core_anims\ptpov_droppod_drop_front_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_drop_back_L" {
	"pov_pete_core_anims\ptpov_droppod_drop_back_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_drop_back_R" {
	"pov_pete_core_anims\ptpov_droppod_drop_back_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_space_front_L" {
	"pov_pete_core_anims\ptpov_droppod_ride_space_front_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_space_front_R" {
	"pov_pete_core_anims\ptpov_droppod_ride_space_front_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_space_back_L" {
	"pov_pete_core_anims\ptpov_droppod_ride_space_back_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_space_back_R" {
	"pov_pete_core_anims\ptpov_droppod_ride_space_back_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_atmos_front_L" {
	"pov_pete_core_anims\ptpov_droppod_ride_atmos_front_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_atmos_front_R" {
	"pov_pete_core_anims\ptpov_droppod_ride_atmos_front_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_atmos_back_L" {
	"pov_pete_core_anims\ptpov_droppod_ride_atmos_back_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_ride_atmos_back_R" {
	"pov_pete_core_anims\ptpov_droppod_ride_atmos_back_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_exit_front_L" {
	"pov_pete_core_anims\ptpov_droppod_exit_front_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_exit_front_R" {
	"pov_pete_core_anims\ptpov_droppod_exit_front_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_exit_back_L" {
	"pov_pete_core_anims\ptpov_droppod_exit_back_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_droppod_exit_back_R" {
	"pov_pete_core_anims\ptpov_droppod_exit_back_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "fmpov_mount_Ogre_Kneel_Front" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Kneel_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_Kneel_behind" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Kneel_behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_Kneel_Right" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Kneel_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_Kneel_left" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Kneel_left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_stand_Front" {
	"pov_pete_core_anims\fmpov_mount_Ogre_stand_Front.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_stand_Behind" {
	"pov_pete_core_anims\fmpov_mount_Ogre_stand_Behind.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_stand_AirGrab" {
	"pov_pete_core_anims\fmpov_mount_Ogre_stand_AirGrab.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_Above_Right" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Above_Right.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_mount_Ogre_Above_Left" {
	"pov_pete_core_anims\fmpov_mount_Ogre_Above_Left.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "fmpov_OgreDisembark_Kneel_Crouch" {
	"pov_pete_core_anims\fmpov_OgreDisembark_Kneel_Crouch.smd"
	fadein 0.2
	fadeout 0.2
	snap
	fps 30
}

$sequence "Classic_MP_flyin_exit_povA_idle" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povA_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povA_jump" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povA_jump.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povB_idle" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povB_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povB_jump" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povB_jump.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povC_idle" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povC_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povC_jump" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povC_jump.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povD_idle" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povD_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Classic_MP_flyin_exit_povD_jump" {
	"pov_pete_core_anims\Classic_MP_flyin_exit_povD_jump.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_trainingpod_doors_close" {
	"pov_pete_core_anims\ptpov_trainingpod_doors_close.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 14 "PlaySound_SimPod_DoorShut" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_trainingpod_doors_open" {
	"pov_pete_core_anims\ptpov_trainingpod_doors_open.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_trainingpod_handle_close" {
	"pov_pete_core_anims\ptpov_trainingpod_handle_close.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_trainingpod_handle_open" {
	"pov_pete_core_anims\ptpov_trainingpod_handle_open.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_trainingpod_idle" {
	"pov_pete_core_anims\ptpov_trainingpod_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_generic_side_jumpLand_A" {
	"pov_pete_core_anims\ptpov_generic_side_jumpLand_A.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_generic_side_jumpLand_B" {
	"pov_pete_core_anims\ptpov_generic_side_jumpLand_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_generic_side_jumpLand_C" {
	"pov_pete_core_anims\ptpov_generic_side_jumpLand_C.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_generic_side_jumpLand_D" {
	"pov_pete_core_anims\ptpov_generic_side_jumpLand_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_relic_runto_dropship" {
	"pov_pete_core_anims\ptpov_relic_runto_dropship.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_data_knife_drone_scene" {
	"pov_pete_core_anims\ptpov_data_knife_drone_scene.smd"
	{ event AE_CL_PLAYSOUND 0 "DataKnife_Hack_Console_Pt1" }
	{ event AE_CL_PLAYSOUND 13 "DataKnife_Hack_Console_Pt2" }
	{ event AE_CL_PLAYSOUND 28 "DataKnife_Hack_Console_Pt3" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_knife_drone_start" {
	"pov_pete_core_anims\ptpov_data_knife_drone_start.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 0 "create_dataknife" }
	{ event AE_CL_PLAYSOUND 13 "DataKnife_Hack_Console_Pt2" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "knife_popout" }
	{ event AE_CL_VSCRIPT_CALLBACK 22 "knife_popout" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_knife_drone_idle" {
	"pov_pete_core_anims\ptpov_data_knife_drone_idle.smd"
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_data_knife_drone_end" {
	"pov_pete_core_anims\ptpov_data_knife_drone_end.smd"
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_drone_ride_landing" {
	"pov_pete_core_anims\ptpov_drone_ride_landing.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_drone_ride_idle" {
	"pov_pete_core_anims\ptpov_drone_ride_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_drone_ride_leapaway" {
	"pov_pete_core_anims\ptpov_drone_ride_leapaway.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_drone_entrance_low_B" {
	"pov_pete_core_anims\ptpov_drone_entrance_low_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ninja_melee_block_01" {
	"pov_pete_core_anims\ptpov_ninja_melee_block_01.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ninja_melee_knockback_01" {
	"pov_pete_core_anims\ptpov_ninja_melee_knockback_01.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 3 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 4 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 5 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 6 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 12 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 13 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 22 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 23 "P_sword_clash_sparks_FP start_at_attachment KNIFE" }
	{ event AE_CL_PLAYSOUND 0 "ElitePilot.ninja_melee_knockback_PlayerArms" }
	fadein 0
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_ninja_melee_knockback_02" {
	"pov_pete_core_anims\ptpov_ninja_melee_knockback_02.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ninja_melee_finisher_01" {
	"pov_pete_core_anims\ptpov_ninja_melee_finisher_01.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ninja_melee_finisher_02" {
	"pov_pete_core_anims\ptpov_ninja_melee_finisher_02.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_ninja_counter_kick" {
	"pov_pete_core_anims\ptpov_ninja_counter_kick.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_intro_camera" {
	"pov_pete_core_anims\ptpov_wilds_intro_camera.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_intro_camera_idle" {
	"pov_pete_core_anims\ptpov_wilds_intro_camera_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_wilds_escape_pod_wake" {
	"pov_pete_core_anims\ptpov_wilds_escape_pod_wake.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 435 "P_wild_pod_fall start_at_attachment l_hand" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 435 "wilds_hitting_ground" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_escape_pod_wake_idle" {
	"pov_pete_core_anims\ptpov_wilds_escape_pod_wake_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_wilds_OG_victory" {
	"pov_pete_core_anims\pov_wilds_OG_victory.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_wilds_OG_victory_late" {
	"pov_pete_core_anims\pov_wilds_OG_victory_late.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 38 "screenshake:0.5:20:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 341 "screenshake:0.5:20:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 364 "screenshake:0.5:20:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 670 "screenshake:0.2:0.3:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 879 "screenshake:0.2:0.3:1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_wilds_OG_defeated" {
	"pov_pete_core_anims\pov_wilds_OG_defeated.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 145 "screenblur:0.8:90" }
	{ event AE_CL_VSCRIPT_CALLBACK 200 "screenblur:0:90" }
	{ event AE_CL_VSCRIPT_CALLBACK 410 "screenblur:1:90" }
	{ event AE_CL_VSCRIPT_CALLBACK 410 "fade_to_black:90" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_wilds_OG_final_words" {
	"pov_pete_core_anims\pov_wilds_OG_final_words.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "wilds_og_pilot_grab" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_family_photo_camera" {
	"pov_pete_core_anims\pov_family_photo_camera.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 1 "fade_from_black:300" }
	{ event AE_CL_VSCRIPT_CALLBACK 1 "screenblur:1:0" }
	{ event AE_CL_VSCRIPT_CALLBACK 5 "screenblur:0:300" }
	{ event AE_CL_VSCRIPT_CALLBACK 960 "fade_to_black:340" }
	{ event AE_CL_VSCRIPT_CALLBACK 1200 "screenblur:1:260" }
	{ event AE_CL_VSCRIPT_CALLBACK 1310 "screenblur:0:0" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_prowler_encounter" {
	"pov_pete_core_anims\ptpov_wilds_prowler_encounter.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 0 "fade_from_black:600" }
	{ event AE_CL_VSCRIPT_CALLBACK 164 "fade_to_black:14" }
	{ event AE_CL_VSCRIPT_CALLBACK 179 "fade_from_black:30" }
	{ event AE_CL_VSCRIPT_CALLBACK 210 "fade_to_black:7" }
	{ event AE_CL_VSCRIPT_CALLBACK 218 "fade_from_black:15" }
	{ event AE_CL_VSCRIPT_CALLBACK 0 "screenblur:1:0" }
	{ event AE_CL_VSCRIPT_CALLBACK 280 "screenblur:0:15" }
	{ event AE_CL_VSCRIPT_CALLBACK 298 "screenblur:0.3:21" }
	{ event AE_CL_VSCRIPT_CALLBACK 320 "screenblur:1:10" }
	{ event AE_CL_VSCRIPT_CALLBACK 331 "screenblur:0.6:17" }
	{ event AE_CL_VSCRIPT_CALLBACK 349 "screenblur:0.9:19" }
	{ event AE_CL_VSCRIPT_CALLBACK 369 "screenblur:0:90" }
	{ event AE_CL_VSCRIPT_CALLBACK 0 "prowler_dof_start" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "wilds_wakingup" }
	{ event AE_SV_VSCRIPT_CALLBACK 285 "signal:music_cue" }
	{ event AE_CL_VSCRIPT_CALLBACK 640 "prowler_dof_stop" }
	{ event AE_CL_PLAYSOUND 0 "Wilds_Anim_ProwlerEncounter_Cooper_Pt1" }
	{ event AE_CL_PLAYSOUND 253 "Wilds_Anim_ProwlerEncounter_Cooper_Pt2" }
	{ event AE_CL_PLAYSOUND 457 "Wilds_Anim_ProwlerEncounter_Cooper_Pt3" }
	{ event AE_CL_PLAYSOUND 747 "Wilds_Anim_ProwlerEncounter_Cooper_Pt4" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_first_battery_insert" {
	"pov_pete_core_anims\ptpov_wilds_first_battery_insert.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_second_battery_insert" {
	"pov_pete_core_anims\ptpov_wilds_second_battery_insert.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "wilds_slot_battery_2" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_third_battery_insert" {
	"pov_pete_core_anims\ptpov_wilds_third_battery_insert.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "wilds_slot_battery_3" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_battery_pickup" {
	"pov_pete_core_anims\ptpov_wilds_battery_pickup.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 78 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 92 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 164 "reload_pilot_small" }
	{ event AE_CL_PLAYSOUND 0 "wilds_anim_battery_pickup_01" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_battery_pickup_02" {
	"pov_pete_core_anims\ptpov_wilds_battery_pickup_02.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 54 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 95 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 140 "reload_pilot_small" }
	{ event AE_CL_PLAYSOUND 0 "wilds_anim_battery_pickup_02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_OG_grave" {
	"pov_pete_core_anims\ptpov_OG_grave.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "wilds_don_helmet" }
	{ event AE_CL_VSCRIPT_CALLBACK 595 "fade_to_black:2" }
	{ event AE_CL_PLAYSOUND 0 "Wilds_Anim_BuryOG_PlaceRock" }
	{ event AE_CL_PLAYSOUND 241 "Wilds_Anim_BuryOG_GetHelmet" }
	{ event AE_CL_PLAYSOUND 425 "Wilds_Anim_BuryOG_ExamineHelmet" }
	{ event AE_CL_PLAYSOUND 575 "Wilds_Anim_BuryOG_HelmetOn" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_wilds_first_embark" {
	"pov_pete_core_anims\ptpov_wilds_first_embark.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 112 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 356 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 422 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 457 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 481 "reload_pilot_large" }
	{ event AE_CL_PLAYSOUND 244 "diag_sp_extra_GB101_92_01_mcor_player" }
	{ event AE_CL_VSCRIPT_CALLBACK 517 "fade_to_black:7" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_torture_intro_player" {
	"pov_pete_core_anims\pov_torture_intro_player.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 747 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 753 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 757 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 765 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 788 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 805 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1132 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1148 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1177 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1691 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1695 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1700 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1710 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1720 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1725 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1730 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1740 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1745 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1750 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1755 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1760 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1830 "reload_pilot_large" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pov_torture_intro_player_beforeQuestion" {
	"pov_pete_core_anims\pov_torture_intro_player_beforeQuestion.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pov_torture_intro_player_beforeQuestion_idle" {
	"pov_pete_core_anims\pov_torture_intro_player_beforeQuestion_idle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "pov_torture_intro_player_2ndhalfonly" {
	"pov_pete_core_anims\pov_torture_intro_player_2ndhalfonly.smd"
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pov_torture_kill_player" {
	"pov_pete_core_anims\pov_torture_kill_player.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 46 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 74 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 98 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 126 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 185 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 224 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 316 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 345 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 367 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 392 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 426 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 502 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 507 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 512 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 517 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 522 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 527 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 532 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 537 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 542 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 550 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 560 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 565 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 570 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 575 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 580 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 674 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 718 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 753 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 778 "reload_pilot_large" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "pov_torture_kill_player_endidle" {
	"pov_pete_core_anims\pov_torture_kill_player_endidle.smd"
	fadein 0
	fadeout 0
	fps 30
	loop
}

$sequence "pov_torture_kill_player_get_up" {
	"pov_pete_core_anims\pov_torture_kill_player_get_up.smd"
	fadein 0
	fadeout 0
	fps 23
}

$sequence "pov_blisk_taunt_scene_player" {
	"pov_pete_core_anims\pov_blisk_taunt_scene_player.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_torture_cache_pickup" {
	"pov_pete_core_anims\ptpov_torture_cache_pickup.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 33 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 62 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 84 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 219 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 283 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 304 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 380 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 435 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 527 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 547 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 651 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 703 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 715 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 747 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 792 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 887 "reload_pilot_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_reunion_insert" {
	"pov_pete_core_anims\ptpov_skyway_reunion_insert.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 167 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 179 "reload_pilot_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_reunion_embark" {
	"pov_pete_core_anims\ptpov_skyway_reunion_embark.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 17 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 34 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 46 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 57 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 87 "reload_pilot_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_world_run" {
	"pov_pete_core_anims\ptpov_skyway_world_run.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 100 "screenshake:0.5:70:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 316 "screenshake:0.5:20:1" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_world_run_idle" {
	"pov_pete_core_anims\ptpov_skyway_world_run_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_world_run_end_idle" {
	"pov_pete_core_anims\ptpov_skyway_world_run_end_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_skyway_world_run_land" {
	"pov_pete_core_anims\ptpov_skyway_world_run_land.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 3 "titan_damaged_big" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_skyway_injector_throw" {
	"pov_pete_core_anims\ptpov_skyway_injector_throw.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 18 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 81 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 156 "reload_pilot_large" }
	{ event AE_CL_VSCRIPT_CALLBACK 24 "screenshake:1:20:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 81 "screenshake:1:20:1" }
	{ event AE_CL_VSCRIPT_CALLBACK 156 "screenshake:1:20:1" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "Aim_ride" {
	"a_aim_ride_up_left"
	"a_aim_ride_up_center"
	"a_aim_ride_up_right"
	"a_aim_ride_mid_left"
	"a_aim_ride_mid_center"
	"a_aim_ride_mid_right"
	"a_aim_ride_down_left"
	"a_aim_ride_down_center"
	"a_aim_ride_down_right"
}

$sequence "ptpov_blisk_taunt_scene_aim" {
	"pov_pete_core_anims\ptpov_blisk_taunt_scene_aim.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_blisk_taunt_scene_idle" {
	"pov_pete_core_anims\ptpov_blisk_taunt_scene_idle.smd"
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_ride"
	fps 30
}

$sequence "ptpov_planet_explosion" {
	"pov_pete_core_anims\ptpov_planet_explosion.smd"
	fadein 0.2
	fadeout 0.2
	fps 24
}

$sequence "ptpov_planet_explosion_slow_1" {
	"pov_pete_core_anims\ptpov_planet_explosion_slow_1.smd"
	fadein 0.2
	fadeout 0.2
	fps 10
}

$sequence "ptpov_planet_explosion_slow_2" {
	"pov_pete_core_anims\ptpov_planet_explosion_slow_2.smd"
	fadein 0.2
	fadeout 0.2
	fps 12
}

$sequence "ptpov_planet_ex_ending" {
	"pov_pete_core_anims\ptpov_planet_ex_ending.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pov_intro_scene_player" {
	"pov_pete_core_anims\pov_intro_scene_player.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 898 "reload_pilot_large" }
	fadein 0
	fadeout 0.2
	snap
	fps 30
}

$sequence "ptpov_FastBall_Disembark" {
	"pov_pete_core_anims\ptpov_FastBall_Disembark.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_intro_camp" {
	"pov_pete_core_anims\ptpov_beacon_intro_camp.smd"
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "ptpov_beacon_controlroom_a_disembark" {
	"pov_pete_core_anims\ptpov_beacon_controlroom_a_disembark.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_arc_tool_steal" {
	"pov_pete_core_anims\ptpov_beacon_arc_tool_steal.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 22 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 65 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 72 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 73 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 74 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 75 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 76 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 77 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 78 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 79 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 80 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 81 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 82 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 83 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 84 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 85 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 86 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 87 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 88 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 89 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 90 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 91 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 92 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 93 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 94 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 95 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 96 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 97 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 98 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 99 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 100 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 101 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 102 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 103 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 104 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 105 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 106 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 107 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 108 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 109 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 110 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 111 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 112 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 113 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 114 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 115 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 116 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 117 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 118 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 119 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 120 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 121 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 122 "reload_pilot_large" }
	{ event AE_CL_PLAYSOUND 0 "wpn_arc_tool_take_away_1p" }
	{ event AE_CL_PLAYSOUND 0 "Beacon_Anim_arc_tool_steal_pt01" }
	{ event AE_SV_VSCRIPT_CALLBACK 14 "signal:attach_arc_tool" }
	{ event AE_CL_VSCRIPT_CALLBACK 14 "snap_gun" }
	{ event AE_CL_PLAYSOUND 40 "Beacon_Anim_arc_tool_steal_pt02" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_lefthand_wind_start" {
	"pov_pete_core_anims\ptpov_beacon_lefthand_wind_start.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_lefthand_wind_loop" {
	"pov_pete_core_anims\ptpov_beacon_lefthand_wind_loop.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_beacon_lefthand_wind_end" {
	"pov_pete_core_anims\ptpov_beacon_lefthand_wind_end.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_wind_tunnel" {
	"pov_pete_core_anims\ptpov_beacon_wind_tunnel.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_wind_tunnel_short" {
	"pov_pete_core_anims\ptpov_beacon_wind_tunnel_short.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_fastball_throw_end" {
	"pov_pete_core_anims\ptpov_beacon_fastball_throw_end.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 403 "reload_titan_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_fastball_lob_end" {
	"pov_pete_core_anims\ptpov_beacon_fastball_lob_end.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 98 "reload_titan_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_dish_module_01" {
	"pov_pete_core_anims\ptpov_beacon_dish_module_01.smd"
	{ event AE_CL_PLAYSOUND 0 "Beacon_DishArmMove_Sequence" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 28 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 56 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 68 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 81 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 87 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 127 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 140 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 147 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 189 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 280 "reload_titan_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_dish_module_02" {
	"pov_pete_core_anims\ptpov_beacon_dish_module_02.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 126 "snap_gun" }
	{ event AE_CL_VSCRIPT_CALLBACK 180 "unsnap_gun" }
	{ event AE_CL_VSCRIPT_CALLBACK 190 "snap_gun_2" }
	{ event AE_CL_VSCRIPT_CALLBACK 264 "unsnap_gun_2" }
	{ event AE_CL_PLAYSOUND 0 "Beacon_Dish_Slide_Radar" }
	{ event AE_CL_PLAYSOUND 0 "Beacon_Dish_Slide_Radar_Hit_01" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 23 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 55 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 79 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 123 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 135 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 203 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 232 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 253 "reload_titan_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_satellite_slide" {
	"pov_pete_core_anims\ptpov_beacon_satellite_slide.smd"
	{ event AE_CL_PLAYSOUND 0 "Beacon_Dish_Slide_Player" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 29 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 39 "titan_damaged_med" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 49 "titan_damaged_med" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 59 "titan_damaged_big" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_beacon_satellite_freefall" {
	"pov_pete_core_anims\ptpov_beacon_satellite_freefall.smd"
	{ event AE_CL_PLAYSOUND 0 "Beacon_Dish_Slide_FreeFall" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 2 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 75 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 104 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 307 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 375 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 410 "reload_pilot_large" }
	fadein 0.4
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_cavalry_arrives_player" {
	"pov_pete_core_anims\ptpov_beacon_cavalry_arrives_player.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_cavalry_arrives_player_IDLE" {
	"pov_pete_core_anims\ptpov_beacon_cavalry_arrives_player_IDLE.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_beacon_cavalry_arrives_player_alt" {
	"pov_pete_core_anims\ptpov_beacon_cavalry_arrives_player_alt.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 175 "screenshake:1:20:1" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 175 "reload_pilot_small" }
	{ event AE_CL_VSCRIPT_CALLBACK 220 "screenshake:1:20:1" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 220 "reload_pilot_small" }
	{ event AE_CL_VSCRIPT_CALLBACK 255 "screenshake:1:20:1" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 255 "reload_pilot_small" }
	{ event AE_CL_VSCRIPT_CALLBACK 280 "screenshake:1:20:1" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 280 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 302 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1060 "reload_pilot_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_beacon_cavalry_arrives_player_alt_IDLE" {
	"pov_pete_core_anims\ptpov_beacon_cavalry_arrives_player_alt_IDLE.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_sewers_radio_equip_sequence_01" {
	"pov_pete_core_anims\ptpov_sewers_radio_equip_sequence_01.smd"
	{ event AE_SV_VSCRIPT_CALLBACK 140 "signal:AnimRadioGet_PlayRadioTransmission" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_Kane_boss_helmet_grab_pilot" {
	"pov_pete_core_anims\ptpov_Kane_boss_helmet_grab_pilot.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 22 "sewers_helmet_grab_land_on_titan" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 64 "sewers_helmet_grab_hatch_open_start" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 100 "sewers_helmet_grab_hatch_open_end" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 220 "sewers_helmet_grab_grab_kane" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 239 "sewers_helmet_grab_remove_helmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 415 "sewers_helmet_grab_radio_detatch" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 490 "sewers_helmet_grab_radio_atatch" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 725 "sewers_helmet_grab_jump_off" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 750 "sewers_helmet_grab_jump_off" }
	{ event AE_SV_VSCRIPT_CALLBACK 430 "signal:AnimRadioGet_RadioDetachFromHelmet" }
	{ event AE_SV_VSCRIPT_CALLBACK 460 "signal:AnimRadioGet_PlayRadioTransmission" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_fall_land" {
	"pov_pete_core_anims\ptpov_timeshift_fall_land.smd"
	{ event AE_CL_PLAYSOUND 1 "Timeshift_Scr_LongFallLanding" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 3 "timeshift_fan_drop" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_skywalk_jumpscare" {
	"pov_pete_core_anims\ptpov_timeshift_skywalk_jumpscare.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_helmet_grab_sequence" {
	"pov_pete_core_anims\ptpov_timeshift_helmet_grab_sequence.smd"
	{ event AE_CL_PLAYSOUND 0 "Timeshift_Scr_TakeHelmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 54 "timeshift_take_helmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 97 "timeshift_take_helmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 123 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 153 "timeshift_take_helmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 181 "timeshift_take_helmet" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 351 "reload_pilot_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_hologram_sequence_start" {
	"pov_pete_core_anims\ptpov_timeshift_hologram_sequence_start.smd"
	{ event AE_CL_PLAYSOUND 0 "Timeshift_Scr_GiveHelmetToBT" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 38 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 85 "timeshift_vortex_helmet_start" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 108 "timeshift_vortex_helmet_end" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_device_equip_sequence" {
	"pov_pete_core_anims\ptpov_timeshift_device_equip_sequence.smd"
	{ event AE_CL_PLAYSOUND 0 "Timeshift_Scr_EquipDevice" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 74 "timeshift_take_device_01" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 122 "timeshift_take_device_02" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "ptpov_timeshift_device_equip_sequence_02" {
	"pov_pete_core_anims\ptpov_timeshift_device_equip_sequence_02.smd"
	{ event AE_CL_STOP_PARTICLE_EFFECT 1 "P_timeshift_gauntlet_engage playendcap" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 18 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 43 "reload_pilot_small" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 101 "P_timeshift_gauntlet_engage follow_attachment L_BACKHAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 140 "P_timeshift_gauntlet_engage follow_attachment L_BACKHAND" }
	{ event AE_SV_VSCRIPT_CALLBACK 101 "signal:AnimTimeshift" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 101 "timeshift_timetravel_manual" }
	{ event AE_SV_VSCRIPT_CALLBACK 140 "signal:AnimTimeshift" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 140 "timeshift_timetravel_manual" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_wake_idle" {
	"pov_pete_core_anims\ptpov_timeshift_wake_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_timeshift_wake" {
	"pov_pete_core_anims\ptpov_timeshift_wake.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 121 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 144 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 160 "reload_pilot_small" }
	{ event AE_CL_PLAYSOUND 12 "Timeshift_Scr_CoreScan_CooperGetUp" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 117 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_PLAYSOUND 115 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 117 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 118 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 118 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 120 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 125 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 128 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_PLAYSOUND 126 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 128 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 129 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 128 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 130 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 132 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 138 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 140 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 146 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 150 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_PLAYSOUND 148 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 150 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 160 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 166 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 168 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 175 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 176 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 178 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 180 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 181 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 183 "AnimTimeshiftSkinSwapRed" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_discard_start" {
	"pov_pete_core_anims\ptpov_timeshift_discard_start.smd"
	{ event AE_CL_PLAYSOUND 32 "Timeshift_Scr_CoreScan_CooperRemoveDevice" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 64 "timeshift_rip_off_device" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 4 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 15 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_CREATE_PARTICLE_EFFECT 37 "P_ts_gauntlet_brkn_spark follow_attachment L_BACKHAND" }
	{ event AE_CL_PLAYSOUND 2 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 4 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 6 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 5 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 7 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 8 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 6 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 8 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 11 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 9 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 11 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 14 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 14 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 16 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 18 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 16 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 18 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 19 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 18 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 20 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 21 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 20 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 22 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 26 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 28 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 30 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 32 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 30 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 32 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 39 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 41 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 43 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 44 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 43 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 45 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 46 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 45 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 47 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 48 "AnimTimeshiftSkinSwapNone" }
	{ event AE_CL_PLAYSOUND 47 "Timeshift_Scr_DeviceSpark" }
	{ event AE_SV_VSCRIPT_CALLBACK 49 "AnimTimeshiftSkinSwapRed" }
	{ event AE_SV_VSCRIPT_CALLBACK 50 "AnimTimeshiftSkinSwapNone" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_discard_end" {
	"pov_pete_core_anims\ptpov_timeshift_discard_end.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_timeshift_broken" {
	"pov_pete_core_anims\ptpov_timeshift_broken.smd"
	{ event AE_CL_CREATE_PARTICLE_EFFECT 49 "P_timeshift_gauntlet_engage follow_attachment L_BACKHAND" }
	{ event AE_CL_PLAYSOUND 0 "Timeshift_Scr_FirstBrokenDeviceUse" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 49 "timeshift_timetravel_broken" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_fastball_throw_end" {
	"pov_pete_core_anims\ptpov_s2s_fastball_throw_end.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 403 "reload_titan_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "pt_pov_joystick_AIMS" {
	"pov_pete_core_anims\pt_pov_joystick_AIMS.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "Aim_joystick_AIM" {
	"a_aim_joystick_R_up_left"
	"a_aim_joystick_R_up_center"
	"a_aim_joystick_R_up_right"
	"a_aim_joystick_R_mid_left"
	"a_aim_joystick_R_mid_center"
	"a_aim_joystick_R_mid_right"
	"a_aim_joystick_R_down_left"
	"a_aim_joystick_R_down_center"
	"a_aim_joystick_R_down_right"
}

$sequence "ptpov_s2s_bridge_console_start" {
	"pov_pete_core_anims\ptpov_s2s_bridge_console_start.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 0 "create_dataknife" }
	{ event AE_CL_PLAYSOUND 0 "s2s_bridge_console_start" }
	{ event AE_CL_VSCRIPT_CALLBACK 48 "knife_popout" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 43 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 79 "reload_pilot_small" }
	fadein 0.25
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_s2s_bridge_console_end" {
	"pov_pete_core_anims\ptpov_s2s_bridge_console_end.smd"
	{ event AE_CL_PLAYSOUND 0 "s2s_bridge_console_end" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 61 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 68 "reload_pilot_large" }
	fadein 0
	fadeout 0
	snap
	fps 30
}

$sequence "ptpov_s2s_bridge_console_idle" {
	"pov_pete_core_anims\ptpov_s2s_bridge_console_idle.smd"
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_joystick_AIM"
	snap
	fps 30
	loop
}

$sequence "pt_pov_joystick_idle" {
	"pov_pete_core_anims\pt_pov_joystick_idle.smd"
	fadein 0.2
	fadeout 0.2
	addlayer "Aim_joystick_AIM"
	snap
	fps 30
	loop
}

$sequence "ptpov_s2s_bridge_punch_embark" {
	"pov_pete_core_anims\ptpov_s2s_bridge_punch_embark.smd"
	{ event AE_CL_PLAYSOUND 0 "s2s_anim_bt_embark" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 22 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 84 "reload_pilot_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_player_stumble_01" {
	"pov_pete_core_anims\ptpov_s2s_player_stumble_01.smd"
	fadein 0.05
	fadeout 0.25
	fps 30
}

$sequence "ptpov_s2s_player_stumble_02_left" {
	"pov_pete_core_anims\ptpov_s2s_player_stumble_02_left.smd"
	fadein 0.05
	fadeout 0.25
	fps 30
}

$sequence "ptpov_s2s_player_stumble_03_back" {
	"pov_pete_core_anims\ptpov_s2s_player_stumble_03_back.smd"
	fadein 0.05
	fadeout 0.25
	fps 30
}

$sequence "ptpov_s2s_player_stumble_04_right" {
	"pov_pete_core_anims\ptpov_s2s_player_stumble_04_right.smd"
	fadein 0.05
	fadeout 0.25
	fps 30
}

$sequence "ptpov_s2s_widowfall" {
	"pov_pete_core_anims\ptpov_s2s_widowfall.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_s2s_widowfall_02" {
	"pov_pete_core_anims\ptpov_s2s_widowfall_02.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_viper_returns_start" {
	"pov_pete_core_anims\ptpov_s2s_viper_returns_start.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 22 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 53 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 81 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 232 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 280 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 290 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 307 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 308 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 309 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 310 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 311 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 312 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 313 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 314 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 315 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 316 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 317 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 318 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 319 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 320 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 321 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 322 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 323 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 324 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 325 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 326 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 327 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 328 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 329 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 330 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 331 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 332 "reload_pilot_large" }
	fadein 0.2
	fadeout 0
	fps 30
}

$sequence "ptpov_s2s_viper_returns_middle" {
	"pov_pete_core_anims\ptpov_s2s_viper_returns_middle.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 10 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 32 "reload_pilot_large" }
	fadein 0
	fadeout 0
	fps 30
}

$sequence "ptpov_s2s_viper_returns_end" {
	"pov_pete_core_anims\ptpov_s2s_viper_returns_end.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 19 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 50 "titan_damaged_big" }
	fadein 0
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_end_fight_landing" {
	"pov_pete_core_anims\ptpov_s2s_end_fight_landing.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_end_fight_fall" {
	"pov_pete_core_anims\ptpov_s2s_end_fight_fall.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 46 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 61 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 154 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 171 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 218 "titan_damaged_big" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 272 "titan_damaged_big" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_end_fight_knockback" {
	"pov_pete_core_anims\ptpov_s2s_end_fight_knockback.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 2 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 3 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 4 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 5 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 6 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 7 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 8 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 9 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 10 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 11 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 12 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 13 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 14 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 15 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 16 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 17 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 18 "reload_pilot_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_end_fight_knockback_02" {
	"pov_pete_core_anims\ptpov_s2s_end_fight_knockback_02.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 0 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 1 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 2 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 3 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 4 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 5 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 6 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 7 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 8 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 9 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 10 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 20 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 37 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 88 "reload_pilot_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_lifeboats_jump" {
	"pov_pete_core_anims\ptpov_s2s_lifeboats_jump.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_lifeboats_land" {
	"pov_pete_core_anims\ptpov_s2s_lifeboats_land.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 3 "titan_damaged_big" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_start1" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_start1.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_start2_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_start2_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_start2" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_start2.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 66 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 81 "reload_pilot_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_1_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_1_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_1" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_1.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_2_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_2_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_2" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_2.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_3_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_3_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_3" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_3.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_push_end" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_push_end.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_insert_end" {
	"pov_pete_core_anims\ptpov_s2s_sphere_insert_end.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_player_protect" {
	"pov_pete_core_anims\ptpov_s2s_sphere_player_protect.smd"
	{ event AE_CL_RUMBLE_PLAY_LOCAL 122 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 153 "reload_pilot_small" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_player_protect_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_player_protect_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_s2s_sphere_end" {
	"pov_pete_core_anims\ptpov_s2s_sphere_end.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_s2s_sphere_end_idle" {
	"pov_pete_core_anims\ptpov_s2s_sphere_end_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_TDay_drop_player" {
	"pov_pete_core_anims\ptpov_TDay_drop_player.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_TDay_drop_player_start" {
	"pov_pete_core_anims\ptpov_TDay_drop_player_start.smd"
	{ event AE_CL_VSCRIPT_CALLBACK 818 "fade_to_black:16" }
	{ event AE_CL_PLAYSOUND 98 "TDay_Intro_Cooper_ThumbsUp" }
	{ event AE_CL_PLAYSOUND 715 "TDay_Intro_Cooper_TitanActivate" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 170 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 211 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 238 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 239 "reload_pilot_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 315 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 345 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 370 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 515 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 536 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 721 "reload_titan_large" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 742 "reload_titan_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 727 "rumble_pilot_hurt" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 777 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 791 "reload_pilot_small" }
	{ event AE_CL_RUMBLE_PLAY_LOCAL 849 "reload_titan_large" }
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_melee_F_neckslash_D" {
	"pov_pete_core_anims\ptpov_synced_melee_F_neckslash_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_melee_B_stab_D" {
	"pov_pete_core_anims\ptpov_synced_melee_B_stab_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_melee_F_struggle_D" {
	"pov_pete_core_anims\ptpov_synced_melee_F_struggle_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_melee_F_chestpunch_D" {
	"pov_pete_core_anims\ptpov_synced_melee_F_chestpunch_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_synced_melee_B_chestpunch_D" {
	"pov_pete_core_anims\ptpov_synced_melee_B_chestpunch_D.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_medium_hijack_B" {
	"pov_pete_core_anims\ptpov_rodeo_medium_hijack_B.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_medium_hijack_F" {
	"pov_pete_core_anims\ptpov_rodeo_medium_hijack_F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_medium_hijack_L" {
	"pov_pete_core_anims\ptpov_rodeo_medium_hijack_L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_medium_hijack_R" {
	"pov_pete_core_anims\ptpov_rodeo_medium_hijack_R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_ride_R_hijack_battery" {
	"pov_pete_core_anims\ptpov_rodeo_ride_R_hijack_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_ride_R_return_battery" {
	"pov_pete_core_anims\ptpov_rodeo_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_ride_L_return_battery" {
	"pov_pete_core_anims\ptpov_rodeo_ride_L_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_medium_grenade_1st" {
	"pov_pete_core_anims\ptpov_rodeo_medium_grenade_1st.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_nuke_rodeo_ride_R_return_battery" {
	"pov_pete_core_anims\ptpov_nuke_rodeo_ride_R_return_battery.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_ride_F_idle" {
	"pov_pete_core_anims\ptpov_rodeo_ride_F_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_ride_L_idle" {
	"pov_pete_core_anims\ptpov_rodeo_ride_L_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_ride_R_idle" {
	"pov_pete_core_anims\ptpov_rodeo_ride_R_idle.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
	loop
}

$sequence "ptpov_rodeo_trans_F2L" {
	"pov_pete_core_anims\ptpov_rodeo_trans_F2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_trans_F2R" {
	"pov_pete_core_anims\ptpov_rodeo_trans_F2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_trans_L2F" {
	"pov_pete_core_anims\ptpov_rodeo_trans_L2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_trans_L2R" {
	"pov_pete_core_anims\ptpov_rodeo_trans_L2R.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_trans_R2F" {
	"pov_pete_core_anims\ptpov_rodeo_trans_R2F.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_trans_R2L" {
	"pov_pete_core_anims\ptpov_rodeo_trans_R2L.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_entrance_F_front" {
	"pov_pete_core_anims\ptpov_rodeo_entrance_F_front.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_entrance_L_left" {
	"pov_pete_core_anims\ptpov_rodeo_entrance_L_left.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_rodeo_entrance_R_right" {
	"pov_pete_core_anims\ptpov_rodeo_entrance_R_right.smd"
	fadein 0.2
	fadeout 0.2
	fps 30
}

$sequence "ptpov_mp_battery_port_insert" {
	"pov_pete_core_anims\ptpov_mp_battery_port_insert.smd"
	{ event AE_CL_PLAYSOUND 0 "TitanWar_Battery_Insert" }
	{ event AE_SV_VSCRIPT_CALLBACK 45 "detach_battery" }
	{ event AE_CL_PLAYSOUND 48 "TitanWar_Battery_Insert_Power" }
	fadein 0.2
	fadeout 0.2
	fps 30
}
